### ISSUE TITLE
Improved memory leak prevention in Dicom.Imaging.Codec.Jpeg.i

### ISSUE THREAD

**Issue by anders9ustafsson** [fo-dicom/fo-dicom#1]
Hi everyone!

I thought it would be best to enable the Issues tab as well, to facilitate the logging of fixes and enhancements. I hope everyone is OK with this.

Here is one issue that I want to bring up right away, as it concerns some code that you recently improved, @hdesouky . Please have a look, everyone and tell me what you think; am I drawing the right conclusions?

---
Regarding [Dicom.Imaging.Codec.Jpeg.i, line 508 and above](https://github.com/fo-dicom/fo-dicom/blob/master/DICOM%20%5BNative%5D/Dicom.Imaging.Codec.Jpeg.i#L508):

... wouldn't it be even safer to move the declaration of `frameArray` to the outer scope (before `try`) and place the `delete` in the `finally` block instead, like this:

    PinnedByteArray^ frameArray = nullptr;
    try {
      ...
      frameArray = gcnew PinnedByteArray(frameSize);
      ...
    }
    finally {
      if (frameArray != nullptr) {
        delete frameArray;
        frameArray = nullptr;
      }
      ...
    }

If I am not mistaken, this will ensure that `frameArray` gets properly cleaned up even if an exception occurs in the latter part of the `try` block.

**Comment by IanYates** [comment]
I haven't done C++ in many years (and even then it wasn't pro level, although I enjoyed reading that 1000+ page book I had about it)...  

However, the `gcnew` operator, from what I can tell, implies that the garbage collector will clean up the object.  There's conflicting stuff out on the net about needing `delete` with `gcnew`, but the best resource I could find (http://weblogs.thinktecture.com/cnagel/2006/04/ccli-finalize-and-dispose.html) indicates that `delete` will translate to a `.Dispose()` call, which makes good sense.

Given all of that, what you've said makes good sense to me.

**Comment by hdesouky** [comment]
Thanks for adding the issues tab.

@IanYates  gcnew is special keyword introduced by Managed c++ to allocated managed objects.
The issue is PinnedByteArray is using un-managed Handles classes to pin a byte array in memory to be able to work with its pointer through the JPEG encoders and decoders.

When working with un-managed objects it is not wise to rely on the GC to dispose these objects since it is dealing with valuable resources (memory handles). So disposing the PinnedByteArray is mandatory at the end of encoding/decoding operation.

@anders9ustafsson  Your proposed clean up code is the right way to do it.
