### ISSUE TITLE
Inconsistent handling of Get<T> default values for specific element types

### ISSUE THREAD

**Issue by anders9ustafsson** [fo-dicom/fo-dicom#10]
In [DICOMElement.cs](https://github.com/fo-dicom/fo-dicom/blob/master/DICOM/DicomElement.cs), the abstract base class `DicomElement` implements a `Get` method with the following signature:

    public abstract T Get<T>(int item = -1);

Some of the other classes deriving from `DicomElement` (both abstract and instantiatable), implements the `Get` method with a different default value, for example:

    public abstract class DicomValueElement<Tv> : DicomElement where Tv: struct {
      public override T Get<T>(int item = 0) { ... }
    }
    ...
    public class DicomUnsignedShort : DicomValueElement<ushort> {
      public override T Get<T>(int item = 0) { ... }
    }

This leads to inconsistent behavior when `DicomUnsignedShort` represents an array of `ushort`:s and the `Get` method is invoked with a default value:

    DicomUnsignedShort elem1 = new DicomUnsignedShort(DicomTag.xxx, 1, 2, 3, 4);
    DicomElement elem2 = new DicomUnsignedShort(DicomTag.xxx, 5, 6, 7, 8);
    ...
    var firstItem1 = elem1.Get<ushort>();    // OK, default value for DicomUnsignedShort object is 0
    var firstItem2 = elem2.Get<ushort>();    // ArgumentOutOfRangeException, default value for DicomElement object is -1

A review of the `Get` implementations in *DicomElement.cs* is required to avoid out-of-range exceptions caused by incorrectly handled default values.

**Comment by IanYates** [comment]
I'm assuming there's deliberate intent behind some of them having a default of `-1` and others having a default of `0`.

It seems to me that the -1 default is intended in cases where the index is supposed to be irrelevant, such as calling `Get<string>()` on a DicomMultiStringElement.

Unfortunately, as your example excellently highlights, in C#, default values for missing method parameters are calculated at compile-time and are based on the type information available.

I can think of a couple of approaches to handle this.
1. For cases such as the one you provided tests for, treat -1 as a sentinel value and substitute in the 0 instead.
2. Replace the `int item` with `int? item = null` instead so that the null value is our sentinel.  That would make the intention more clear and still be source compatible but wouldn't be binary compatible and would require a recompilation
3. Set the defaults to -1 everywhere so that the -1 sentinel value is at least consistently applied.  Like 2, this would be source compatible and still require a recompilation for the new default values to take effect
4. Provide two public overloaded methods - `Get<T>()` and `Get<T>(int item)` and implement accordingly.  The easiest implementation would probably see the existing `Get<T>(int item = ???)` methods made protected and consistent sentinel values applied throughout.  It does have the advantage of not exposing the default values to external libraries but otherwise is more work than 2 & 3

@anders9ustafsson - is this a new problem for you or have you already solved it in one of your forks?

**Comment by anders9ustafsson** [comment]
Yes, I also believe it was a conscious choice once upon a time to use different default values in the different overrides, so one has to be careful not to lose the original intent when fixing this issue.

When it comes to solving the issue, I personally lean towards your option 4 right now, @IanYates . Haven't thought it through entirely, though, so I may change my mind :-)

I did recognize the issue some time ago and made a partial fix in the *portable* branch in my *cureos* fork, but I actually think my fix would also fail the unit test that I added an hour ago. So no, I don't have a ready-made solution right now.
