### ISSUE TITLE
support .net4.0

### ISSUE THREAD

**Issue by douxiaoping** [fo-dicom/fo-dicom#1000]
### Expected behavior
support .net4.0??

**Comment by gofal** [comment]
In 2015 microsoft announced EndOfLive of .net 4, 4.5 and 4.5.1

If you still for some reasons need to use a framework that has so security updates since the last 5 years, please use older fo-dicom version from nuget, or just take the sourcecode and compile it for net4 yourself.
It should not be a problem, because the current code still has compiler-conditions to also compile for Unity, that based on netframework 3.5.

**Comment by gofal** [comment]
Close this due to inactivity. Please feel free to reopen this issue if you still face problems.
