### ISSUE TITLE
How do I ignore escape characters and choose the encoding of the JsonDicomConverter?

### ISSUE THREAD

**Issue by gasupidupi** [fo-dicom/fo-dicom#1002]
### Goal
I want to serialize a DicomDataset containing escape characters and special characters to a JSON string. I would like to choose to ignore the escape characters and set the right encoding for the special characters. How can I do that?

### Expected behavior
The tag inside the JSON should look like this when I serialize it:
```
    "vr": "UC",
    "Value": [
        "*éncöding*\\*example*\\*"
    ]
```

### Actual behavior
The tag inside the JSON looks like this when I serialize it currently:
```
    "vr": "UC",
    "Value": [
      "*?nc?ding*",
      "*example*",
      "*"
    ]
```

### Steps to reproduce the behavior
I have a DicomDataset containing a (Unlimited Characters) tag with a string value similar to this example:
`"*éncöding*\\*example*\\*"`

Then I serialize the DicomDataset to a JSON :
`string content = JsonConvert.SerializeObject(dataset, Formatting.Indented, new JsonDicomConverter(true));`

### fo-dicom version and OS/platform
fo-dicom 4.0.4, Windows 10, netcoreapp3.1

**Comment by gofal** [comment]
The encoding-problem could be an issue. I will have a closer look at it.

As far as "\\" is concerned, I am affraid, that will cause problems. The json serialization is very strict and defined in DICOM standard. This ensures, that json that was serialized with fo-dicom and then (after sent via webservices) deserialized from another application, result in exactly the same Dicomdataset - and the other way round of course.
So for VR, that allow an array of values, the character "\" is a delimiter.
If you serialize a text that contains a "\", but has no multiplicity - like for examle LT - then you will only get one value in json array.

instead of breaking the Json serializer I would aks you to do the following:
- serialize the json
- load the json into a JObject
- iterate this jObject and maniuplate the values there (the the array of vallues, concenate them with "\\" in between and set as new value)
- write the manipulated json string.

**Comment by gasupidupi** [comment]
Thank you for your answer. I was able to adjust the delimiter using your description. Have you found the source of the encoding-problem?

**Comment by gasupidupi** [comment]
The issue with the encoding was a small and stupid error on my side. I just forgot to add the encoding as a parameter when instantiating the DicomItems and adding them to the DicomDataset.
