### ISSUE TITLE
Change Transfer Syntax ImplicitVRLittleEndian to JPEGProcess14SV1

### ISSUE THREAD

**Issue by edautov** [fo-dicom/fo-dicom#1018]
### Expected behavior
change dicom file from Implicit VR Little Endian to JPEG Lossless, Nonhierarchical, First-Order Prediction
var newFile = file.Clone(DicomTransferSyntax.JPEGProcess14SV1);

and compress a dcm file

### Actual behavior
An unhandled exception of type 'Dicom.DicomDataException' occurred in Dicom.Core.dll
Additional information: Tag: (0002,0010) not found in dataset

### Steps to reproduce the behavior
var file = DicomFile(@"file.dcm");
var newFile = file.Clone(DicomTransferSyntax.JPEGProcess14SV1);

### fo-dicom version and OS/platform
fo-dicom.Desktop, VS 2015
Debug x86

**Comment by gofal** [comment]
can you verify that the dicomfile, you want to clone, actually contains dicom tag 0002,0010?

So does this exception happen only on this file or on all files?

the Clone method reads Tag 0002,0010, which is one of the mandatory tags.

**Comment by edautov** [comment]
Thanks.
You right,
In my collection dicom files don't have tag 0002,0010.
With next code, dicom files is OK.

var transcoder = new DicomTranscoder(file.Dataset.InternalTransferSyntax, DicomTransferSyntax.ExplicitVRLittleEndian);
file = transcoder.Transcode(file);var newFile = file.Clone(DicomTransferSyntax.JPEGProcess14SV1);

I hope that's right?

**Comment by gofal** [comment]
Sure, thats right. But I'd recomment that you do not explicitly transcode to ExplicitVRLitteEndian and then to JPEGProcess14SV1. That means you transcode the file twice. Why not creating a transcoder from 'file.Dataset.InternalTransferSyntax' directly to 'JPEGProcess14SV1)? then you are done within the two lines:

        var transcoder = new DicomTranscoder(file.Dataset.InternalTransferSyntax, DicomTransferSyntax.JPEGProcess14SV1);
        var newFile = transcoder.Transcode(file);

the DicomTranscoder then iterates its internal registered encoders and decoders and finds the most efficient way. 

Do you know the source of the files? maybe you could give them a hint, that the files are no valid DICOM files because the required 0002,0010 is missing. The best solution would be, if they fix it as soon as possible.

**Comment by edautov** [comment]
Thanks for the help!
