### ISSUE TITLE
FO-DICOM for windows xp

### ISSUE THREAD

**Issue by yadavvirus** [fo-dicom/fo-dicom#1031]
How can I use fo-dicom labrary in windows xp to build WINFORM Application for windows XP platform.
As xp not supporting dotnet framework 4.5 or highr. Please help
Thank you in advance.

**Comment by gofal** [comment]
windows xp is unsupported since 8.4.2014 (six years ago). Please do not run an application handling with medical data on such an outdated system!

of course fo-dicom has no intention to support windows xp.
But current fo-dicom sources also compile for Unitiy that is based on dotnet framework 3.5. So there are quite some compiler conditions `#if !NET35`. So if you checkout the sourcecode and build the application with dotnet framework 3.5 then this should work. But I really do not recommend it.

**Comment by amoerie** [comment]
This sort of thing is usually covered by a backing enterprise firm that takes a very generous fee for such a backwards compatibility service.

But we're not an enterprise firm, just volunteer developers, so we don't spend our already limited time on supporting ancient platforms. Sorry!

**Comment by amoerie** [comment]
Closing this issue as there are no plans to support this.
