### ISSUE TITLE
Consider IAsyncEnumerable in IAsyncDicomC*Provider

### ISSUE THREAD

**Issue by amosonn** [fo-dicom/fo-dicom#1037]
Some `IAsyncDicomC*Provider`-s, specifically `CMove`, `CFind` and `CGet` currently return `Task<IEnumerable<Task<DicomC*Response>>>`. This type doesn't actually enable completely async enumeration of those responses - once the first `Task` is ready, the `IEnumerable` already needs to be ready, and know e.g. the number of responses that will be provided.

The idiomatic type for this type of async enumeration is `IAsyncEnumerable`, which is part of the standard library since the .NET Standard 2.1 and .NET Core 3 targets, and is available for other targets via `Ix.Net` https://github.com/dotnet/reactive . Would it be possible to switch to them / add another interface using them? Converting from the previous types to those types can be done automatically be some helper method (this in C#8 syntax, older syntax requires some more boilerplate):
```csharp
async IAsyncEnumerable<T> Convert<T>(Task<IEnumerable<Task<T>>> task)
{
    var iter = await task;
    foreach (Task<T> t in iter)
    {
        yield return await t;
    }
}
```

Converting the other way around is not always possible - except by awaiting the entire `IAsyncEnumerable` on the first task. It is for those cases, where the responses are coming one-by-one, that the new interface will be useful.
```csharp
async Task<IEnumerable<Task<T>>> Convert<T>(IAsyncEnumerable<T> iter)
{
    var l = new List<Task<T>>;
    await foreach (T t in iter)
    {
        l.Add(Task.FromResult(t));
    }
    return l;
}
```

Edit:
I can draft a PR for this, if this is acceptable (I guess someone else should choose the names for the new interfaces ;) ).

**Comment by amoerie** [comment]
Hi, thanks for your suggestion!

Believe me man, I wanted to, but we need to stay compatible with .NET Framework for now.
The combo of Task<IEnumerable<Task>> isn't pretty, but it's the closest we can get to IAsyncEnumerable while staying backwards compatible. 

I'm afraid this feature won't be feasible until we decide to move to .NET Standard 2.1, which won't be for a long time I'm afraid (because this means dropping support for .NET Framework)

Furthermore, I don't see how this can be added easily using #ifdefs so that this code would only light up for .NET Standard 2.1 without modifying a whole bunch of network layer code.

**Comment by amosonn** [comment]
I think that Ix.NET bridges exactly this gap, making these types available also for .NET Standard 2.0 (albeit without the nice C#8 syntax).

Alternatively, I think the only place where these interfaces are used is inside the great switch-case (of ifs) in `DicomService.PerformDimseAsync`. So a new block with something like `if (this is INewAsyncDicomCFindProvider thisAsEtc)` could be added there with `#ifdef`-s, if the dependency on Ix.NET is not wanted / doesn't work well enough.

If I drafted an MR, how would you go around testing it also for .NET Standard 2.0?

**Comment by amoerie** [comment]
I'd prefer #ifdefs over adding a dependency to Ix.NET, especially
considering that this is now a language feature, albeit only on a very
recent version.

Feel very free to draft an MR for this. I'd wish to reuse the
IAsync*Provider interfaces and literally give them a different signature on
net standard 2.1. That makes it explicit that IAsyncEnumerable is an
upgrade for the existing signature.

To test them, you could add target framework netcore31 to the unit tests
project, and then duplicate the tests for the async providers also using
ifdefs.

As you'll probably find, it will get a little ugly with the ifdefs in
various places, but if that's mostly limited to the tests I don't mind. If
the implementation itself only has a few of these, that's okay.

Op di 26 mei 2020 20:03 schreef amosonn <notifications@github.com>:

**Comment by amosonn** [comment]
I posted a PR. Do note that this makes it a breaking change for anyone who is already using netstandard2.1 or netcore3.0, so I don't know what the correct way to version this would be.

**Comment by gofal** [comment]
We also should not forget that the interface is for convenience and that you do have full control of the `DicomService` class when implementing the handlers. 
What I want to say: if you are facing some issues because the Task<IEnumberable<Task<Response>>> is not as asynchronous as you need it, then you still have the possiblility to call then `SendResponse` yourself like:

        public async Task<IEnumerable<Task<DicomCFindResponse>>> OnCFindRequestAsync(DicomCFindRequest request)
        {
            var items = await DoSomeDatabaseQuery()
            foreach (var item in items)
            {
                  var someValue = await CalculateSomeValue(item);
                  SendResponse(new DicomCFindResponse(request, DicomStatus.Pending) { Dataset = someValue } ));
            }
            return Task.FromResult(Enumerable.Empty<Task<DicomCFindResponse>>());
        }

**Comment by gofal** [comment]
Now that there are compiler-conditions. Does that mean, that we have to publish 2 different nuget-packages, one for netstandard2.0 and one for netstandard2.1?
Or is it sufficient, that you compile the source against netstandard2.1 yourself for your needs?

**Comment by amoerie** [comment]
I am afraid that our nuget package releases would have to contain separate DLLs for net standard 2.1, yes.. 

Also, I had never considered the trick to call SendResponse instead of returning responses! 😮

**Comment by gofal** [comment]
> Also, I had never considered the trick to call SendResponse instead of returning responses!

the methods `SendResponse` and `SendRequest` are public part of the API.
This is a documentation issue, that such possibilities are not aware to the devs. Documentation / tutorials / guides are rather weak in fo-dicom 😢 . My english is too bad so I do not dare to start this.

**Comment by amoerie** [comment]
> I posted a PR. Do note that this makes it a breaking change for anyone who is already using netstandard2.1 or netcore3.0, so I don't know what the correct way to version this would be.

Circling back to this, I think if you modify the code that no signature is changed for fo-dicom 4.0, we don't have versioning issues, because 5.0 is still in early alpha mode and consumers should expect breaking changes still. 

I think it's the right call to use IAsyncEnumerable in .NET Core 3.0, this sets us on the correct path for the future, and the hassle for us today is quite small.

Or would you still prefer to keep the Task<IEnumerable<Task<>>> signature, @gofal ? Your argument that any scenario is supported by using SendResponse seemed to imply you were hesitant.

**Comment by JoakimRaySearch** [comment]
This was reverted (due to some misunderstanding) and then never added back to 5.0.0? This is really needed (or something similar) to get proper async handling of CMove etc, now we have to wait for all files before sending responses.

**Comment by amoerie** [comment]
What are you saying @JoakimRaySearch, looks like it's still there to me:

https://github.com/fo-dicom/fo-dicom/blob/b57d6bd89dae059241f23b8bb16d9716cf9669de/FO-DICOM.Core/Network/IDicomCMoveProvider.cs#L18

**Comment by JoakimRaySearch** [comment]
True, I looked here

https://github.com/fo-dicom/fo-dicom/blob/b57d6bd89dae059241f23b8bb16d9716cf9669de/DICOM/Network/IAsyncDicomCMoveProvider.cs#L19

But that's for the old .NetFramework then, Only NetCore get the proper IAsyncEnumerable?

**Comment by JoakimRaySearch** [comment]
Just a side note, are there any reason to keep the old code on the development branch? Seems just confusing to me.

**Comment by amoerie** [comment]
There was a time, not so long ago, where we were actively developing both v4 and v5. Then, it made sense. Now, since the official release of v5 (which was not so long ago) I agree that it is more confusing than useful.

@gofal What do you think? Perhaps it would make sense to make a v4 branch and remove the v4 code from the development branch.

**Comment by gofal** [comment]
Yes, agree. There is already a v4-branch. this should be updated to the current master. in the v4-branch we could delete the v5-projects, and then in the master-branch we remove the v4-projects.

Are there any open PRs, that we should review and merge first because they also touch v4-code, to avoid conflicts?

**Comment by gofal** [comment]
I do not see open PRs, except the two incomplete 1114 and 807. I will cleanup them and spearate the code as described above.

**Comment by amoerie** [comment]
While we're on the subject,  shouldn't we close those two old PRs? They've been inactive more > 1 year, so the authors should probably reopen and rebase their work if they want to advance it.

**Comment by gofal** [comment]
yes, thats exactly what i meant when I wrote "i will cleanup them".

**Comment by amoerie** [comment]
> yes, thats exactly what i meant when I wrote "i will cleanup them".

Apologies for the misunderstanding! I thought it was a type and you meant "I will cleanup then" 🤐
