### ISSUE TITLE
An error occured using fo-dicom：No codec registered for tranfer syntax: JPEG Baseline (Process 1): Default Transfer Syntax for Lossy JPEG 8 Bit Image Compression

### ISSUE THREAD

**Issue by Ctx0305** [fo-dicom/fo-dicom#1040]
### Expected behavior
It can operate normally in any environment

### Actual behavior
It works on a  Win10 x86 system,but it doesn't work on a Win x64 system

### fo-dicom version and OS/platform
fo-dicom  v4.0.30319

**Comment by gofal** [comment]
please take a look at this wiki: https://github.com/fo-dicom/fo-dicom/wiki/Native-codecs-on-.NET
how do you build your project? as netcore or netframework? in AnyCpu, x86, x64? Are you using fo-dicoms built in Transcodermanager or are you using Efferent's transcoder manager?

Please add more details. Its almoust impossible to help otherwise.

**Comment by gofal** [comment]
I will close this issue due to inactivity. If you have more informations please feel free to reopen this issue!

**Comment by Ctx0305** [comment]
thx




| |
陈天祥
|
|
邮箱：c18210887065@163.com
|

签名由 网易邮箱大师 定制

On 07/03/2020 03:39, Reinhard Gruber wrote:

Closed #1040.
