### ISSUE TITLE
Are there any plan support netstandard2.0?

### ISSUE THREAD

**Issue by cocosip** [fo-dicom/fo-dicom#1042]
Now i use fo-dicom v5.0.0-alpha1, i find the package was deprecated 
Will continue to develop support netstandard2 ? Are there any roadmap?

**Comment by gofal** [comment]
Of course it continues developing!
I deprecated this package because it's not completed so far and I plan to do some changes in API.

The codec, that is shipped with fo-dicom in version 4, is only complete in NetFramework and only Windows. But Efferent created a great complete codec that runs on windows, linux and soon mac. See here: https://github.com/Efferent-Health/fo-dicom.Codecs/issues/6
Corona has blocked this process.

Would you use the new version 5 even if no codecs are available?
