### ISSUE TITLE
When I run the CStoreSCP, Visual Studio is shut down.

### ISSUE THREAD

**Issue by inininini** [fo-dicom/fo-dicom#1047]
### Expected behavior
I'm a new beginner at fo-dicom. When I run the CStoreSCP, I want to build a server which can take dicom files through the C-store protocol sent from other PCs.

### Actual behavior
When I run the CStoreSCP, Visual Studio is shut down. I've succeeded in sending a dicom file to free PACS software(named 'conquestdicomserver') through CStoreSCU and extracting image files from dicom through render.image(). 
But, I don't know how I can use CStoreSCP library. I want to build a PACS server like that free PACS software.

I attached my code. 
[CStoreSCP.zip](https://github.com/fo-dicom/fo-dicom/files/4762132/CStoreSCP.zip)

### Steps to reproduce the behavior
1. Create a new solution file of Visual studio 2019.
2. Install fo-dicom libraries from Nuget.(fo-dicom, fo-dicom.NLog)
3. Copy and paste the codes from programs.cs of C-Store SCP.
4. Run the solution file.

### fo-dicom version and OS/platform
Window 10, fo-dicom 4.0.5, Visual Studio 2019

**Comment by gofal** [comment]
The problem is with the application-type you created. If you look at the properties of the CStoreSCP project. Then the output-type of the project is "Windows Application". So it is expected that a WinForms is started. But in the main-method you start a fo-dicom server and access `Console.ReadLine()`. VisualStudio debugger seems to try to access a UI, but there is no.

Change the output-type of the project to "Console application", then it will run.

**Comment by amoerie** [comment]
One month later and the solution provided by @gofal seems very reasonable. I think this is not a fo-dicom issue. If you disagree, please open a new issue.
