### ISSUE TITLE
Possibly incorrect code about getting YBR_ FULL_ 422 image PixelData

### ISSUE THREAD

**Issue by kira-96** [fo-dicom/fo-dicom#1049]
Hi! I happened to see this piece of code in [PixelData.cs](https://github.com/fo-dicom/fo-dicom/blob/development/DICOM/Imaging/Render/PixelData.cs#L171).

``` csharp
...
else if (pi == PhotometricInterpretation.Rgb || pi == PhotometricInterpretation.YbrFull
         || pi == PhotometricInterpretation.YbrFull422 || pi == PhotometricInterpretation.YbrPartial422)
{
    var buffer = pixelData.GetFrame(frame);

    if (pixelData.PlanarConfiguration == PlanarConfiguration.Planar) buffer = PixelDataConverter.PlanarToInterleaved24(buffer);

    if (pi == PhotometricInterpretation.YbrFull) buffer = PixelDataConverter.YbrFullToRgb(buffer);
    else if (pi == PhotometricInterpretation.YbrFull422) buffer = PixelDataConverter.YbrFull422ToRgb(buffer, pixelData.Width);
    else if (pi == PhotometricInterpretation.YbrPartial422) buffer = PixelDataConverter.YbrPartial422ToRgb(buffer, pixelData.Width);

    return new ColorPixelData24(pixelData.Width, pixelData.Height, buffer);
}
else if (pi == PhotometricInterpretation.YbrFull422)
{
    var buffer = pixelData.GetFrame(frame);
    if (pixelData.PlanarConfiguration == PlanarConfiguration.Planar) throw new DicomImagingException("Unsupported planar configuration for YBR_FULL_422");
    return new ColorPixelData24(pixelData.Width, pixelData.Height, buffer);
}
...
```

There is already exists `pi == PhotometricInterpretation.YbrFull422` in the previous `if` condition, which means that it will never enter the following `if` condition.  
But when **Photometric Interpretation** is **YBR_ FULL_ 422**, Planar Configuration (0028,0006) shall be **0**. Please take a look [here](https://dicom.innolitics.com/ciods/mr-image/image-pixel/00280004).  
Does it mean that the following `if` condition should be correct?  
So, it should looked like this.  
``` csharp
...
else if (pi == PhotometricInterpretation.Rgb || pi == PhotometricInterpretation.YbrFull
         || pi == PhotometricInterpretation.YbrPartial422)
{
    var buffer = pixelData.GetFrame(frame);

    if (pixelData.PlanarConfiguration == PlanarConfiguration.Planar) buffer = PixelDataConverter.PlanarToInterleaved24(buffer);

    if (pi == PhotometricInterpretation.YbrFull) buffer = PixelDataConverter.YbrFullToRgb(buffer);
    else if (pi == PhotometricInterpretation.YbrPartial422) buffer = PixelDataConverter.YbrPartial422ToRgb(buffer, pixelData.Width);

    return new ColorPixelData24(pixelData.Width, pixelData.Height, buffer);
}
else if (pi == PhotometricInterpretation.YbrFull422)
{
    if (pixelData.PlanarConfiguration == PlanarConfiguration.Planar) throw new DicomImagingException("Unsupported planar configuration for YBR_FULL_422");
    var buffer = pixelData.GetFrame(frame);
    buffer = PixelDataConverter.YbrFull422ToRgb(buffer, pixelData.Width);
    return new ColorPixelData24(pixelData.Width, pixelData.Height, buffer);
}
...
```

**Comment by amoerie** [comment]
Possibly related to #645

**Comment by WernMich** [comment]
I do not see any relation to #645: this post / code section is related to how conversion to RGB is done. Issue #645 is related to frame size calculation of uncompressed YBR_FULL_422 images.

For me this code section looks strange too. The second if-statement related to YBR_FULL_422 images should be moved into the first one, because the check of the second if-statement will never be entered because of the return statement in the first if-statement (and the if-else condition too). In my opinion it should be like @kira-96 already wrote: move the check of planar config. into the first if-statement.

**Comment by amoerie** [comment]
Thanks for helping review this @WernMich 

I'm still not very familiar with the various photometric interpretations, would either of you be willing to make a pull request for this? Bonus points for adding a unit test that shows what exactly is being fixed here, because while I do see that the if statements seem wrong, I don't have a bigger picture.

**Comment by WernMich** [comment]
You are welcome: a good Fo-Dicom library is a great value for all of us. I can do this in the late evening today or tomorrow.

**Comment by amoerie** [comment]
Man, open source can be amazing sometimes. Great stuff!

**Comment by WernMich** [comment]
@amoerie I killed it ;) And I am not sure if I ever get comfortable with git. The issue is fixed but when I tried to revert the PixelData.cs file to have only the mandatory changes, I reverted the 2020 commit. And I do not know how to get this commit into my fork / development branch again. Actually I do not have more time to investigate here. But code changes and unit test are available in my fork (dev branch). Unit tests did all run fine at my system. Do not know why the first PR did fail, was not my code causing troubles.
