### ISSUE TITLE
DicomContentItem no option to set encoding

### ISSUE THREAD

**Issue by raise** [fo-dicom/fo-dicom#1069]
### Expected behavior
Set char encoding when adding new DicomContentItem of type text or personname

### Actual behavior
no such option

### Steps to reproduce the behavior
see above

### fo-dicom version and OS/platform
current

**Comment by gofal** [comment]
This is already fixed in the upcomming version 5.0.0.
There I redesigned the encoding behavior. Currently you have to pass the encoding to every DicomItem. So currently it is possible to create a dataset, where patientName is encoded in utf8, while referringPhysician is encoded in japanese and the whole dicomdataset does not even contain a 0008,0005 entry.

in the next version you only pass a string as value, which is internally stored as unicode. And only when fo-dicom is serializing the DicomDataset into some binary stream (store to file, send over network) it reads the content from entry 0008,0005 SpeicificCharacterSet and then encodes all string value in this dataset and its child-datasets with this encoding.

**Comment by mwittig** [comment]
@raise I am reaching out to you about your rfControljs. Can you please contact me at pimatic.info @ gmail.com
