### ISSUE TITLE
DS VR type value ending with \0 fails to serialize

### ISSUE THREAD

**Issue by jackliums** [fo-dicom/fo-dicom#1078]
**Describe the bug**
We have seen DS value type value ending with null terminator (\0) fails to serialize to JSON with ArgumentException "Failed converting DS value to json". It seems like this is a pretty common case generated by certain devices.

C# correctly parses the value "0\0" to 0 if TryParse method is using on long, double and etc but because `FixDecimalString` happens before that, it fails the validation and therefore ends up throwing exception.

**To Reproduce**
1. Open a DICOM file where PatientSize attribute value (VR type DS) is set to "0\0".
2. Serialize the DICOM file to JSON

**Expected behavior**
It should correctly serialize the value to 0.

**Screenshots or test DICOM files**
N/A

**Environment**
Fellow Oak DICOM 4.0.5
OS: Windows 10 x64
Platform: .Net Core 3

**Comment by gofal** [comment]
oh, they added an \0 charachter instead of a space. DICOM strongly prefers even length values.
See here: http://dicom.nema.org/dicom/2013/output/chtml/part05/sect_6.2.html

> Values with VRs constructed of character strings, except in the case of the VR UI, shall be padded with SPACE characters (20H, in the Default Character Repertoire) when necessary to achieve even length. Values with a VR of UI shall be padded with a single trailing NULL (00H) character when necessary to achieve even length.

later there in the definition of `DS` it says:

> Decimal Strings may be padded with leading or trailing spaces

So anyway: even if your data is no valid DICOM, this enhancement to fix the wrong \0 has no risk. The method `FixDecimalString` should trim the val, that is passed as parameter, before continue processing with

        private static string FixDecimalString(string val)
        {
            val = val.Trim().TrimEnd('\0'); // trim spaces and NULL (00H) characters

            if (IsValidJsonNumber(val))
            {
                return val;
            ......

or something similar.

are there some other spots, where this trailing \0 makes problems? Maybe you do the fix, do some testing and create a pull request. Would be great, if you'd do.

**Comment by gofal** [comment]
merged into development
