### ISSUE TITLE
Dicom Server DicomServiceOptions MaxPduSize is never used. 

### ISSUE THREAD

**Issue by BobSter3000** [fo-dicom/fo-dicom#1084]
**Describe the bug**
The default or configured Dicom Server DicomServiceOptions MaxPduSize is never used.  

**To Reproduce**
Using the StoreSCP example modify the DicomServer.Create using statement to include a new DicomServiceOptions with a MaxPDULenght set to some number.

**
            using (var server = DicomServer.Create<CStoreSCP>(port, null, new DicomServiceOptions { MaxPDULength = 400000 }))
            {
                // end process
                Console.WriteLine("Press <return> to end...");
                Console.ReadLine();
            }
**
Run the sample application and send an accocation request to the Sample Server.

**Expected behavior**
The Association Accept should contain the MaxPDULengeth set in the DicomServer.Create constructor.  Instead it appears that the MaxPDULength sent in the Association Accept is the same MaxPDULenght sent in the Assocation Request.

**Screenshots or test DICOM files**
If applicable, add screenshots or test DICOM files to help explain your problem.
![image](https://user-images.githubusercontent.com/9662532/89899276-02726580-dbb0-11ea-9efc-dbbf987f6ad3.png)

**Proposed Fix**
DicomService.cs
        protected Task SendAssociationAcceptAsync(DicomAssociation association)
        {
            Association = association;
            //Add the following line
            Association.MaximumPDULength = Options.MaxPDULength;

**Environment**
Fellow Oak DICOM version: 4.0.6
OS: Windows 10-1909 x64
Platform: .NET Framework 4.6.2

**Comment by gofal** [comment]
You are right.

the proposed fix will not work, because the property `Association` is used for further requests and the value in `Association.MaximumPDULength` is used to create the PDUs sent to the client.

Instead the AAssociateAC would need an additional parameter to pass Options.MaxPDULength. 

Or in class DicomAssociation replace the existing property MaximumPDULength by the two properties MaximumPDULengthToClient and MaximumPDULengthToServer.

**Comment by gofal** [comment]
The problem was, that the class `Association` has only one field `MaximumPDULength`, but in fact it requires two values: the value that your own service supports and the value that the remote service sends you. The property was initialized with the own value and this was sent in AssociationRequest, and then the server returned the AsssociationRequestResponse with the servers value. The property Association.MaximumPDULength is overwritten with this value and then used in further communication. So for the SCU clients this worked fine.
But in case of a server this did not work. Because the server initialized the Association-instance with the value from the client's association request. This value must be stored because it has to be used in further communication. But the server then returned this clients's value in AssociationRequestResponse message instead returning its own value.

So the solution is now, that the `Association`class has a property `Option` of type `DicomServiceOption` and the server as well as the client pass their option to this property. So `Association.MaximumPDULength` now always contains the value sent by the remote service, while `Association.Option.MaximumPDULength` always contains the own value.
