### ISSUE TITLE
Confusion about private UN tag

### ISSUE THREAD

**Issue by kira-96** [fo-dicom/fo-dicom#1146]
**Describe the bug**
If the VR of a private tag is **UN**, it will be cast to **LO**.

**To Reproduce**
See screenshots

**Expected behavior**
When I saved the file, its original value can no longer be read. So I don't want the VR of it to change.

**Screenshots or test DICOM files**

Screenshot opened with *Makhaon DICOM dump*
![Snipaste_2021-01-13_10-34-21](https://user-images.githubusercontent.com/22876709/104399741-3fda8500-558c-11eb-8d34-ff2bb7d4a220.png)
Screenshot opened with fo-dicom
![Snipaste_2021-01-13_10-33-51](https://user-images.githubusercontent.com/22876709/104399781-51bc2800-558c-11eb-91bf-8169a7bb15a6.png)
The test dicom file.
[test.zip](https://github.com/fo-dicom/fo-dicom/files/5806081/test.zip)

**Environment**
Fellow Oak DICOM version: 4.0.7
OS: Windows 10 x64
Platform: .NET Framework 4.6.2

---

I found the relevant code in the source code.
https://github.com/fo-dicom/fo-dicom/blob/development/DICOM/IO/Reader/DicomReader.cs#L441-L447
It existed for a long time, I'm not sure if it has a special meaning.
If it's a bug, I can fix it.
Thanks!

**Comment by gofal** [comment]
The reason for this code is that: http://dicom.nema.org/dicom/2013/output/chtml/part05/sect_7.8.html Paragraph 7.8.1.a
in private groups the first FF items are reserved for Private Creator, which shall be of type LO. The DICOM standard claims that this is true for the elements (gggg, 0010-00FF).
So you could argument that the code should not only check for element <= 00FF, but also for element >= 10. And therefore the provided data 0029,00001 should not be interpreted as LO. But later in 7.8.1.c in Note 3 it says that the requirements of this section do not allow any use of the elements in ranges (gggg, 001-000F). So the data you created in the sample is no valid DICOM. Those tags should not exist at all.

**Comment by gofal** [comment]
So at least I would not consider this as a bug. But of course its open how fo-dicom should deal with this invalid data.

Do you have real-world data that contains this tags? Is it important that the tag should have UN instead of LO?
Because in case of UN you can only get a byte-array. And in case fo-dicom parses it as LO, you can still get the tag as DicomItem and then access the Buffer that contains the original data and so you can access the byte-array, too, independent of how fo-dicom interpreted the tags.

**Comment by kira-96** [comment]
> 
> 
> The reason for this code is that: http://dicom.nema.org/dicom/2013/output/chtml/part05/sect_7.8.html Paragraph 7.8.1.a
> in private groups the first FF items are reserved for Private Creator, which shall be of type LO. The DICOM standard claims that this is true for the elements (gggg, 0010-00FF).
> So you could argument that the code should not only check for element <= 00FF, but also for element >= 10. And therefore the provided data 0029,00001 should not be interpreted as LO. But later in 7.8.1.c in Note 3 it says that the requirements of this section do not allow any use of the elements in ranges (gggg, 001-000F). So the data you created in the sample is no valid DICOM. Those tags should not exist at all. Maybe that's the reason why Makhaon DICOM dump named them "Unknown Element"

I see. Thank you very much!

**Comment by kira-96** [comment]
> 
> 
> So at least I would not consider this as a bug. But of course its open how fo-dicom should deal with this invalid data.
> 
> Do you have real-world data that contains this tags? Is it important that the tag should have UN instead of LO?
> Because in case of UN you can only get a byte-array. And in case fo-dicom parses it as LO, you can still get the tag as DicomItem and then access the Buffer that contains the original data and so you can access the byte-array, too, independent of how fo-dicom interpreted the tags.

Yes, there are some data stored in it. As I said before, when I save the file, these data are saved as strings, and the original values can no longer be read.

**Comment by gofal** [comment]
ok, then I leave it up to you to do a pull request and keep the elements (gggg,0001-000F) as VR UN if you need this. But the elements from 0010-00FF have to be converted to LO, because DICOM explicitly says that.

**Comment by gofal** [comment]
And maybe you can talk to the ones where the data comes from and give them the hint, that their files are wrong. The best solution would be that they fix this.

**Comment by kira-96** [comment]
Sorry, I made a mistake. It has nothing to do with the above code, when I debug, these codes didn't run.
https://github.com/fo-dicom/fo-dicom/blob/development/DICOM/IO/Reader/DicomReader.cs#L702-L716
VR was changed after running these codes. Because the **VRs** of `Private Creator` only contain **LO**.
https://github.com/fo-dicom/fo-dicom/blob/development/DICOM/DicomDictionary.cs#L62-L69
Is it right?

**Comment by kira-96** [comment]
> 
> 
> And maybe you can talk to the ones where the data comes from and give them the hint, that their files are wrong. The best solution would be that they fix this.

OK, thanks. I will try.

**Comment by gofal** [comment]
I see. So this is kind of duplicate, but both are based on the same paragraph in standard that I linked above.
So first when parsing the VR, then this is converted to LO for (gggg,0001-000F) and then later then parsing the value then this conversion is performed again. If you want to change the behaviour then I assume you have to do it on both spots.

The first part is clear, in parseVR you should add the condition that _tat.Element also hast to be greater or equal to 0x0010.

and then in dicomdictionary is slightly more difficult. in case of implicit transfersyntax the dictionary has to be used. this tictionary can either have explicit tags or tags with byte-masks. Now this mask does not support value ranges. Maybe that was the reason why also the values (gggg,0001-000F) are mapped. Because excluding these values from dictionary requires a more complicated mapping. But because these values are not allowed anyway the simple mapping was fine.

**Comment by kira-96** [comment]
I understand. This DCM file is not standard, that's why this problem appears. I should communicate with my colleagues first. 
Thank you very much for your answer.

**Comment by kira-96** [comment]
@gofal I made some small changes, and make sure it follows the rules of [paragraph 7.8](http://dicom.nema.org/medical/dicom/current/output/chtml/part05/sect_7.8.html).
Now `(gggg, 0001-000F)` and `(gggg, 0100-0FFF)` are parsed as `Unknown`.
![Snipaste_2021-01-14_10-28-46](https://user-images.githubusercontent.com/22876709/104536596-4f70d100-5653-11eb-9b8e-15fb4dd2114e.png)
Please check it.
