### ISSUE TITLE
Please add the ability to read DICOM RT Images.

### ISSUE THREAD

**Issue by CenturaPhysics** [fo-dicom/fo-dicom#1153]
**What is, according to you, missing from fo-dicom? Please describe.**
Please add the ability to correctly read pixels from DICOM RT Image types.  See the post titled "RenderImage produces black image in WPF" on the google group to see the problem.  To render these images correctly, you will need to handle weird pixel values that may be between 0 and 1, representing a fractional value.  And, you may need to ignore or somehow handle strange WindowWidth, WindowCenter, and RescaleSlope values, that may also be fractional values between 0 and 1.

**Describe the solution you'd like**
Recognize when one of the unusual DICOM image formats is present, and use an alternate render code to rescale the pixel values accordingly.

**Describe possible alternatives or existing workarounds you've considered**
For a DICOM image with 2-byte pixel values, and with very small window and slope values (WindowWidth = 0.2147, WindowCenter = 0.1077, RescaleSlope = 5.612e-06) I used the following code to rescale the pixel values to be some number between 0 and 255, and then inserted these values into each byte of the 4-byte word for each pixel value in an array representing a Bgr32 image....

        public byte[] Convert16BitByteArrayTo32Bit(byte[] input16BitByteArray )
        {
            int inputSize = input16BitByteArray.Length;
            int maxIndex = input16BitByteArray.Length / 2;
            int idx = 0;
            byte[] tempBytes = new byte[2];
            byte[] newBytes = new byte[inputSize*2];

            do {
                tempBytes[0] = input16BitByteArray[(idx * 2)];
                tempBytes[1] = input16BitByteArray[(idx * 2)+1];
                int tempInt = BitConverter.ToUInt16(tempBytes, 0);
                double frac = (double)tempInt / (double)65536;
                int relValue = (Int16)(255 * frac);

                newBytes[(idx*4)] = (byte)relValue;
                newBytes[(idx*4) + 1] = (byte)relValue;
                newBytes[(idx*4) + 2] = (byte)relValue;
                newBytes[(idx*4) + 3] = 255;
                idx = idx + 1;
            } while (idx < maxIndex);

            return newBytes;
        }

and....

        public BitmapSource MakeWPFImage(byte[] theBgr32Array, int theWidth, int theHeight)
        {
            PixelFormat pf = PixelFormats.Bgr32;
            int rawStride = (theWidth * pf.BitsPerPixel + 7) / 8;
            BitmapSource bitmap = BitmapSource.Create(theWidth, theHeight, 96, 96, pf, null, theBgr32Array, rawStride);
            return bitmap;
        }

These are called by...
            byte[] pixelByteData = di.PixelData.GetFrame(0).Data;
            byte[] pixelByteData32 = Convert16BitByteArrayTo32Bit(pixelByteData);
            theBS = MakeWPFImage(pixelByteData32, di.Width, di.Height);

This got me a nice gray-scale image.  To window and level this image, I would just need to insert code to adjust the relative value placed into each byte of the 4-byte word.

Thanks,
Anton Eagle

**Comment by aerik** [comment]
@CenturaPhysics Are the "weird pixel values" and "strange WindowWidth, WindowCenter, and RescaleSlope values" Dicom conformant?  I don't see anything in http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.8.8.2.html or http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.8.8.2.6.html that jumps out at me telling me to expect anything unusual...

**Comment by gofal** [comment]
@aerik for more details about that read this thread: https://groups.google.com/g/fo-dicom/c/5oxaploh5w0/m/DvOx8R0gBAAJ
these weird values are DICOM conformat. DICOM allows decimal numbers, but usually one expects integer numbers with some decimal point behind. The calculation when rendering often does rounding or casting to int.
But in that case the values are 0.xxxx, so all numbers are small numbers close to zero, which are absolutely fine according to DICOM standard, but the calculation with casting to int breaks everything up.

**Comment by aerik** [comment]
@gofal Ah, I hadn't seen that, thanks, and I missed, or didn't think through, the example given where

`   (WindowWidth = 0.2147, WindowCenter = 0.1077, RescaleSlope = 5.612e-06) 
`

I have only seen a handful of RT images, and they didn't have this issue.

So specifically that would be 

```
        public int this[int value]
        {
            get
            {
                return unchecked((int)((value * RescaleSlope) + RescaleIntercept));
            }
        }
```

So one would naturally use either double or decimal for the pixel value manipulation calculations (LUT values and... )?  I'm sure the effect of those changes would ripple out through the image rendering code... but that's not too bad really...?

**Comment by gofal** [comment]
The calculation of the pixel values is iterated via a chain of ILUT-clases. the interface had the indexer `int this[int value]`. so in this chain every calculation was casted to an int, what caused this issue.
Now internally every calculation is done with double `double this[double value]`.

But there is still an other issue:
DICOM standard defines pretty well how to calcualte window width and window center:
http://dicom.nema.org/medical/Dicom/2018d/output/chtml/part03/sect_C.11.2.html in C.11.2.1.2.1 "Default LINEAR Function". There the window width and window center are assumed to be integer values. Therefore the calculation contains something like "value - (center-0.5) ....". But in this case here where WindowCenter is 0.1077 this calcualtion results in negative values and everything is wrong again.

For that reason, DICOM standard also defined in C.11.2.1.3.2 "LINEAR_EXACT Function" to do an exact calculation of window width and window center.

So after this update, the sample image provided will still be rendered pure black, thats because the VOI LUT Function in this image is "LINEAR" and thats why the calculation defined in section C.11.2.1.2.1 has to be taken.
But if you update the VOI LUT Function (0028,1056) to "LINEAR_EXACT", then this is an correct image and fo-dicom will render it correctly.
