### ISSUE TITLE
A DicomValidationException: components must not have leading zeros

### ISSUE THREAD

**Issue by JiangWeian** [fo-dicom/fo-dicom#1160]
After I upgraded the version of fo-DICOM from 3.0.2 to 4.0.2, a validation error occurred：
Dicom.DicomValidationException: Content "9790.00727170976343643477368009189780409586" does not validate VR UI: components must not have leading zeros

Is there any way to cancel this verification？Because the previous uid can't be modified any more.

**Comment by gofal** [comment]
this UID is not a valid UID. You really should avoid creating such data. 
But in case you really have to, you can set the property `DicomDataset.AutoValidate` to false, then this kind of validation is turned off. This property is decorated with an Obsolte-Attribute so that it generated warnings in your build process and you are reminded not to use this property too much but only when really needed.

**Comment by travnick** [comment]
@gofal The "funny" thing here is that it looks like they have a bug in [DICOM specification](https://dicom.nema.org/medical/dicom/current/output/html/part05.html#sect_9.1) itself (or I misunderstand the thing here):
```
Each component of a UID is a number and shall consist of one or more digits. The first digit of each component shall not be zero unless the component is a single digit.
```
**but** there is also a note:
```
Registration authorities may distribute components with non-significant leading zeroes. The leading zeroes should be ignored when being encoded (i.e.,"00029" would be encoded "29").
```

So according to [RFC 2119](https://datatracker.ietf.org/doc/html/rfc2119) the note allows (`may` distribute, `should` be ignored) to have leading zeros, but at the same time it's forbidden (`shall not` be zero)

**Comment by mrbean-bremen** [comment]
There's a difference between components distributed by registration authorities (the registered number), and the representation as a DICOM UID. The latter shall not have leading zeros.

**Comment by travnick** [comment]
`The leading zeroes should be ignored when being encoded` - `should` is used instead of `shall`.

**Comment by mrbean-bremen** [comment]
My understanding is that the registration authorities define the UIDs which may have insignifant leading zeros, and therefore may be omitted when encoded in some way. 
If they are _encoded as DICOM UIDs_, they _must_ be omitted, according to the standard.

So if understood that way (as I do), there is no contradiction. But I agree that the formulation might be (shall be?) more clear.

**Comment by gofal** [comment]
Let me join in the vote that others already posted.
I also do not see a contradiction, because both termas "shall not be zero" and "leading zeros should be ignored" point into the same direction, one of them stronger than the other. But they do not contradict!

What I read from the standard is, that the DicomTags with ValueRepresentation UI never are allowed to have leading zeros.
But the note tells that some authorities are distibuting IDs with leading zeros. One might say, that these IDs are invalid and therefore would refuse to accept them, but this note tells, that the IDs are valid and that they just should be "recoded". By omitting the leading zeroes the IDs should be transformed to fit into the DICOM-Standard. 
So if doing a pure string-comparison, one might say that the ID "000029" would be a different value then the ID "29", but this note in the standard tells us, that these two values should be considered as equal.

**Comment by gofal** [comment]
Let me think..
I wonder if this small note justifies, that fo-dicom should not throw a validation exception if someone creates a dicomdataset with a UID "1.000029.00001", but instead should create a dicomtag with value "1.29.1"? Saying, if some authority (the user) wants to distribute a UID with leading zeroes, then we should ignore these leading zero when encoding the value.

What do you think about that?

**Comment by mrbean-bremen** [comment]
> Saying, if some authority (the user) wants to distribute a UID with leading zeroes

I don't think the user counts as an authority in this sense. As far as I understand (and I may be wrong here), the mentioned authorities are the authorities registering official DICOM UIDs. They are allowed to register the UIDs with (insignifant) leading zeros, while the DICOM standard does not allow to encode these leading zeros in a UID.

So, I'm quite sure that leading zeros are not allowed in the standard, but fo-dicom could of course skip that validation if this is what is wanted, as the validation is just a formal one and cannot lead to any ambiguities. I have no strong opinion here.
