### ISSUE TITLE
DicomWriter might fail in WriteBuffer for large files (>2GB/int.MaxVelue [bites])

### ISSUE THREAD

**Issue by pelnar** [fo-dicom/fo-dicom#1163]
var offset = 0; declares offset as int which for larger files (e.g. videos for exmaple) will fail. Simple fix is to define offset as explicit long instead of var
System.IO.IOException: 'An attempt was made to move the file pointer before the beginning of the file.

**Comment by pelnar** [comment]
I can fix this

**Comment by osklu002** [comment]
Was going to create a bug but I think it is duplicate of this one:

**### Expected behavior**
We would like to be able to wrap videos larger than ~2.5GB

**### Actual behavior**
Creating a StreamByteBuffer with a size larger than int.MaxValue throws an OutOfRange-exception

This is possibly related to GetByteRange taking an int instead of a long

**### Steps to reproduce the behavior**
Try to create a StreamByteBuffer larger than int.MaxValue

**### fo-dicom version and OS/platform**
fo-dicom 5.0
Windows 64bit

**Comment by gofal** [comment]
This is fixed with #1626 
If the issue still occurs in latest version of fo-dicom, please reopen this issue and provice actual information
