### ISSUE TITLE
Make this repository the base fork of fo-dicom

### ISSUE THREAD

**Issue by anders9ustafsson** [fo-dicom/fo-dicom#12]
To help other users finding the "right" fork of *fo-dicom*, we should find a way to turn this fork into the base fork of *fo-dicom*.

I have been searching around, but I have not been able to find any instructions on how to reliably change the base fork, especially when there are many sub-forks like in our case.

But here's what I think we need to do to make the base fork switch happen:

1. Make the current owner of the base fork, @petnet, member of the *fo-dicom* organization so that he/she can transfer the ownership of the base fork to the organization.
2. Change the name of the organization's *fo-dicom* repository (Github does not seem to support ownership transfer if the new owner already has a repo with the same name), for example into *fo-dicom-transfer*.
3. @petnet transfers the ownership of his/her *fo-dicom* fork to the *fo-dicom* organization.
4. Merge the commits of *fo-dicom-transfer* into the new *fo-dicom* repo, preferably via `git rebase`.
5. Remove the *fo-dicom-transfer* repo.

The side effects I can think of with this approach is that 

a) Github users who have already forked *fo-dicom/fo-dicom* will lose their forks. But these users only need to re-fork, right?
b) We will lose the issue reports made so far to this repo. They will need to be manually transferred to the new repo.

Any thoughts or comments about this? One showstopper is of course to get hold of user @petnet. I am working on that right now.

**Comment by IanYates** [comment]
I've just sent a request to GitHub support referencing this issue.  We may get lucky with a response :four_leaf_clover:

**Comment by anders9ustafsson** [comment]
Thanks, @IanYates . Let's hope for their support :-)

**Comment by IanYates** [comment]
Great success!

------------
Hey Ian,

Thanks for reaching out. There are a few problems with the plan in that issue, most importantly that you can't have multiple repositories from the same network in the same account. 

So this statement is only partially true:

"Change the name of the organization's fo-dicom repository (Github does not seem to support ownership transfer if the new owner already has a repo with the same name), for example into fo-dicom-transfer."

It's not just that you can't have two repositories with the same name, those two repositories must not have the same common ancestor (root). 

When a root of a network is deleted, a new root is chosen randomly. So, "petnet/fo-dicom" was chosen randomly after the old root was deleted. I've just switched the root to your repository, since it seems like where development is happening.

Hope this helps and let us know if you have any other questions.

Cheers,
Ivan
 
> See this issue: https://github.com/fo-dicom/fo-dicom/issues/12
> 
> The original fo-dicom repository was deleted by its owner. With his blessing we've kept the project alive and have created an organisation and a repository from a fork off the original repository.
> 
> There's now some confusion as people aren't sure which is the correct "root" fork. Are you able to help us?
> 
> Thank you!
----------------

**Comment by anders9ustafsson** [comment]
Wow!

Great work, @IanYates , this was much better than I would had hoped for!

Thanks for contacting Github and making this happen!
