### ISSUE TITLE
ISO_IR 192 decoding problem with umlaut

### ISSUE THREAD

**Issue by wolfi177** [fo-dicom/fo-dicom#1210]
### Expected behavior
Patientname with umlaut

### Actual behavior
when reading dicom files encoded with ISO_IR 192 I just get '?' instead of ö,ü,ä or ß. 

### Steps to reproduce the behavior
            var file = FellowOakDicom.DicomFile.Open(@"00000000");
            file.Dataset.TryGetSingleValue<string>(FellowOakDicom.DicomTag.PatientName, out string patientName);

### fo-dicom version and OS/platform
Windows 10 with fo-dicom 4.0.4 and also 5.0.0

**Comment by mrbean-bremen** [comment]
Do you have an anonymized dataset where this happens? Are you sure that the data is encoded in UTF-8, and not in Latin1?

**Comment by wolfi177** [comment]
Thank you for your rapid reply.

I added 2 anonymized Images that contains 'ü' and 'ß' in PatientName. 
When I open it with Medical Connections DicomObjects it works fine so I assume the encoding is OK.

[Images.zip](https://github.com/fo-dicom/fo-dicom/files/7154301/Images.zip)

**Comment by mrbean-bremen** [comment]
I had a look at the images, and the patient names are indeed encoded in Latin1, not in UTF-8. fo-dicom falls back to ASCII in this case, as nothing can be said about the encoding.  I guess that DicomObjects falsl back to Latin1 instead, which, while not correct, will help in such cases (e.g. mostly for Middle European names).

**Comment by mrbean-bremen** [comment]
Actually I'm not sure if the fallback encoding should be used in this case, e.g. when decoding with the given encoding fails (you used one in the first version of the question). 
@gofal - do you think that would make sense? What is the expected behavior here?

**Comment by wolfi177** [comment]
Thank you for your help. Now I know that this is not a valid coding since, according to wikipedia, UTF-8 uses more than 1 byte per special character. I will report this to the modality manufacturer before I work around the problem.

**Comment by gofal** [comment]
The DicomFile.Open method already has an overload with Encoding as second parameter after filename. Then this Encoding is used as fallback encoding in case there is no explicit encoding stored in the DicomDataset.
Of course the best thing is, to raise an issue to the manufacturer, because the incomplete files (the used encoding is missing there) should stop spreading around. But from my experience, this takes some time until it is fixed. Meanwhile you can use this overload of DicomFile.Open.

**Comment by mrbean-bremen** [comment]
> The DicomFile.Open method already has an overload with Encoding as second parameter after filename. Then this Encoding is used as fallback encoding in case there is no explicit encoding stored in the DicomDataset.

Yes, but it is not used if an encoding is stored in the dataset, but the decoding using that encoding fails, like in this case, so that would not work. In the first version of the question (now edited out) this was exactly what the OP had done.
My question was, if it _should_ work in this case (e.g. use the fallback encoding instead of ASCII of decoding fails). This would only work for encodings that can actually detect incorrect encoding, like utf-8.

**Comment by gofal** [comment]
Ah, I see. I misunderstood this issue. I thought that the image would not contain a specific characterset value. But true, if the file contains a *wrong* specific charset then this fallbackencoding parameter does nothing. 
From my perspective it would be consistent if the developer passes a fallbackencoding and then the encoding fails for some reason, that then this fallbackencoding is used instead of ASCII. So if you do have an idea how to technically implement this and you would like to, then a PR is very welcome. Until your last changes fo-dicom never had cared about failing decodings so I guess thats the reason why this has not been implemented so far.

**Comment by mrbean-bremen** [comment]
It should be easy if we have access to the fallback encoding at that point (I will check this later), but only in version 5, of course.

**Comment by wolfi177** [comment]
So this is the reason why the fallbackencoding parameter does not work. I now simply delete the specific character set when saving the image. Now I can use the fallbackencoding parameter to read the image with the correct characters: 

            var file = FellowOakDicom.DicomFile.Open(@"00000000", fallbackEncoding: DicomEncoding.GetEncoding("ISO_IR 100"));
            file.Dataset.TryGetSingleValue<string>(FellowOakDicom.DicomTag.PatientName, out string patientName);

Thank you both

**Comment by mrbean-bremen** [comment]
Ok, I had a quick look, and accessing the fallback encoding would mean we have to pass in the constructor of the respective classes (`DicomStringElement` and derived), meaning an API change. We could add it as an optional argument, but we would still have to store it in the tag class instances. Not sure if this it worth it - what do you think?

**Comment by mrbean-bremen** [comment]
Had another look, and in the end it is probably easier to just use a workaround like removing the encoding and setting a fallback encoding, as done by @wolfi177, than using the fallback encoding that was not designed for that case. We also have to keep in mind that this case would work only for texts with bytes that are illegal for that encoding, which is not the case for single-byte encodings.
