### ISSUE TITLE
Missing Clean Graphics Option in DicomAnonymizerGenerated.cs

### ISSUE THREAD

**Issue by fordanic** [fo-dicom/fo-dicom#1212]
**Describe the bug**
The DefaultProfile for the SecurityProfile is lacking the final option, the Clean Graphics Option. It has been merged with the Clean Structured Data Option. For example check the following rows:
                50[0-9A-F]{2},[0-9A-F]{4};X;;;;;;;;;C
                60[0-9A-F]{2},4000;X;;;;;;;;;C
                60[0-9A-F]{2},3000;X;;;;;;;;;C                
		0008,0050;Z;;;;;;;;;
		0018,4000;X;;;;;;;;C;
		0040,0555;X/Z;;;;;;;;;C
The last row is a part of the Clean Structured Data Option and the first three rows for the Clean Graphics Option, however, they are placed in the same column in the profile. Basically the Clean Graphics Option is not available (a column is missing) and will result in an index out of range exception if used.

The profile should look like this:
                50[0-9A-F]{2},[0-9A-F]{4};X;;;;;;;;;;C
                60[0-9A-F]{2},4000;X;;;;;;;;;;C
                60[0-9A-F]{2},3000;X;;;;;;;;;;C                
		0008,0050;Z;;;;;;;;;;
		0018,4000;X;;;;;;;;C;;
		0040,0555;X/Z;;;;;;;;;C;
Notice the extra ;.

**To Reproduce**
Set a security profile to use the clean graphics option.

**Expected behavior**
The clean graphics option is applued.

**Screenshots or test DICOM files**
If applicable, add screenshots or test DICOM files to help explain your problem.

**Environment**
Fellow Oak DICOM version: 4.0.7 (also on master)

**Comment by gofal** [comment]
Is this still an open issue?
Because the profiles are auto generated from the standard. Table E.1-1. "Application Level Confidentiality Profile Attributes" (https://dicom.nema.org/medical/dicom/current/output/chtml/part15/chapter_E.html#sect_E.1) is downloaded and the rows you mentioned above are generated from that.
So if those profiles were merged, then this is contained in current release.

**Comment by fordanic** [comment]
@gofal, IMO this is still an issue. That is, the options Clean Graphics Option and Clean Structured Data Option have been merged when they should be two different options.

**Comment by mrbean-bremen** [comment]
I just had a look, and the problem is that a new profile (Retain Institution Identity Option) had been introduced in DICOM 2017d, and this got put right into the middle of the table in the standard. This option was not present as the code was generated (as can be seen in the comment), but had been added to the enums, so this leads to the discrepancy.

We either have to re-generate the code, if the generator is still present (I haven't seen it, but maybe I missed it), or we could just manually add that column in the defaults.

**Comment by mrbean-bremen** [comment]
@gofal - do you know if the generator is still out there? I would prefer that we use it if it is available to minimize the possibility of typos. Otherwise either @fordanic or one of us could fix this manually using the standard. I don't think it makes sense to write tests for this, so this should be an easy fix with a review that is a bit tedious.

**Comment by gofal** [comment]
Sure, the generators are checked in in Sourcecode. Several Times per year I execute it and update all uids and definitions etc to latest DICOM Standard. This is then also added to the changelog.

**Comment by gofal** [comment]
https://github.com/fo-dicom/fo-dicom/wiki/DICOM-dictionary-generation

**Comment by mrbean-bremen** [comment]
Ok, tried it. It seems to generate the wrong output. I have an idea what the problem may be, but will have a closer look ~tomorrow~ another day...

**Comment by gofal** [comment]
That's Tricky, the profiles are flags enums and therefore the anonymizer accrpts int instead of enum as Parameter. Some application may have stored the configured Profile to be used as int value. So a New Profile should not replace an existing one (even if it is retired) but should be added as new value.

**Comment by mrbean-bremen** [comment]
Hm, but there is an equal possibility that it has been stored wrong due to the bug, so either way, there will be some potential impact.
If we just fix the parsing, the enums used in fo-dicom will be correct now, but something that has been stored before the change may be incorrect now. If we also add some code that manually moves the new colums to the end (end also change the enum values themselves), this may cause problems with values saved after the enum change, and additionally is more error-prone. I don't really know how this is used, so this may still be the right option...

**Comment by gofal** [comment]
Sure, agree. The next version will be a raise in the minor version anyway, so some breaking changes can be included ;-)

**Comment by mrbean-bremen** [comment]
So, to summarize: the bug was a very simple one, and it led to just the last column be omitted. My confusion came from the few hardcoded values at the beginning of the list (the ones for tag ranges), where indeed a column in the middle was missing, while for all the other tags (the ones that were actually generated) just the last column was missing.
