### ISSUE TITLE
Download .dcm file from PACS (DCM4CHEE)  server and save the .dcm file into local drive.

### ISSUE THREAD

**Issue by IqbalAST** [fo-dicom/fo-dicom#1260]
After a lot searching, I was unable to find the way how to save .dcm file.
I've a PACS (DCM4CHEE) server and I can connect to it and query patient's information but I can't get (or I don't know how to get any) the way to download .dcm file.

My only purpose is to download .dcm file from PACS server to backup in a local drive.
Thanks.

**Comment by amoerie** [comment]
Hi @IqbalAST  thanks for making the separate issue.

I think your solution would look a bit like this:

1. Make a DicomClient 
2. Send C-FIND requests to figure out what studies are present on the remote PACS server
3. Send C-GET requests to retrieve the DICOM files that you want
4. Store the received DicomFile

See our README file on how to send a C-FIND request
See this unit test on how to work with C-GET requests: https://github.com/fo-dicom/fo-dicom/blob/development/Tests/FO-DICOM.Tests/Network/Client/DicomClientTest.cs#L1178

Alternatively, you can send C-MOVE requests to the PACS server, and have the PACS server initiate a connection to your C-STORE server to send the files to you. This is generally more robust, because then the associations handshake can setup the the correct transfer syntaxes.

**Comment by wx0322** [comment]
Just What I was looking for.
