### ISSUE TITLE
Optimize Logging memory consumption

### ISSUE THREAD

**Issue by gofal** [fo-dicom/fo-dicom#1314]
**What is, according to you, missing from fo-dicom? Please describe.**
While fo-dicom optimizes the allocation of 6bytes headers in dimse messages, logdata is always created even if logging is turned off. So a lot of useless strings are allocated

**Describe the solution you'd like**
The default Logger implementations in fo-dicom do not allow setting LogLevels what to log and what not to log.
And the log-messages shall not be passed into the log methods, but instead a string-factory method shall be passed.

**Describe possible alternatives or existing workarounds you've considered**

with a simple Lazy class like the following:

    public class Lazy
    {

        private Func<string> _stringGenerator;

        public Lazy(Func<string> generator)
        {
            _stringGenerator = generator;
        }

        public override string ToString() => _stringGenerator();

        public static Lazy Build(Func<string> generator) => new Lazy(generator);

    }

it is possible, to wrap a string-creating function into a factory.
now if i replaced in DicomService every method like

                    Logger.Info("{logId} -> {pdu}", LogID, pdu);

by
 
                    Logger.Info("{logId} -> {pdu}", LogID, Lazy.Build(() => pdu.ToString()));

or

                                Logger.Info(
                                    "{calledAE} <- Association accept:\n{assocation}",
                                    LogID,
                                    Association.ToString());

by

                                Logger.Info(
                                    "{calledAE} <- Association accept:\n{assocation}",
                                    LogID,
                                    Lazy.Build(() => Association.ToString()));

then there was already some memory improvement in benchmark:

|            Method |     Mean |     Error |    StdDev |    Gen 0 |    Gen 1 |    Gen 2 |  Allocated |
|------------------ |---------:|----------:|----------:|---------:|---------:|---------:|-----------:|
|  SendEchoToServer | 1.666 ms | 0.0471 ms | 0.0613 ms |  15.6250 |        - |        - |  104.71 KB |
| SendStoreToServer | 5.700 ms | 0.1351 ms | 0.1709 ms | 554.6875 | 523.4375 | 515.6250 | 4131.51 KB |

became to

|            Method |     Mean |     Error |    StdDev |    Gen 0 |    Gen 1 |    Gen 2 |  Allocated |
|------------------ |---------:|----------:|----------:|---------:|---------:|---------:|-----------:|
|  SendEchoToServer | 1.729 ms | 0.0711 ms | 0.0949 ms |  15.6250 |        - |        - |   88.43 KB |
| SendStoreToServer | 5.722 ms | 0.1138 ms | 0.1264 ms | 531.2500 | 507.8125 | 492.1875 | 4086.06 KB |

So no big improvement, but at least a little bit that can be done very easily.

**Comment by amoerie** [comment]
Just a note here @gofal: if we want to take this further, there is also https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/loggermessage?view=aspnetcore-6.0

This is an intelligent optimization that parses the log message format once and also tries to do as little as possible if the log level is not enabled. 

We could try to do something similar, or even consider dropping our own ILogger abstraction and depending on Microsoft.Extensions.Logging instead. This would also give us free access to the upcoming source generator based implementation in the next release, which would increase performance even more.
Furthermore, this would remove the need to maintain our own logging adapters for NLog, Serilog, etc.

The only concern I have is how well Microsoft.Extensions.Logging works in a .NET Framework environment..

As for your current solution, not calculating the string is already nice low hanging fruit! I do wonder if we could do a different implementation that does not use Lazy and Func<string>, because those closures allocate hidden classes as well to capture the variables used inside the Func, so in the case where logging is enabled we now allocate even more...

**Comment by aerik** [comment]
Maybe I'm being dense, but isn't this just about being intelligent about when we call ToString() on the objects passed as the last argument to the logger?

`void Log(LogLevel level, string msg, params object[] args);`

If I'm understanding it right, couldn't a change be made in the implementations of Logger, and just leave all the passed objects as objects in the rest of the code?

**Comment by amoerie** [comment]
You are right that this will already make a difference, but the truth is more subtle than that. When do you actually call ToString? On the same thread, or on a background thread? And when do you execute string.Format? If the log level is enabled, or always? If your logging target is a TCP server that needs JSON, maybe you don't need to call ToString at all?

These kind of dilemmas is what the Microsoft ILogger and its underlying implementations solve for us. 

Could we improve our memory and performance numbers with just some tweaks in our own ILogger abstraction and its surrounding infrastructure? Definitely yes. But I think we can make a bigger dent by going all the way, and in the same effort plug better into existing .NET core applications.
