### ISSUE TITLE
Package was restored using .NETFramwork=v4.6.1

### ISSUE THREAD

**Issue by hashitha** [fo-dicom/fo-dicom#1318]
I am getting the following when I added fo-dicom.Imaging.Desktop 5.0.2 to a .NET 6 WPF app. The app seems to work fine.

![image](https://user-images.githubusercontent.com/10569142/151686345-95a79fca-fed7-4a94-9b4d-e0e6f3e3ebfc.png)

**Comment by tpst** [comment]
I'm also getting this. I would like to know if this is something to be concerned about.

**Comment by gofal** [comment]
the package fo-dicom.imaging.desktop requires System.Drawing. Is there any issue with System.drawing and .net 6? Will GDI be deprecated in .net 6 and replaced by some other packages?
I have not started to use .net6 so far, because it would require to switch my whole IDE-ecosystem, so I do not have personal experience. But System.Drawing is the only package referenced by fo-dicom.imaging.desktop and not by fo-dicom.core.

**Comment by hashitha** [comment]
I am not sure about what is happening with GDI but VS2022 runs so much faster so it is worth the upgrade if you have a lot of ram.

**Comment by mrbean-bremen** [comment]
Maybe the warning has to do with the fact that `System.Drawing` is only supported under Windows since .NET 6. If fo-dicom only supports Windows, this should not be an issue.

**Comment by gofal** [comment]
Oh, i thought System.Drawing was always only supported under Windows. That's why it is only included in the nugetpackage fo-dicom.Imaging.Desktop, while on all other platform it is recommended to use fo-dicom.Imaging.ImageSharp, or no package at all and use the byte-arrays of pixels directly (RawImage).

**Comment by gofal** [comment]
If you are using fo-dicom.imaging.desktop, then you are bound to Windows anyway, and therefore somehow referencing .netframework will not limit your application further.

**Comment by mrbean-bremen** [comment]
I was actually wrong, it's [System.Drawing.Common](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only) what I was referring to, not `System.Drawing`, though that namespace is also effected.

**Comment by MrBean2016** [comment]
I had the same problem so I pulled down the repo, created a .Net-project file (Net 6.0), added the source-files, added System.Drawing.Common 6.0 as a Nuget-packet and it seems to work without any dependencies to .Net Framework.
