### ISSUE TITLE
Ability to ignore "Other" VR types when converting to JSON

### ISSUE THREAD

**Issue by mocsharp** [fo-dicom/fo-dicom#1321]
**What is, according to you, missing from fo-dicom? Please describe.**
The `DicomJsonConverter` cannot be configured to not write any other VR types (e.g. OB, OW, UN...).

**Describe the solution you'd like**
Give an option in the constructor to write `writeOtherValueTypes = true` if possible.
Or make `WriteJsonDicomItem` protected so it can be called from a derived class.

**Describe possible alternatives or existing workarounds you've considered**
Make our own converter for now as a workaround based on fo-dicom's implementation.

**Comment by gofal** [comment]
Why would that be necessary? I mean, is that something that is required or used often?
So if this is something that only you need for your application because of some special reasons, then I would not implement a new converter. But instead I would just remove those DicomItems from the DicomDataset before passing it to the converter. So something like

            var VRsToRemove = new List<DicomVR> { DicomVR.OW, DicomVR.OB, DicomVR.UN };
            Dataset.Remove(i => VRsToRemove.Contains(i.ValueRepresentation));
            // now serialize Dataset to Json

**Comment by mocsharp** [comment]
@gofal Thanks for the suggestion.

It is for performance reasons as we need the ability to save both original DICOM plus JSON headers.  In that case, we would have to clone the `Dataset` and then remove the unwanted VRs from the clone.

I am more than happy to open a PR to make that change but would like to get some feedback on whether to add an option to the constructor or make `WriteJsonDicomItem` protected.

**Comment by mocsharp** [comment]
@gofal if you are okay with this change https://github.com/mocsharp/fo-dicom/commit/34fe9869815b3abf6bbb5d59e87e961ce37b4e44, please let me know and I can create a PR or make additional changes. Thanks!

**Comment by gofal** [comment]
first of all: cloning a dataset is very cheap! The Dicomitems are designed to be immutable. So a DicomDataset is a list of DicomItems. When you clone a Dataset, then you get a new List, but each element referencing the same instances of Dicomitems. So you can Clone and then remove items from the cloned Dataset without doubling the whole data in memory.

**Comment by gofal** [comment]
In my opinion having such an parameter is not suitable for fo-dicom. because the usecase where you just pass VRs and then (stupidly) remove all items of those VRs is very specific to your application. adding an option to remove private Tags, or adding an anonymization level to remove tags containing sensible data or so would acutally make more sense. But not just passing a list of VRs. But even in the use cases I mentioned above this option is not required. In those cases you would clone the dataset, apply an Anonymizer and then serialize the anonymized dataset.

But making private methods of the serializer protected, so that you can more easily your own implementation, is of course a good idea. But be aware: since those methods are not a public api, the method names or parameters of those methods may change more easily on new releases than the public api does.

**Comment by mocsharp** [comment]
Thank you @gofal! 
I am a bit hesitant even if cloning is cheap as we may be dealing with thousands of studies per hour.  In our use case, we only wanted to store header info minus any binary blobs.  The header info is for a downstream [subsystem](https://github.com/Project-MONAI/monai-deploy-workflow-manager) to consume, process, filter, and launch AI workflows.

Let me run some benchmarks and report back the differences.

**Comment by mrbean-bremen** [comment]
While I agree that it doesn't make sense to add a special parameter to do this (as it can indeed be done in an easy and non-expansive way without it), I can see that there are use cases where you want to serialize only the header data without the mass data (like image data), which is what Ox data mostly is. The mass data may be transferred in another, more efficient way, or not all all, depending on the use case.

Maybe making this private method protected is indeed a good compromise, with the usual (mentioned) caveat, that this API may not be stable.

_EDIT_: As @mocsharp responded at the same time - this is the kind of use cases I am referring to.

**Comment by mocsharp** [comment]
Here are some numbers I have collected.
Using a CT study with 147 instances:

1. Ignoring `O*` and `UN` VRs by skipping, using modified code: **22ms** to convert and **2,365,490** bytes for storage.
1. Ignoring `O*` and `UN` VRs by cloning and removing unwanted VRs: **26ms** to convert and **2,365,490** bytes for storage.
1. Complete: **260ms** to convert and **1,030,035,140** bytes for storage.

Indeed, it looks like clone&remove doesn't add too much time.
I think we can stick with what @gofal has suggested but if you like, I can still open a PR to make `WriteJsonDicomItem` protected.

**Comment by mrbean-bremen** [comment]
This looks good enough to me - I don't think we need the change in this case.
