### ISSUE TITLE
Random "Association rejected" when switched to v3 and async code

### ISSUE THREAD

**Issue by jongo** [fo-dicom/fo-dicom#1387]
**Describe the bug**

There is one special PACS...

When we used old fodicom v2 all DIMSE communication worked well. When we have switched our client to fodicom v3 & v4 and used async API, PACS started to reject associations randomly with message:

`Association rejected [result: Transient; source: ServiceUser; reason: NoReasonGiven]`

This is the sample of code that gives error

```
var cfind = CreateImagesQuery(StudyUID, SeriesUID);
cfind.OnResponseReceived = (DicomCFindRequest rq, DicomCFindResponse rp) =>
{
    //do stuff
};

var client2 = new Dicom.Network.Client.DicomClient(Ip, Port, false, Aet1, Aet2);
await client2.AddRequestAsync(cfind);
await client2.SendAsync();    
```  

We will try to get PACS logs but we can't have them at this time. PACS conformance statement says:

> A Q/R SCP AE will only allow a single outstanding operation on an association. Therefore, a Q/R SCP
> AE will not perform asynchronous operations window negotiation.

Is it possible that we are missing some option in DICOM client when sync PACS is on otther side? (This is desperate shot, but we have depleted all possible ideas.)

Our last resort is to have special branch/version for that specific PACS with fodicom 2.

Thanks in advance.

**Environment**
Fellow Oak DICOM 4.0.8
OS: Windows Server 2012)
Platform: NET Framework 4.6.2

**Comment by gofal** [comment]
actually you are only adding one Request to the DicomClient, therefore the SendAsync method will only send one reuqest, no multiple outstanding operations. That's why I cannot see the problem. Maybe because of the async nature now you have serval processes with several client instances that are making the requests in parallel.

**Comment by jongo** [comment]
> actually you are only adding one Request to the DicomClient, therefore the SendAsync method will only send one reuqest, no multiple outstanding operations. That's why I cannot see the problem. 

Yes, agree.

> Maybe because of the async nature now you have serval processes with several client instances that are making the requests in parallel.

This is more possible. We have Web API Controller that invokes the DIMSE communicaton with the PACS, awaits for PACS and returns response to web client. Multiple web clients are calling that Web API controller in the same time.

**Comment by gofal** [comment]
Well, without knowing any details of your application, I have the following impression:
I do not know the implementation in fo-dicom 2 (i started with fo-dicom version 3), but we did a lot of refactorings and improvements in the last version. Also some improvements to gratefully handle parallel / async execution. I guess in version 2 there has been some synchronization mechanism because the DicomClient was not threadsafe. Thats why the requests may have been synchronized within fo-dicom. But now fo-dicom is fully threadsafe and can run many requests in parallel.
So if the PACS that you are working with does not support several requests at the same time, then you have to add some synchronization mechanism in your application. Or do buffering to avoid having many requests and response the web api methods from your cache.

**Comment by jongo** [comment]
Thanks @gofal. When we get PACS logs and if we fix that issue, I'll let now here the solution that worked for us.

**Comment by streunerlein** [comment]
@jongo Pinging on this, did you find a solution?

**Comment by gofal** [comment]
closing the issue due to inactivity.
