### ISSUE TITLE
Print SCP using ImageSharp

### ISSUE THREAD

**Issue by khaledyasser95** [fo-dicom/fo-dicom#1397]
Question

Can I use image sharp to print instead using the code in the sample repositories?
![image](https://user-images.githubusercontent.com/26413162/173206766-6d13a982-2031-4e4f-b5cd-0a297abd83b2.png)

If yes, can you tell me the logic

Thanks!

**Comment by khaledyasser95** [comment]
I did that but is this a correct way?
![image](https://user-images.githubusercontent.com/26413162/173207673-47724a9d-58b7-45e1-ac8b-65c92f79ffb3.png)

**Comment by gofal** [comment]
yes sure, you could to that.
But the sample code does printing on a printer using .net and therefore requires GDI. This then makes System.Drawing available anyway and thats why System.Drawing.Bitmap is used.

if you do not want to print on a printer and only keep data data in memory or write as an image on file, then just call RenderImage().AsSharpImage() instead of RenderImage().AsBitmap(). And do not forget to register ImageSharp into your DicomSetupBuilder.
