### ISSUE TITLE
IDisposable and rendering images

### ISSUE THREAD

**Issue by IanYates** [fo-dicom/fo-dicom#144]
I'm trying to follow the flow of "ownership" for various objects created and returned by the `DicomImage.RenderImage` call.

An `ImageGraphic` instance is created and disposed during the call.  That `ImageGraphic` has its `RenderImage` method called.  If we assume WinForms (I'm using it from ASP.NET) then we end up returning a `WinFormsImage` instance.

The `WinFormsImage` class itself creates an internal `Bitmap` during its constructor.  That `Bitmap` is created using the provided `IPixelData`.

Note: according to https://msdn.microsoft.com/en-us/library/zy1a2d14(v=vs.110).aspx, we can't dispose the pixel data until AFTER the `Bitmap` itself has been disposed. 

However, the `DicomImage.RenderImage` call disposes of its `ImageGraphic` instance, which will dispose its pixels.  It then returns the `WinFormsImage`.

I think we need to clarify which bits of infrastructure should own what.  But I could be missing something as there are many moving parts.  @anders9ustafsson - you've got the most experience with all of this now.  Have I misunderstood something?  I haven't looked at other implementations like the WPF one but I assume they follow a similar pattern.

**Comment by anders9ustafsson** [comment]
@IanYates Do you have examples of when the disposal order you are describing causes problems? I have not experienced any failure to render images due to early disposal, but I may not have tried every possible scenario :-)

In principle I agree that ownership needs to be clarified. I am a little reluctant to the modifications in the PR you have posted, though. I will add a few line-by-line comments for the time being, and I will try to digest more thoroughly what you are proposing in the PR to come up with an overall review a little later on.
