### ISSUE TITLE
DicomJsonConverter has different behavior than DicomReader/Writer

### ISSUE THREAD

**Issue by jovinson-ms** [fo-dicom/fo-dicom#1451]
**Describe the bug**
`DicomReader/Writer` (for converting between raw bytes and in-memory representation) is quite lenient in the validations applied, both on reading and writing. `DicomJsonConverter` applies a number of validations in both the reading and writing process, leading to a behavior gap between the two conversion paths.

For example, a Dicom file could contain an element with Decimal String VR, but invalid content such as `asdf`.

With `DicomReader/Writer`:
- When reading, if `autovalidate` is set to false, the value `asdf` will be used to create a new `DicomDecimalString` using the `IByteBuffer` [constructor](https://github.com/fo-dicom/fo-dicom/blob/b43c485d942d60eb633734764561a83b82f511da/FO-DICOM.Core/DicomElement.cs#L813)
- While in-memory, the value can be retrieved as a `decimal` (which will fail) or as a `string` (which will succeed)
- When writing using `DicomWriter` the value will be written with the same bytes that were read

With `DicomJsonConverter`:
- When reading from JSON, the value `asdf` will not parse as a `decimal` and [fail validation](https://github.com/fo-dicom/fo-dicom/blob/b43c485d942d60eb633734764561a83b82f511da/FO-DICOM.Core/Serialization/JsonDicomConverter.cs#L874). ❌
- When writing to JSON, the value `asdf` (which will be present if the `DicomDataset` was created using `DicomReader`) can be written as a string when the `NumberSerializationMode` is set to `PreferablyAsNumber` or `AsString`.

Ideally, I'd like to see the `DicomJsonConverter` apply the same minimal level of validation as `DicomReader/Writer` during the serialization / deserialization process.

**To Reproduce**
- Read a Dicom file with an element with Decimal String VR and value `asdf` into a `DicomDataset` using `DicomReader`
- Write the `DicomDataset` to JSON using `DicomJsonConverter`
- Read the JSON back into a `DicomDataset` using `DicomJsonConverter`
- An exception is thrown

**Expected behavior**
The content of the dataset is written successfully in DICOM JSON format.

**Environment**
Fellow Oak DICOM version: 5.0.4
OS: Windows 11 x64
Platform: .NET 6

**Comment by amoerie** [comment]
While I agree with the sentiment that validation behavior should be similar between DicomWriter/DicomReader and the JSON converter, I am not certain that making the JSON converter more lax is the direction we want to go in. But it is not my call to make.

My personal opinion is that good software should be liberal in the data it accepts and strict in the data it outputs. So in this particular scenario, my opinion aligns with your proposed changes, deserialization will succeed even when faced with "invalid" data.

Ultimately, @gofal was and is the driving force behind the whole validation behavior in Fellow Oak DICOM, so I think his input is important here.

**Comment by gofal** [comment]
The missing validation in DICOM software leaded to so many messy data in real world. Most of the time I spend in support with DICOM is about handling some invalid data that other software generates. When working in this project I noticed how many devs there are, wo are using this library for creating DICOM data without going deeper into the standard. I noticed that by so many questions "hi, i'm new to dicom but i just need to create a dicom file for the screenshot". So i really feel responsible: when providing software then it has to include validation.

After validation was introduced in fo-dicom the issues about "now the code failes when working with this or that modality" increased. Most of the cases where when working with some old software via classical DIMSE communication (using DicomWriter/DicomReader). There is no chance to make that old software work that is not under development any more, so the strategy to be liberal in the data it accepts applied. 
But with newer formats like Json in DicomWeb, there is a chance to be more strict. Because the software that sends and receives such data is more up to date and propably still in development. That's why I relly would hope to keep more validation there.
If some data with "asdf" as numeric value is received, then the first impulse should be to reject and tell the sender to fix this issue, not as we used to in old DIMSE to make the own application make working with that broken data and continue distributing it to other destinations.

But sure, in case there is no chance to make the source fix their problem, there has to be an option to turn validation off.

I hope, this explains, why there happend to be some different behavior for validation in DICOM DIMSE and DICOMWeb.

**Comment by jovinson-ms** [comment]
Thanks for the explanation, and it completely makes sense to me. The challenge is that building a general DicomWeb implementation as we are doing involves both sets of data - some customers may store only older Dicom files, while others may be creating them in the present. 

The main takeaway I had from your comment above is that we should allow validation to be turned off (or perhaps more accurately turned down) optionally. The challenge so far has been finding how lenient to be. In general, the approach of the changes we've suggested to serialization are to delay the VR-specific validation as much as possible, while still ensuring that the content can be parsed as a DicomDataset.

**Comment by esmadau** [comment]
Hello, I wanted to ask along these same lines what the appetite is to allow for deserialization to truly skip validation. We validate on serialization and want to reload that data into DicomDataset without it going through any validation. Today, we have "validation" turned off, but the parser will still look at VRs and parse based on some assumptions and then equally the DicomDataset expects a string to be able to be cast to, for example, and int. It'd be great to have the "structure" of a DicomDataset but have everything as string types to allow the data through.  @gofal

**Comment by gofal** [comment]
I have to ask you one question: Why do you want to generate a DicomDataset with invalid content?

When you deserialize some Json from Text to Dicom, then you are actually creating a Dicom file, aren't you? So if you have some source and that source just writes "asdf" into a field where a number is required, then this is mess. Agree?
If you then *create* a DicomDataset and just pass this messy value into the DicomTag, then you are aware, that no other application ever will be able to handle this value in a reasonable way. But more, you are creating a Dicomfile, that may cause issues or problems in other applications after you started to share it.

If you receive such a messy json data, then the best solution would be, to reject that data, in order to trigger the source to fix the problem.

If that is no option, then the next step would be, just to throw away that messy value! Do not pass it into the DicomDataset that you are creating.

If you want to throw all the responsibility away from you and turn off validation completely and you do not care about DICOM standard, then it is up to you. But I really want do do a veto, to change fo-dicom in a way, to silently accept messy data and generate invalid DICOM files and therefore support breaking the standard.

**Comment by esmadau** [comment]
Hi @gofal , thank you for the reply.
I understand that you'd like to see fo-dicom attempt to better uphold the DICOM standard. 
We have also thought to just drop the invalid metadata. Is this something you'd be ok to see added as a PR to fo-dicom with a flag? So for example, during deserialization, if it can't deserialize we drop it when a flag is set?

For some added context on use case: 
An example of the situation we have is that customer X is giving us DICOM files generated by a device with, for example, a faulty Pixel Spacing value and yet another viewing device totally expects that faulty value and will even display it and has features built on it. So customer X gives us these files to store on their behalf only to at some point later ask for them again to view on another device. Also important to note is that customer X themselves did not choose to use the original faulty device and are trying to archive data generated years ago by another customer of theirs and there's no way of fixing it so the risk is losing all this data from an outage if not moved to a solution like ours that has resiliency built in. We also don't like that these documents were generated with fault data, but would prefer to be able to provide them in an example of a provider requesting it a decade after initial diagnosis in case of recurrence where most of the data is still valid and insightful.
We can drop the data for now, but in instances where the date format isn't what is expected but is maybe totally readable and valuable to the end user, it'd be best to preserve it.

**Comment by gofal** [comment]
I also had implemented many data migration projects. So I really feel familiar with the context you describe.
But one part of the migration process was, to check such data. We often found faulty data had to build a sanitizer before importing the data into the archive. In your case, if you are expecting that the device requires faulty data, then you would have to build a "desanitizer" for exporting such data.
When we took over responsibility over the data and to process / distribute / convert /analyze the data, then we made the customer clear that we can do that only with valid data. And if there is some mess with to chance to fix it, then this information is worthless anyway and has to be erased. 
We had some projects where our sales agent promised to take all data as it is. Those where the projects, that made us the most troubles and costed us the most time (and therefore money).

I am glad, that you understand, that it's not a good idea to introduce such a standard-breaking change just because of your very special use case.
But fo-dicom is an open source project! You are very welcome, to fork the library, do the changes whatever you want to make it fit your very special needs :-)

**Comment by esmadau** [comment]
@gofal  - would it make sense to allow for dropping the data as a way to sanitize during de/serialization to/from JSON within fo-dicom when a feature flag is enabled? Can I open the PR?

**Comment by smithago** [comment]
@gofal totally agree on the sentiment. To allow only valid data. But we are seeing need for relaxed rules in real world. Specifically when the data is old and they don't want to mutate it.

I like how fo-dicom provides nobes. Choose what you want with validation settings. fo-dicom already provides the nob skip-validation. I think she is asking to go all the way through with it. So there is still full validation and full no-validation and consumer gets to choose. I think this is more of a bug fix for skip-validation setting to truely skip-validation.

**Comment by gofal** [comment]
Yes, I see.
"and they don't want to mutate it.", I have never seen a radiologist or medical physician or patient, who insisted to keep messy data as it is. They always want to have data that just stores their medical data in a standard way to be able to process it then and therefore help them doing diagnosis and help their health. We never should forget: we are not working with some business data or statistics data or something, where a little bit of mess is just fine. We are working with medical data. It's about people. We really have to care about the data. 
I only heard this request from other it-companies or developers because they did not want to make updates or they are not willing to fix their bugs. But obviously you seem to have other contacts as me.

Sorry for that. but currently I am more than angry. I have to fight with a huge swedish DICOM company. Because they just have an archive with double StudyinstanceUIDs in it. There are troubles because there are wrong images contained in a patients case. Because some images of an other patient do have a wrong studyinstanceuid. But then this company wanted to explain me, that the combination of StudyInstanceUID+PatientId is unique and I should change my software to make this pair of data the unique key instead of only the studyinstanceuid. This happened on their side because they did not do enough validation and therefore this inconsistency happend. And now they say: "well it happend, we don't care any more. now this data is out in wold. Deal with it! try to fix it on your side".

Having consistent and correct data is so so so so so important. And we should fix the bugs and not help to propagate it!

**Comment by gofal** [comment]
So, if you really want to turn validation off. And if you really think, it is a good idea to have a tag with a integer type to be filled with "asdf" and you are conficed that instead of removing this meaningless data you want to persist and distrubute that and therefore causing other vendors some troubles, then you can do that.
if there is a PR with some validation "fix" in it, then I will approve that.
But I had to revert the last PR, because it changed the very core handling of DicomDatasets. It was not about turning off some validation, but It changed the internal datastorage. It allowed all number typed tags to have strings. But this PR did then not deal with the consequences. the api relies on, if there is a DicomDataset and you call "GetValue<int>" of a tag with value representation of a integer type, then you will get a int.

**Comment by gofal** [comment]
Now closing this issue again. If there will be some PR then feel free to reopen this issue.
