### ISSUE TITLE
Dicom printer dicom printer is merging images by merging images from another patient in the same folder

### ISSUE THREAD

**Issue by leonetosoft** [fo-dicom/fo-dicom#1458]
**Describe the bug**
dicom printer is merging images by merging images from another patient in the same folder.

**To Reproduce**
Steps to reproduce the behavior (code snippet or clear description)

**Expected behavior**
Each patient in a folder

**Screenshots or test DICOM files**
If applicable, add screenshots or test DICOM files to help explain your problem.

**Environment**
Fellow Oak DICOM version: 5.0.0
OS: Windows
Platform: NET Framework 4.6.2

**Comment by gofal** [comment]
please provide more information. Is your application the printer SCU or the printer SCP? What vendor is the other part? hat have you tried so far? could you please secribe the used workflow in more detail. Because a print scp cannot merge patients. the client creates a job and then add pages to the job and then adds images to the page. So the print scu fully controlls the output

**Comment by gofal** [comment]
the description does not contain enough information to be able to support solving it. I will therefore close it for now, but please feel free to reopen it when you can provide more information!
