### ISSUE TITLE
AddOrUpdate PrivateDicomTag with string value throw validation error

### ISSUE THREAD

**Issue by HwangTaehyun** [fo-dicom/fo-dicom#1462]
**Describe the bug**

```
var guid = Guid.NewGuid();
ushort groupNumber = Convert.ToUInt16("00F1", 16);
ushort elementNumber = Convert.ToUInt16("1100", 16);

// vr regarded as "LO" when adding guid.ToString to dicomTag at dataset
1) var dicomTag =  new DicomTag(groupNumber, elementNumber);

// throws validation error
dicomFile.Dataset.AddOrUpdate<string>(dicomTag, guid.ToString());
```

In the case, it throws validation error ```"Unhandled exception. FellowOakDicom.DicomValidationException: Content "f312e027-460d-4c8c-8d8a-807951b4241b" does not validate VR AE: value exceeds maximum length of 16 characters"```

Currently, I resolve this problem by using the following code temporarily

```
dicomFile.Dataset.AddOrUpdate<string>(DicomVR.LO, dicomTag, guid.ToString());
```

**To Reproduce**
Follow the above example.

**Expected behavior**

```
1) var dicomTag =  new DicomTag(groupNumber, elementNumber); // vr regarded as "LO" in dataset
dicomFile.Dataset.AddOrUpdate<string>(dicomTag, guid.ToString());
```

I think the Private Dicom tag's string value is inferred to be "AE" because DicomDictionary's entry has same value type for VR: AE and LO
```
private DicomDataset DoAdd<T>(DicomTag tag, IList<T> values, bool allowUpdate)
{
    var entry = DicomDictionary.Default[tag.IsPrivate ? GetPrivateTag(tag) : tag];
    if (entry == null)
        throw new DicomDataException($"Tag {tag} not found in DICOM dictionary. Only dictionary tags may be added implicitly to the dataset.");

    DicomVR vr = null;
    // maybe problem
    if (values != null) vr = entry.ValueRepresentations.FirstOrDefault(x => x.ValueType == typeof(T));
    if (vr == null) vr = entry.ValueRepresentations.First();

    return DoAdd(vr, tag, values, allowUpdate);
}
```
![image](https://user-images.githubusercontent.com/42465090/196113476-af5ca822-b131-443c-8151-cf061c6241ef.png)
![image](https://user-images.githubusercontent.com/42465090/196114123-b50935c3-3160-45b6-9207-2e9724303c4c.png)

I want to fix this issue myself.

Could you review this issue? @anders9ustafsson

Thank you for the amazing dicom open source!

**Screenshots or test DICOM files**
If applicable, add screenshots or test DICOM files to help explain your problem.

**Environment**
Fellow Oak DICOM version: (e.g. 5.0.2)
OS: (e.g. mac m1)
Platform: (e.g. .NET Framework 6.0.300)

**Comment by mrbean-bremen** [comment]
So, as far as I understand, you want to create a private tag of your own. 

The first thing to consider is that each private tag is associated with a private creator. If you want to write your own private tags, you have to define your own private creator - this is usually the company name followed by a specific name for the current device or software that creates the tags.
If you create a private DICOM tag in fo-dicom, you have to use the constructor that takes the private creator string a s the third argument - this will create the private creator for you, if it doesn't exist yet, and creates the correct tag ID based on the location of the private creator. A private tag without a private creator is not valid.

The second thing is, that if you do this, you _have_ to define the VR of your tag yourself, as there is no way of knowing the VR of an unknown private tag. You can do this by adding a DICOM dictionary entry for your tag, something like:
```cs
var privTag = new DicomTag(0x00f1, 0x0010, "MY_PRIVATE_CREATOR");
DicomDictionary.Default.Add(new DicomDictionaryEntry(privTag, "My private tag", "privateTag1", DicomVM.VM_1, false, DicomVR.CS));
```
This will add the tag to the dictionary with a VR of CS (you replace it with the VR you need).
You can then create your tag:
```cs
var dicomTag =  new DicomTag(0x00f1, 0x0010, "MY_PRIVATE_CREATOR);
```
which will create it with a VR of CS.

As an aside - some time ago I wrote an [answer](https://stackoverflow.com/questions/61062464/how-do-you-register-private-dicom-tags/61066847#61066847) regarding private tags on SO, maybe this will also help you to understand this better.

So, your code does not create valid DICOM, though I think it still would be better if it would be handled in a way that a VR of UN instead of AT is used in this case.

**Comment by HwangTaehyun** [comment]
Thank you for the very detailed explanation @mrbean-bremen! Surprisingly, I already voted up your stack overflow answer before! And I have one more question. How about using my method like the following without adding to dicom dictionary?
```
dicomFile.Dataset.AddOrUpdate<string>(DicomVR.LO, dicomTag, guid.ToString());
```

**Comment by mrbean-bremen** [comment]
Yes, you can do this, though I would advice to still use the version with the private creator to create the tag:
```cs
var dicomTag = new DicomTag(0x00f1, 0x0010, "MY_PRIVATE_CREATOR");
dicomFile.Dataset.AddOrUpdate<string>(DicomVR.LO, dicomTag, guid.ToString());
```
This ensures that the private creator is correctly created or looked up, and the tag is correctly set for this private creator.

**Comment by HwangTaehyun** [comment]
Thank you. I have a last question about that. If there are dicom tags which have the same group number and element number and has different private creator, then does fo-dicom recognizes these dicom tags differently right?

**Comment by mrbean-bremen** [comment]
>  If there are dicom tags which have the same group number and element number and has different private creator, then does fo-dicom recognizes these dicom tags differently right?

Right. As you will use the private creator to construct the private tag you search for, it will know where to look.

**Comment by HwangTaehyun** [comment]
Thank you!

**Comment by gofal** [comment]
This issue seems to be solved now?

**Comment by HwangTaehyun** [comment]
Not yet. I resolved this issue with the following code!
```
dicomFile.Dataset.AddOrUpdate<string>(DicomVR.LO, dicomTag, guid.ToString());
```

**Comment by gofal** [comment]
> Not yet. I resolved this issue with the following code!
> 
> ```
> dicomFile.Dataset.AddOrUpdate<string>(DicomVR.LO, dicomTag, guid.ToString());
> ```

yes, that is fine. It's exactly what you are supposed to do with private Tags.
