### ISSUE TITLE
StoreSCP stops accepting requests when using MaxClientsAllowed and a connection/association is not closed 

### ISSUE THREAD

**Issue by FoundryOfFailedCreations** [fo-dicom/fo-dicom#1468]
**Describe the bug**
First off, I want to mention that I am not certain if this is actually a bug or intended behavior, but I will try and stick to the format for better readability.

We are using FO-DICOM to receive DICOMs from a variety of medical devices in a hospital setting.
Currently our implementation uses Version 4 and has not been upgraded to Version 5 yet.
The problem can be reproduced in Version 5 though, all examples are using FO-DICOM 5.0.3. in a NET6 environment.

We’re seeing some unexpected behaviour when using a StoreSCP server in conjuction with the MaxClientsAllowed option.
By our default, MaxClientsAllowed is set to 20. In most scenarios this works just fine, however there are some cases where the SCP just stops accepting new requests, resulting in errors on the devices.

This happens if:
-	A (let’s call it non-DICOM) TCP message is sent to the SCPs port (e.g. an HL7 message or just an empty one) and the sender expects an answer
-	A DICOM client opens an association but never closes it

I’m just mentioning the first case as this helped me reproduce the error. We never saw any such traffic, but I initially managed to reproduce it using an HL7 message.

In any case, having an open connection or association with the SCP, allows for a maximum of X (where X = MaxClientsAllowed -1) other requests, before the SCP stops accepting further ones.
Any new request will result in a timeout.

Monitoring the ports via commandline (netstat) shows one established connection and X (MaxClientsAllowed -1) connections on CLOSE_WAIT (receiver side) or FIN_WAIT2 (sender side). These do not vanish until the first opened connection (which is still ESTABLISHED at this point) is closed or removed. 
However the first connection only closes after about 2 hours, I assume this happens because Windows just cancels it.

**To Reproduce**
It can be reproduced by creating a STORESCP where the option MaxClientsAllowed has a non 0 value and then opening an association (but not closing it) or sending a non DICOM TCP message, expecting an answer.

The following code is an example that forces the problem:
```
internal class Program
    {
        static async Task Main(string[] args)
        {
            //create server, set max clients allowed
            using var server = DicomServerFactory.Create<CStoreSCP>(11112);
            server.Options.MaxClientsAllowed = 20;

            //create connection request
            var connectionRequest = new AdvancedDicomClientConnectionRequest
            {
                NetworkStreamCreationOptions = new NetworkStreamCreationOptions
                {
                    Host = "127.0.0.1",
                    Port = server.Port,
                }
            };
            //create connection (this is already enough to force the problem, an association is not actually needed)
            using var connection = await AdvancedDicomClientConnectionFactory.OpenConnectionAsync(connectionRequest, default);

            //create an association
            var associationRequest = new AdvancedDicomClientAssociationRequest
            {
                CallingAE = "EchoSCU",
                CalledAE = "EchoSCP"
            };
            //open the association (but never close it)
            using var association = await connection.OpenAssociationAsync(associationRequest, default);

            while(true)
            {
                //do nothing
                await Task.Delay(10000);
            }
        }
    }

```
The CStore class used in this example is copy pasted from your samples (with small modifications to allow any calling AE). 
In this example both the server and connection are created, however it doesn’t matter if a second program were to open it, the results are the same.
Now, using another client to send (for example) CEcho requests to the SCP, there will be 19 (in our scenario, since MaxClientsAllowed is 20) passing CEcho requests, after that, any further request will result in a timeout:

```
var client = DicomClientFactory.Create(modality.IP, modality.Port, false, modality.CallingAE, modality.CalledAE);
client.NegotiateAsyncOps();
var request = new DicomCEchoRequest();
await client.AddRequestAsync(request);
await client.SendAsync();
```

The server after receiving request 19:
![image](https://user-images.githubusercontent.com/52371201/199469986-0e199386-a455-4a86-a1d1-15aaae3dd701.png)

The client sending CEcho requests 1-19:
![image](https://user-images.githubusercontent.com/52371201/199470046-fc7bbc10-9d8a-44e8-87eb-0b0f4d1532ed.png)

The client trying to send further requests after request 19 has passed:
![image](https://user-images.githubusercontent.com/52371201/199470105-2e04f52c-4ae8-44a4-9814-f377534911f0.png)

The netstat results while this happens (I removed my machine’s name in this screenshot):
![image](https://user-images.githubusercontent.com/52371201/199470149-10381fa4-8850-46a0-9827-8a872bd37289.png)

The same can be accomplished using a simple TCP sender and calling socket.receive:
```
using System.Net;
using System.Net.Sockets;
using System.Text;

namespace TCPSender
{
    internal class Program
    {
        private static string SERVER_IP;
        private static int PORT_NO;
        private static bool WaitForAnswer;
        static void Main(string[] args)
        {
            Console.WriteLine("IP");
            SERVER_IP = Console.ReadLine();
        PORT:
            Console.WriteLine("Port");
            if (!int.TryParse(Console.ReadLine(), out PORT_NO))
            {
                Console.WriteLine("Invalid number");
                goto PORT;
            }
            Console.WriteLine("Wait for answers?(y|n)");
            if (Console.ReadLine().ToLower() == "y") WaitForAnswer = true;
            else WaitForAnswer = false;
            while (true)
            {
                var msg = Console.ReadLine();
                send(msg);
            }
        }
        static void send(string? Message)
        {
            string textToSend = Message ?? String.Empty;

            Socket soc = new(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
            IPAddress ipAdd = IPAddress.Parse(SERVER_IP);
            IPEndPoint remoteEP = new(ipAdd, PORT_NO);
            soc.Connect(remoteEP);
            byte[] Bytes = Encoding.ASCII.GetBytes(textToSend);
            soc.Send(Bytes);
            if (WaitForAnswer)
            {
                byte[] buffer = new byte[1024];
                int iRx = soc.Receive(buffer);
                char[] chars = new char[iRx];

                Decoder d = Encoding.UTF8.GetDecoder();
                int charLen = d.GetChars(buffer, 0, iRx, chars, 0);
                System.String recv = new(chars);
                Console.WriteLine(recv);
            }
            soc.Close();
            soc.Dispose();
        }
    }
}
```
In this example, setting WaitForAnswer = true, thus calling soc.Receive() will result the same effect.

**Expected behavior**
I can’t really tell what the expected behaviour should be, I guess I would expect a timeout (closing the connection) after a while.
However, I’m not certain if this is an intended effect on your side.
Should the successful CEchos not be cleared, allowing for new ones, even if the initial connection is still established?

**Further information**
Setting RequestTimeout in the options has no discernible effect, I assume this setting is only used in an SCU client (as the description  suggests).
When setting MaxClientsAllowed to 0 the problem does not appear and any requests passed to the server are answered, even if a “blocking” connection is there. This leads to thousands of CLOSE_WAIT/FIN_WAIT2 handles though, that aren’t getting cleaned up until Windows kills the initial open connection after 2-ish hours. 

I guess my question would be if this is intended behaviour and if we should just always set MaxClientsAllowed to 0, as we cannot control how the devices behave. It seems to happen most often with General Electric (GE) devices, although we also noticed it with Samsung among other manufacturers. 
I don’t know what effect thousands of such CLOSE_WAIT/FIN_WAIT2 handles have on the operating system, I’m yet to set up a test environment to monitor that.

However, this behaviour might allow for potential denial of service attacks. If a malicious attacker were to open a “blocking” connection to an SCP, it might make transmission of DICOMs impossible or severly disrupt it.

On a side note, I think this may be related to the problem mentioned in #1450, as they report the same problem and also use MaxClientsAllowed.

**Comment by jbergstr** [comment]
Thank you, excellent background work!

We too have experienced hangs in Storage SCPs, and there's a lot of similar symptoms we encounter in those situations:
- new connections start failing, or are queued up and accepted very slowly
- the listening sockets that should have been closed just remain in the CLOSE_WAIT state
- the problem may get resolved by itself in a few hours (I assume when Windows finally kills the problematic connection)
- the problem gets resolved by restarting the listening service but may come back in 5 minutes or 5 days, or anywhere in between; the issue comes up completely spuriously

A major difference is that we explicitly set MaxClientsAllowed to 0. Could it be, though, that MaxClientsAllowed just makes the problem obvious sooner; without MaxClientsAllowed it takes a high-traffic environment and a longer time. Another reason could be that hundreds and thousands of sockets stuck in CLOSE_WAIT will eventually exhaust all the available sockets in the OS and that is the actual cause for the traffic to become blocked in our case.

I'm yet to verify whether non-DICOM requests are the root cause in our environment as well, but will certainly experiment with this (in fact we have an internal troubleshooting meeting booked for this particular problem next Monday).

**Comment by FoundryOfFailedCreations** [comment]
Thank you for the input, glad we're not the only ones seeing this problem.

I managed to do some testing in the meantime, to see how MaxClientsAllowed = 0 deals with various levels of traffic when there is a "blocking" connection/association.

I ran two different tests, both times I had 15 STORESCP with MaxClientsAllowed = 0 running, where I intentionally blocked the connections by creating an association but never closing it.
For the first one, I then sent two CECHO requests every five seconds to every SCP. They lasted for about 24 hours before the entire thing crashed. Granted, this crash may also be some fault in our implementation.
For the second test, I used the same setup, but reduced the number of CECHOs to 1 every 30 seconds per SCP. This one is still running for almost a week now without noticeable problems.

So I guess, setting MaxClientsAllowed to 0 may be at least a workaround to prevent a completely blocked SCP, unless you have really high traffic. We have done that in some of our productive environments, I have no results yet though.

On your remark on the non-DICOM requests, I personally do not think that this is the cause.
It's just something I tried in order to reproduce the issue.
We thought it might be the cause too (i.e. some malware scanner probing open ports or some device that's not properly configured), so we set up Wireshark in our customer's environments, but never saw any such traffic at all.
I think it's more the DICOM devices themselves. 
For example, some GE devices tend to open an association before even beginning to create/transform the DICOMs to be sent, which then - depending on the number of items - may cause the device to hit its own timeout, therefore opening a new association without cleaning up the former.
We also observed other devices simply opening an association just to do nothing and then open up another for transmission.

In short: Devices act wierd and we can't control them. 

I just wonder about the original intention behind MaxClientsAllowed.
If this is to limit the number of clients communicating with an SCP, why does it cause timeouts - which are interpreted as actual errors - when the limit is reached? Would it not make more sense to just reject the association in that case?

Also, even if there is a persisting association, why are the following associations never cleaned up? 
I have not dug too deep into the source, but it seems like the SCP is keeping a list of DICOM partners when MaxClientsAllowed has a non zero value. This list is then apparently checked against, when there is a new connection attempt. 
However, I have not found the conditions that need to be met for an entry to be removed from said list.

**Comment by jbergstr** [comment]
We had our test session this morning, wherein we attempted to flood the Storage SCP with various kinds of malformed TCP traffic. We wrote a little program that opened thousands of TCP connections to the SCP with various strategies:
- Opening and closing the sockets normally or just opening the sockets without ever closing them
- Never sending any data, or sending empty data or junk

We couldn't reproduce the issue with MaxClientsAllowed set to 0 with these test cases. Instead, we observer that the SCP detects that the connection was closed (the OnConnectionClosed method was called), and understandably no association was established as this wasn't DICOM. No sockets were left in the CLOSE_WAIT status. So indeed it seems that non-DICOM traffic isn't really the cause here. Unfortunately we ran out of time, so testing with oddly-behaving associations will have to be done some other time.

The idea that this is device-specific is supported by our observation that when CLOSE_WAIT statuses start to pile up, this is always detected on a limited number of source IP addresses, and the same ones every time. Also, in our logs we can clearly see that some devices (especially PACSes) tend to "probe" the SCP before transmitting the images: they open an association, only to close it a while later, and then yet a while later, they send a bunch of objects over a new association. This kind of behavior could indeed be one of the problem sources.

Additionally, our SCP is run in a relatively challenging environment. The inbound associations come from a very mixed bag of sources: PACSes, imaging equipment, and programmatic components that generate or convert DICOM data. Additionally, many of the connections come from external networks over VPNs etc. As we all know, networking is an act of optimism even in the best of conditions, so in this kind of a setup, badly behaving associations are more than likely.

Perhaps our next step should be to take a look at the association establishment and clean-up logic in the fo-dicom source and try to find something there that would match up with our observations?

**Comment by gofal** [comment]
Many thanks for this detailed descriptions!
In version 5 the dicom services (client and server) has been rebuilt on new classes available since netstandard and netcore and getting rid of some old constructions. So version 5 is not as mature as version 4 used to be. So propably there could be some parts missing where such idle connections are not cleaned up correctly.

the feature of allowing a maximum number of clients is an old one and you can find it in many other implementations too. Because the request handler then execute some logic with file system, database etc, it can dramatically break your servers performance if there are too many parallel tasks. So this features prevents some DOS attacks.
As i know it is intended, that the dicomserver does not accept network connections if the limit was reached. otherwiese the server still would have to instanciate some kind of DicomService to handle and process the requests, even if this handler only generates an reject-response. DicomClients usualy do a retry of the the send if there was a connection timeout. I am not sure if clients do a resend automatically, if they get a Reject. Rejects are usually rather for "not supported transfersyntax", "not supported abstractsyntax", "AETitles not allowed" or so, so a retry would not make sense there.

**Comment by amoerie** [comment]
I don't have an immediate suggestion to fix this issue, but wouldn't it help to increase our logging in this area?
Specifically, we should write a warning log entry every minute or so when we've reached the max number of clients and are waiting for a slot to free up before accepting new TCP inbound connections.
Additionally, we should write an info log entry when a slot is freed.
Finally, we should write a warning log entry every minute or so when a TCP connection is occupying a slot without seeing any communication.

These logs would help diagnose the root cause of this issue.

**Comment by jbergstr** [comment]
That certainly does sound like a good starting point for this; more logging usually points to the right direction.

I've also planned to create a test application that creates badly-behaved TCP connections and/or DICOM associations in hopes to be able to reproduce the problem consistently. That might also give us some clues. Unfortunately December is always so busy at work, so that might get postponed until January at least...

**Comment by HwangTaehyun** [comment]
@gofal @jbergstr @amoerie @FoundryOfFailedCreations 
It may be slightly related to this issue, in our case, we use a value of 0 for MaxClientsAllowed and fo-dicom v5.0.3 keeps missing Dicom files under certain circumstances (Some Siemens or Some GE MRI devices). We also use it in a hospital, but OnCStoreRequestAsync is called intermittently. For example, if 200 Dicom images are sent to our server, OnCstoreRequestAsync is called only for the number of 1,2,..,7,..200 images. However, when we bring the same Dicom images and test them in our local environment, it works without any problems!! It drives me crazy!! 😢 

With fo-dicom v4.0.7 there is no problem at all even in hospitals. At first, I thought it was idle connection cleanup not working correctly because when I shut down and restarted the window, it worked! So I looked at the code disposing of service logic when network streams have been read all, but I couldn't find much difference between v4 and v5. (I haven't looked at the number of ports with netstat yet like @FoundryOfFailedCreations.) 

I think it is not related to this, but I would like to know if there's no problem. @amoerie 
https://github.com/fo-dicom/fo-dicom/blob/01283643dcfc47ad7a7c7d1f1e228bfa71973f88/FO-DICOM.Core/Network/DicomService.cs#L248

Can I get some advice on this?

I also suspect this happens due to too many CLOSE_WAIT port some reason.. If same situation happens, I will check netstat result.

Thank you!

**Comment by amoerie** [comment]
> @gofal @jbergstr @amoerie @FoundryOfFailedCreations It may be slightly related to this issue, in our case, we use a value of 0 for MaxClientsAllowed and fo-dicom v5.0.3 keeps missing Dicom files under certain circumstances (Some Siemens or Some GE MRI devices). We also use it in a hospital, but OnCStoreRequestAsync is called intermittently. For example, if 200 Dicom images are sent to our server, OnCstoreRequestAsync is called only for the number of 1,2,..,7,..200 images. However, when we bring the same Dicom images and test them in our local environment, it works without any problems!! It drives me crazy!! 😢
> 
> 
> I think it is not related to this, but I would like to know if there's no problem. @amoerie
> 
> https://github.com/fo-dicom/fo-dicom/blob/01283643dcfc47ad7a7c7d1f1e228bfa71973f88/FO-DICOM.Core/Network/DicomService.cs#L248
> 
> Can I get some advice on this?

What's your question? The GC.SuppressFinalize call will remove that DicomService instance from the finalizer queue if it gets garbage collected. (In normal circumstances, the finalizer thread will invoke the finalizer of each object right before it is garbage collected). The reason we suppress it during disposal is that the finalizer is not needed if you dispose of the DicomService properly (with a using ... statement).
All of this just follows the recommended dispose pattern. See https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose for more info.

I haven't had time to add the aforementioned logging yet. Part of the reason for this is that at my job we're still working with a custom fork of v4 , otherwise we would have definitely already encountered this issue too and I could have looked into it by now.
Moving to v5 (and porting along our custom modifications) is high on the priority list, but it's not done yet.

I'll try to make some time to add the required logging so it can be included in the next fo-dicom release already, so we might be able to diagnose the issue better.

**Comment by amoerie** [comment]
I've created a pull request that adds the necessary logging statements here: https://github.com/fo-dicom/fo-dicom/pull/1529 
I'm still on the fence if we should also have logging for a connection that is open but sees no traffic. I've removed that logging for now because it also gets complicated with cancellation/disposal in the mix. I think we should try to diagnose the issue with the current logging first.

**Comment by amoerie** [comment]
@FoundryOfFailedCreations and @jbergstr I'd be very interested to learn if this issue still occurs with 5.1.0 and if so, what the new logging looks like in that case. :-)

**Comment by FoundryOfFailedCreations** [comment]
@amoerie Thanks for the heads-up and all your effort, I went ahead and tested the same constellation with v.5.1.0.

Let me preface this with me not being too familiar with Microsoft.Extensions.Logging (I usually just slap Serilog on a project and call it a day), but this should do the trick I guess:
```
    using ILoggerFactory factory = LoggerFactory.Create(builder =>
            {
                builder.AddConsole();
                builder.SetMinimumLevel(LogLevel.Debug);
            });
            ILogger<Program> logger = factory.CreateLogger<Program>();
            using var server = DicomServerFactory.Create<CStoreSCP>(11112);
            server.Options.MaxClientsAllowed = 20;
            server.Logger = logger;
```
(As a result I have no timestamps in the logs yet, sorry, I have to figure that out first)

The rest is the same as in my original post, i.e. create server, create a dummy connection and association and never close it.

Now, I encountered some issues when trying to send CECHOs with v.5.1.0, so I left the client on v.5.0.3, I'll expand on this later.

The scenario is the same, MaxClientsAllowed is set to 20, and I have a loop sending CECHOs to the server:

```
var client = DicomClientFactory.Create("127.0.0.1", 11112, false, "test","test");

while (true)
{
    client.NegotiateAsyncOps();
    var request = new DicomCEchoRequest();
    request.OnResponseReceived += (req, resp) =>
    {
        _logger.LogInformation("Response received from => {response}", resp.Status);
    };
    request.OnTimeout +=  (req, timeout) =>
    {
        _logger.LogError("Request has timed out");
    };
    await client.AddRequestAsync(request);
    try
    {
        await client.SendAsync();
    }
    catch (Exception ex)
    {
        _logger.LogError($"Failed to send {ex.Message}");
    }
}
```

The behaviour seems the same, 19 requests get processed, the 20th is blocked - this is the log on the server side (note: my sender is using 5.0.3 here):
<img width="715" alt="image" src="https://github.com/fo-dicom/fo-dicom/assets/52371201/400a237e-fa8a-4db4-addf-9424a6e127a5">

And this is client-side:
<img width="847" alt="image" src="https://github.com/fo-dicom/fo-dicom/assets/52371201/1266d811-672f-42e2-813a-a3f518575e27">

Occasionally, the server throws a warning message on every other request (but not on every request - I think that may be because the client tries to send 3 times before throwing):
<img width="796" alt="image" src="https://github.com/fo-dicom/fo-dicom/assets/52371201/29c06b43-ae92-4340-9d20-0cdbd8f0b3b0">

As for why I am not using 5.1.0 for the client, that's because I experience a completely different behaviour with 5.1.0 when using the exact same code, except for adding a logger in the same way I do for the server:
```
using ILoggerFactory factory = LoggerFactory.Create(builder =>
{
    builder.AddConsole();
    builder.SetMinimumLevel(LogLevel.Debug);
});

var _logger = factory.CreateLogger<Program>();

var client = DicomClientFactory.Create("127.0.0.1", 11112, false, "test","test");
client.Logger = _logger;
```

Running this with 5.1.0. produces an infinite loop of this output, repeating very fast:
<img width="858" alt="image" src="https://github.com/fo-dicom/fo-dicom/assets/52371201/35071b7d-c45c-453a-b6db-260ec6d70104">

SendAsync() gets called once and never again, the server receives just one request:
<img width="664" alt="image" src="https://github.com/fo-dicom/fo-dicom/assets/52371201/b9bd55e1-c849-41f6-ad89-631736661ad9">

Am I doing something wrong here? 
I will run some more tests, but this prevents me from using 5.1.0 on both sides for now.
I have looked a the changelog for 5.1.0 but I can't make out something that would specifically point to this.

Another tidbit I noticed (again using 5.0.3 here):
When letting this run long enough, I would say around 30-ish minutes, the port itsself seems to get wrecked, as the output switches to this:
<img width="857" alt="image" src="https://github.com/fo-dicom/fo-dicom/assets/52371201/f676c325-4a58-479a-8208-d82a6ae74674">

On the server nothing changes though, it keeps producing the maximum number of clients warning:
<img width="773" alt="image" src="https://github.com/fo-dicom/fo-dicom/assets/52371201/f5d3ab06-1801-497a-88f5-3d49b9c77d27">

**Comment by amoerie** [comment]
@FoundryOfFailedCreations  you're running into https://github.com/fo-dicom/fo-dicom/pull/1600

Sorry for not giving you a heads up on that one. If you NegotiateAsyncOps, you must pass a value higher than zero. (don't use int.MaxValue either, because the value is used to set the initial capacity of a list. Use a large value like 1000 or so)
Zero is normally allowed by the DICOM standard, but that's currently broken.

**Comment by FoundryOfFailedCreations** [comment]
@amoerie Ah I see, thanks.

When passing 1000 for NegotiateAsyncOps it works.

So here's the logs for 5.1.0, I also added timestamps and switched the AETs to "client" and "server":

Client side Request 19, passes, gets a response, and releases:
<img width="605" alt="image" src="https://github.com/fo-dicom/fo-dicom/assets/52371201/e4252a86-888d-4621-bdfd-97d28321a235">

Server side Request 19 - Keep in mind it says 20 connected clients on number 19 because I open the first one manually when starting the server and don't close it:
<img width="1079" alt="image" src="https://github.com/fo-dicom/fo-dicom/assets/52371201/e372eaae-60cf-4d60-b77c-e3a093d9784a">

Client side Request 20:
The association request returns with PDU Socket Error twice:
<img width="623" alt="image" src="https://github.com/fo-dicom/fo-dicom/assets/52371201/a0c4d13f-1189-45a2-b5d5-2acfc52ce285">

The third one throws the exception:
<img width="1180" alt="image" src="https://github.com/fo-dicom/fo-dicom/assets/52371201/48452682-3765-4456-a67d-6372ad38a779">

On the server, request 20 just shows the warning:
<img width="756" alt="image" src="https://github.com/fo-dicom/fo-dicom/assets/52371201/3d4b83f9-e200-47ee-ad50-007209db72b8">

I think the question from my original post remains, if I send and complete a request, I would assume my connection is finished and should be removed from the list (?) of connections on the server. But that does not happen. Instead the same client uses 19 connections.
Is there something I can do on the client side to actually force a disconnect? Maybe discard the client and create a new one?

**Comment by amoerie** [comment]
I would definitely be interested to see your full BlockDemo code if that's possible.

Furthermore, there is a lot you can do.
Instead of using DicomClient, you can use AdvancedDicomClientConnectionFactory to open a connection yourself.
Then you can you use that advanced connection to open an association, send requests, etc. 
See here for an example using the advanced client API: https://github.com/fo-dicom/fo-dicom#c-echo-with-advanced-dicom-client-connection-manual-control-over-tcp-connection-and-dicom-association 
This gives you 100% control over the connection and the association on the client side.

However, there might still be a reason why the connection on the server is never cleaned up. That's why I'm interested in debugging your sample code.

**Comment by FoundryOfFailedCreations** [comment]
@amoerie I made the repo for the BlockDemo project public: https://github.com/FoundryOfFailedCreations/BlockDemo

I am actually using the AdvancedDicomClientConnectionFactory in there to create a blocking connection.

**Comment by amoerie** [comment]
I think I found the root cause. 

DicomServer does this at line 373 

```csharp
                        await Task.WhenAny(runningDicomServiceTasks).ConfigureAwait(false);
```

But at that point, the only task in that list is the one that is never closed.
That is why closing any of  the subsequent new connections do not count.

**Comment by amoerie** [comment]
@FoundryOfFailedCreations Thanks to your sample, I have positively identified the root cause of this issue, reproduced it with a unit test and have implemented a fix for this in the linked pull request. Thanks!

Edit: extra verification: your sample blocking demo is also fixed now (on the max-clients-allowed branch):

```
....
info: Program[0]
      test <- C-Echo response [471]: Success
info: Program[0]
      Response received from => Success
dbug: Program[0]
      Request [471]: Success
dbug: Program[0]
      C-Echo request [471]: C-Echo response [471]: Success
dbug: Program[0]
      C-Echo request [471] has completed
dbug: Program[0]
      Lingering on open association for 50ms
dbug: Program[0]
      [SENDING REQUESTS] --> [LINGERING ASSOCIATION]
```

As you can see, the client keeps working well into the hundreds of connections.

**Comment by amoerie** [comment]
> @gofal @jbergstr @amoerie @FoundryOfFailedCreations It may be slightly related to this issue, in our case, we use a value of 0 for MaxClientsAllowed and fo-dicom v5.0.3 keeps missing Dicom files under certain circumstances (Some Siemens or Some GE MRI devices). We also use it in a hospital, but OnCStoreRequestAsync is called intermittently. For example, if 200 Dicom images are sent to our server, OnCstoreRequestAsync is called only for the number of 1,2,..,7,..200 images. However, when we bring the same Dicom images and test them in our local environment, it works without any problems!! It drives me crazy!! 😢
> 
> With fo-dicom v4.0.7 there is no problem at all even in hospitals. At first, I thought it was idle connection cleanup not working correctly because when I shut down and restarted the window, it worked! So I looked at the code disposing of service logic when network streams have been read all, but I couldn't find much difference between v4 and v5. (I haven't looked at the number of ports with netstat yet like @FoundryOfFailedCreations.)

Hi @HwangTaehyun (and I guess also @jbergstr)
If the setting `MaxClientsAllowed` is set to zero, then this is a separate issue. 
First of all, if this problem still occurs, can you create a separate Github issue? 
Then, I would be interested in seeing trace level logging of your DICOM server.
Furthermore, if at all possible, it would also be interesting to have the corresponding low level logging of the client side (modality/PACS) that is sending the files. 
Lastly, to help you with your tests, if you try to reproduce the problem that occurs in the hospital, make sure that the association handshake looks *exactly* the same. That means the presentation contexts + accepted transfer syntaxes, async ops invoked & and async ops performed should be identical.
