### ISSUE TITLE
MRI SPECTROCOPY image not receiving

### ISSUE THREAD

**Issue by arunjoshtech** [fo-dicom/fo-dicom#1517]
Dear Team,
We are not receiving MRI Spectroscopy images from MRI and is there any special services need to enable in SCP Services to receive MRI Spectroscopy images.

**What is, according to you, missing from fo-dicom? Please describe.**
A clear and concise description of the use case that this new feature would solve. 

**Describe the solution you'd like**

**Describe possible alternatives or existing workarounds you've considered**
A clear and concise description of any alternative solutions or existing workarounds you've considered.

**Comment by gofal** [comment]
no, nothing special. The MRI will do an handshake with your SCP and asks to store the images by sending some PresentationContexts (AbstractSyntax + Transfersyntax). You then have to accept the correct presentation contexts.

**Comment by arunjoshtech** [comment]
Dear Gofal,
our library supports Enhanced MRI images, right?  It was asked by machine vendors on this issue.

**Comment by mrbean-bremen** [comment]
Yes, the library certainly supports it. You just have to make sure to accept the correct presentation contexts, as already mentioned by @gofal.

**Comment by gofal** [comment]
"support Enhanced MRI" can mean a lot of different things.

If your application is an image archive, then the support is easy. Just add the AbstactSyntax to the presentation contexts. You then recive this large multiframe file, that you can store on disk and send via SCU to other nodes.

if your application is an image viewer, then the support for EnhancedCT or EnhancedMR is sadly not so good in fo-dicom. This is because there are some DicomTags like Windowing-Infomration, Pixel-Spacing etc, that are not located in the root DicomDataset, but they are often stored in some PerFrameFunctionalGroups. The render method has to read the values from there.
This is why i am working on this branch: https://github.com/fo-dicom/fo-dicom/tree/GH917-RenderingOfEnhanced.
Often there are different render-parameters per frame. The current implementation of DicomImage relies on having 1 RenderPipeline per DicomImage when rendering MultiFrameImages. But in EnhancedMR or EnhancedCT you could need a separate RenderPipeline per Frame. This is why the DicomImage needs some restructuration, too

**Comment by arunjoshtech** [comment]
We received the images but graph lines are removed.
The actual images should be attached below received via another software.
![spectroscopyconquest](https://user-images.githubusercontent.com/63642104/231178036-854bd1c6-2dc7-408d-8f46-81e0abd05cc2.png)
In Our Fo-dicom storage receiver images shows below
![fo dicom specroscopy](https://user-images.githubusercontent.com/63642104/231178365-7390cbee-6893-4518-ba37-13e29921a1ea.png)
it means the graph line are graph are not received

**Comment by mrbean-bremen** [comment]
These graph lines, as you call them, are not part of the image - they are the representation of spectroscopy data. Fo-dicom does not display non-image graphical data (like waveform data, or spectroscopy data) - this is usually done by more specialized software. At least in my opinion, this is outside the scope of fo-dicom as a relatively low-level DICOM implementation.

**Comment by PantelisGeorgiadis** [comment]
Hello @arunjoshtech! I believe @mrbean-bremen is right. The spectroscopy data (graph lines, text, etc.) are most likely stored in a format called `MEDCOM Object Oriented Graphics (OOG)` and can be found with the `0029, xx10` private tag. Essentially, it is a set of graphics and text objects that can be drawn as an overlay on the image. You can find more [here](https://gdcm.sourceforge.net/wiki/index.php/MedCom_OOG_Info).

**Comment by arunjoshtech** [comment]
Dear Team, 
Thanks for the replies and effort, basically an application engineer gives training to technicians on this, before transferring images they have to save them by selecting RBG and then save as a dicom file, so it is resolved. once again thanks for your support.
