### ISSUE TITLE
Remote host and remote port not logged

### ISSUE THREAD

**Issue by jussimattila** [fo-dicom/fo-dicom#1518]
**Describe the bug**
Logs show empty string and zero for remote host and port.

**To Reproduce**
Not sure, seems to be the default behavior in our latest builds using fo-dicom 5.0.3.

**Expected behavior**
Logs should show the remote host and port.

**Screenshots or test DICOM files**
![image](https://user-images.githubusercontent.com/8625258/218487053-dae8e816-8627-4503-aba4-d1344f18a7cc.png)

**Environment**
Fellow Oak DICOM version: 5.0.3
OS: Windows 11
Platform: .NET 6

### Referring to

> [INFO] TRUSSOSRV1 -> Association request:
> Calling AE Title:       TEAMPLAY-OTT
> Called AE Title:        TRUSSOSRV1
> Remote host:            
> Remote port:            0
> Implementation Class:   Implementation Class UID [1.3.6.1.4.1.30071.8]
> Implementation Version: fo-dicom 5.0.3
> Maximum PDU Length:     262144

the remotehost and remoteport values are empty. are you sure the configuration is parsed correctly?

_Originally posted by @gofal in https://github.com/fo-dicom/fo-dicom/issues/1467#issuecomment-1323898991_

**Comment by gofal** [comment]
It seems this has been introduced when the DicomClient was refactored to use the AdvancedDicomClient under the hood. 
the properties RemoteHost and RemotePort are filled from actal network stream. But this logging is done before the actual network connection is opened.

It may be usefull to do the logging before the actual network traffic, so that in case of an exception the user can read what the client wanted to call.
So the properties have to be filled from the parameter so the "SendAsync" method.
