### ISSUE TITLE
How to resize a Big resolution Dcm file?

### ISSUE THREAD

**Issue by wangning08115** [fo-dicom/fo-dicom#1547]
1. The DX film one dcm file resolution more than 3000x3000
2. So the dcm file is very big.
3. How to convert the dcm file to one 1000x1000 resolution dcm file?

**Comment by gofal** [comment]
you cannot "convert" a dicomfile to a rescaled file. What you actually want to do, is to create a new dicomfile, that has a derived content from an other dicomfile.
so first you have to open the large file and get the pixeldata.
then you have to rescale it (using an appropriate algorithm that preserves best quality).
Then you have to create a new Dataset using NEW SopInstanceUIDs. you will be able to copy most of the tags, but some technical tags will be updated. And finally you should add a SourceImageSequence (0008,2112) containt the InstanceUID of the big image as Referenced SOP Instance UID.

It is very important that you create new UIDs. image you would use the same instanceuid and your image would be spread around. But some other application got the origianal image and does some reporting. Reports may contain a reference to the SopInstanceUID and contain some findings which are stored as coordinates within the image.
If this report then will be opened together with your rescaled file and your rescaled file would have the same Instance UID, then the coordinates will show a wrong position.
Remember, we are working with medical data, which is very sensitive and the health of some human may depend on that.

This is, what leads me to the question: why might you rescale the dcm file and throw away a lot of information?
If you want do do so because you are developing some software that should be able to display the image faster, then you could consider just storing a rescaled jpeg of the rendered image instead of creating a new dcm file?
