### ISSUE TITLE
Dicom-file with private tag without privateCreator can be stored to and read from disk, with creator the tag is not found

### ISSUE THREAD

**Issue by fabiankrieg** [fo-dicom/fo-dicom#1548]
**Describe the bug**

I tried to store Dicom-files including Private Tags to disk and read them in again. I always encountered errors like `Tag: (0019,1027:testcreator) not found in dataset` when trying to access the data stored in the tag until I removed the creator. 

As far as I figured out the tag is stored to the file and exists in the dataset I load from the file. Yet, `dm.GetSingleValue<string>(test_tag)` will return an error. Also, the private creator is read as `unknown` from the file.

I do wonder whether I just mistreat FO-DICOM here. But as the creator seems to be handled by FO-DICOM in the background I am under the impression that no additional actions by me should be necessary to make the following MWE work.

Here is a glimpse at the debuger, MWE follows below.

![grafik](https://user-images.githubusercontent.com/32844842/233938357-4bb23ac9-99b7-443c-bf1c-7e07a7c2b48b.png)

**To Reproduce**

```csharp
using FellowOakDicom;

namespace Save_LoadTest
{
    internal class Program
    {
        private static string filename = "Testfile.dcm";

        static void Main(string[] args)
        {
            var working_tag = DicomTag.Parse("0019,1027");
            var erroneous_tag = DicomTag.Parse("0019,1027:testcreator");

            WriteTestFile(filename, working_tag, "this will work");
            ReadTestFile(filename, working_tag);

            WriteTestFile(filename, erroneous_tag, "this will crash");
            ReadTestFile(filename, erroneous_tag);
        }

        static void WriteTestFile(string fileName, DicomTag test_tag, string value)
        {
            DicomDataset dm = new();
            dm.AddOrUpdate(test_tag, value);

            // mandatory fields
            dm.AddOrUpdate(DicomTag.Parse("0008,0016"), "1.2.840.10008.5.1.4.1.1.4");
            dm.AddOrUpdate(DicomTag.Parse("0008,0018"), "1.3.6.1.4.1.9328.50.51.267485233220005486");

            var file = new DicomFile(dm);

            if (File.Exists(fileName))
            {
                File.Delete(fileName);
            }

            file.Save(filename);
        }

        static void ReadTestFile(string fileName, DicomTag test_tag)
        {
            var dm = DicomFile.Open(filename, FileReadOption.ReadAll).Dataset;
            Console.WriteLine(dm.GetSingleValue<string>(test_tag));
        }
    }
}
```

Which yields for me:

```shell
this will work
Unhandled exception. FellowOakDicom.DicomDataException: Tag: (0019,1027:testcreator) not found in dataset
   at FellowOakDicom.DicomDataset.GetSingleValue[T](DicomTag tag)
   at Save_LoadTest.Program.ReadTestFile(String fileName, DicomTag test_tag) in D:\Git\Save_LoadTest\Program.cs:line 43
   at Save_LoadTest.Program.Main(String[] args) in D:\Git\Save_LoadTest\Program.cs:line 18
```

**Expected behavior**

The tag is found and the data is returned without errors in both cases.

**Environment**

Fellow Oak DICOM version: 5.0.3
OS: Windows 10 x64
Platform: NET Framework 6.0

**Comment by mrbean-bremen** [comment]
The first version without the private creator that is working for you should actually _not_ work (because of the missing private creator), and I believe it will not work with the current development version.

The second version (with the private creator) only works for known private creators, e.g. private creator/private tag combinations contained in the private dictionary in `fo-dicom`. Otherwise, the VR of the tag is not known, and fo-dicom does not know how to write the tag.
In this case, you have to either add your tag to the private dictionary, e.g. something like:
```cs
  var privCreatorDictEntry = new DicomDictionaryEntry(new DicomTag(0x0019, 0x0027), "Test Creator", "testcreator", DicomVM.VM_1, false, DicomVR.LO);
  DicomDictionary.Default.Add(privCreatorDictEntry);
```
or you have to use the version of  [DicomDataset.AddOrUpdate](https://fo-dicom.github.io/stable/v5/api/FellowOakDicom.DicomDataset.html#FellowOakDicom_DicomDataset_AddOrUpdate__1_FellowOakDicom_DicomVR_FellowOakDicom_DicomTag___0___) which also provides the VR:
```cs
  var dicomTag = new DicomTag(0x0019, 0x0027, "testcreator");
  dm.AddOrUpdate(DicomVR.LO, dicomTag, value);
```
Note also that the private element has a maximum of 0xff, e.g. you should use 0x0027 instead of 0x1027. If you use the later, `fo-dicom` assumes that the private creator already exists at a known location (in this case at 0x0019, 0x0010) and will not create it. If you are not familiar with the way private tags work, you may have to read up in the [standard](https://dicom.nema.org/medical/dicom/current/output/chtml/part05/sect_7.8.html) to better understand what is going on.

**Comment by fabiankrieg** [comment]
Thanks a lot for the conclusive and extensive response!! It took me a while to read through the resources, try things, read again ... . But I think I got it now and also understood why FO-Dicom handles things differently for different element ranges.

One of the main pitfalls for me was that there seems to be no warning when I set a value to an unknown private tag without setting the value range. I don't know if there's a fast way of checking that.

Anyways, thanks a lot!

**Comment by mrbean-bremen** [comment]
> One of the main pitfalls for me was that there seems to be no warning when I set a value to an unknown private tag without setting the value range

I guess you mean value representation. As I wrote, I think that this has been fixed in the development branch.

**Comment by fabiankrieg** [comment]
Exactly, that is the correct term. Perfect!
