### ISSUE TITLE
Fix DicomServer<T>(int port) constructor

### ISSUE THREAD

**Issue by HelderMPinhal** [fo-dicom/fo-dicom#155]
When using `var server = new DicomServer<DicomCEchoProvider>(104);` the server will not run and will not throw any exception.
To make it work, we need to `var server = new DicomServer<DicomCEchoProvider>(104, null, null, ConsoleLogger.Instance);` for instance. What I mean is, we have to explicitly provide a Logger.
I believe this is by not having any implementation set up at the moment of the initialization.
I'm not up to date on the new changes but I think it's supposed to have support for a Null Logger.

My suggestion is to either fix the null support on the Logger param or throw an exception when creating a DicomServer. I think the first option would preferable.

**Comment by anders9ustafsson** [comment]
@HelderMPinhal When you state that  the server is not running, I assume you mean that you don't see any log messages? Because as far as I can see, the server is responding as expected even with the short-hand initialization `new DicomServer<DicomCEchoProvider>(104)`.

In PR #91, I implemented a no-op logger called `NullLogger`. This logger is now default in for all targeted platforms. This means that in 2.0, if you want to dump the output from logging onto the console window, you need to explicitly set the logger implementation to `ConsoleLogger`:

    LogManager.SetImplementation(ConsoleLogManager.Instance);

or, if you only want the `DicomServer` to log to the console, you can use the call you suggested:

    var server = new DicomServer<DicomCEchoProvider>(104, null, null, ConsoleLogger.Instance);

@HelderMPinhal Please double-check if my explanation applies to your application, i.e. that the server **is** in fact running, and it is only the logging that is de-activated.

For perceived portability (`ConsoleLogger` is not available on all platforms), I would prefer to have `NullLogger` remaining the default implementation for all platforms. However, I am of course open for arguments if there is consensus in reverting to `ConsoleLogManager` for .NET.

**Comment by HelderMPinhal** [comment]
@anders9ustafsson I should apologize. The server is running indeed.
It must have been some other thing that prevented the server from running.

Regarding the NullLogger, I completely agree that it should be the default option.

**Comment by anders9ustafsson** [comment]
@HelderMPinhal Nothing to worry about, it is not always easy to keep track of all changes, especially when they are hidden in closed pull requests :-)

Good to get your confirmation, I will then close this issue. And once again, thanks for reporting, it is always good to get the concerns and questions up on the table.
