### ISSUE TITLE
Problem with DicomServer when using a port already being used.

### ISSUE THREAD

**Issue by BobSter3000** [fo-dicom/fo-dicom#157]
DicomServer<DicomCEchoProvider> ds = new DicomServer<DicomCEchoProvider>(5104) with port 5104 already being used.
The System.Net.Sockets.SocketException does not seem to propagate back up as in the old version.  Console logging shows: A first chance exception of type 'System.ObjectDisposedException' occurred in mscorlib.dll.

**Comment by IanYates** [comment]
Thanks for reporting.  I'll investigate over the weekend, unless @anders9ustafsson beats me to it :)

**Comment by anders9ustafsson** [comment]
I'll try to keep my hands off this time, @IanYates :-) Many thanks for looking into it.

**Comment by IanYates** [comment]
So from what I can see, the `Listen(int port, string certificateName)` method in `Dicom.Network.DicomServer<T>` class is called from within the `DicomServer<T>` constructor wrapped within a Task.Factory.StartNew.  The exception is getting raised, but is then being swallowed since it's occurring within a task - by the time the exception has happened control has already returned to the caller of the constructor.

I think we should move the 
```
var listener = NetworkManager.CreateNetworkListener(port);
listener.Start();
```
lines out of the Listen() method, either into the constructor itself or at least into some Init() method.

That will then ensure any problems with opening the TCP port will be caught synchronously during construction as was the previous behaviour.

It will involve promoting the `listener` variable to be a private member of the class but I don't see any problem with that.

Does any of this sound inappropriate?

**Comment by anders9ustafsson** [comment]
Sorry for not having responded earlier, I have been a little short of time lately.

@IanYates Yes, I now see the issue with the exception being "swallowed", thanks for spotting it. I am still a little reluctant to the proposed modifications; defining `listener` in the constructor would add undesirable complexity to the constructor, and adding an `Init()` method to `DicomServer` would change the public API.

My thinking right now is instead to make the created `Task` a field member of the class. That way it would be possible to retrieve task status and potential exceptions by querying the `Task` field.

What do you think about this?

**Comment by IanYates** [comment]
I'll work down those lines and see if I run into trouble

**Comment by anders9ustafsson** [comment]
@IanYates Have you had time to look into this? Otherwise, I might have some time today if you want me to take a look.
