### ISSUE TITLE
The DicomImage method cannot be called correctly in version 5.0, and there is no pixelData in the returned instance

### ISSUE THREAD

**Issue by vincent1996** [fo-dicom/fo-dicom#1652]
**Describe the bug**
var image = new DicomImage("test.dcm");
var bitmap = image.RenderImage().As<Bitmap>();
Error： FellowOakDicom.Imaging.DicomImagingException:“Cannot cast to 'Bitmap'; type must be assignable from 'Byte[]'”

This issue is not present in fo-dicom.Desktop version 4.0

**Screenshots or test DICOM files**
![图片](https://github.com/fo-dicom/fo-dicom/assets/16411793/d0b28133-12a4-4fce-84cf-80f09236642c)
![图片](https://github.com/fo-dicom/fo-dicom/assets/16411793/d86b2254-7ca2-4b76-8141-a4a30fb76c45)

**Environment**
Fellow Oak DICOM version: (e.g. 5.1.1)
OS: (e.g. Windows 8.1 x64)
Platform: (e.g. .NET Framework 4.6.2) or
Platform: (e.g. .NET Framework 6)

**Comment by vincent1996** [comment]
Sorry, I found a solution

**Comment by gofal** [comment]
For those, wo are having the same problem and found this issue, here is the solution:
fo-dicom internally strongly uses dependency injection. for images and rendering there is an ImageManager class, that handles rendering. Because Bitmap is depending on Windows and not cross-platform, it would be a bad idea, to use Bitmap by default. So the default implementation is RawImageManger, which just creates an array of colors. 
If you are using windows, then you can register the WinFormsImageManger. if you prefer to use ImageSharp then you can register ImageSharpImageManager.
On the main ReadMe page there is a description how to register other managers:

https://github.com/fo-dicom/fo-dicom#image-rendering-configuration
