### ISSUE TITLE
Strong memory use surge on HTTP request to DicomService

### ISSUE THREAD

**Issue by danzhik** [fo-dicom/fo-dicom#1678]
**Describe the bug**
Hello, we have noticed a strange behaviour occurring in `DicomSerivce` when it receives an HTTP connection request. Total used memory of our application rises to almost 1.5GB compared to normal idling consumption of ~120MB. We have performed tests on 3 different Windows operated machines, with total of 4GB, 32GB and 48GB RAM present, and the peak occupied memory amount remains the same, i.e., it's not trying to consume all the free memory, but always ~1.3GB. The result is the same using fo-dicom v5.0.3 and the latest available v5.1.1.

What is more interesting, is that the connection is not being terminated ever by server, i.e., unless client aborts connection itself the socket remains open and the memory can not be released using GC. Additionally, I have taken 3 snapshots during the profiling run, and another anomaly showed up. When the HTTP connection is "open", there's an additional instance of LOH present in use. Please refer to screenshots for the details

Once the connection is terminated by a client and GC is triggered, the total used memory returns to normal, as you can see from the 3rd screenshot.

The only logs corresponding to actions' timepoints during testing are these 2 lines when client aborts the connection:
`[11:07:34 DBG] Read 0 bytes from network stream while reading PDU, connection will be marked as closed`
`[11:07:34 INF] Connection closed`.

At least in our case, this creates a little bit of a problem as our application, which hosts fo-dicom's `DicomServer`, usually runs in environments with limited resources (4-8GB of RAM in total) and these spikes may create a resources starvation situation, if an automated port scanner or something similar hits the `DicomServer` and does not terminate the connection itself. 

**To Reproduce**

1. Run the instance of `DicomServer<T>`. In our case we create it using `dicomServerFactory.Create<CStoreSCP>`, where `CStoreSCP` is declared like `public class CStoreSCP : DicomService, IDicomServiceProvider, IDicomCEchoProvider, IDicomCStoreProvider`. 
2. Open a new tab in the browser (we've used latest Chrome and Edge in our tests, if that matters) and type in the URL of created `DicomServer`, e.g., `http://localhost:104`. 
3. Unless you close the tab or terminate an attempt to get a response from the server, the problem will be present

**Expected behavior**
Either a termination of connection on handshake phase if the connection protocol is incompatible, or later after some timeout if earlier termination not possible.

**Screenshots or test DICOM files**
Memory graph of profiling session:
![image](https://github.com/fo-dicom/fo-dicom/assets/35699225/b1b1c7e8-e34a-4735-b2ec-e3c781de016f)

Generations' stats from "before", "during" and "after" in corresponding order of snapshots:
![image](https://github.com/fo-dicom/fo-dicom/assets/35699225/07e572e2-6059-4327-a56e-77b49d66859c)
![image](https://github.com/fo-dicom/fo-dicom/assets/35699225/78ae3837-4fd4-42f8-aa24-84daa7bdf54a)
![image](https://github.com/fo-dicom/fo-dicom/assets/35699225/e1487bd6-c23d-4c05-be67-0613357c3898)

**Environment**
Fellow Oak DICOM version: 5.0.3, 5.1.1
OS: Windows 11, Windows Server 2019
RAM: 4GB/32GB/48GB
Platform: .NET 6

If you will not be able to get the same results during testing, I'd be happy to share a Workspace's dump (judging by other issues, it seems like you also use dotMemory) by any means you find appropriate.

And taking the opportunity, I would like to thank you personally and on behalf of our team for creating and maintaining such an amazing toolset to work with DICOM protocol on so many levels! 

Thank you in advance for looking into this!

**Comment by amoerie** [comment]
I will look into this. Please give me some time.

**Comment by amoerie** [comment]
So, I looked at this in detail, and I think the problem is clear.
You see, when a DICOM client connects to a DICOM server, the following things happen at the TCP level:

1) A TCP connection is opened
2) A DICOM association request is sent
3) This DICOM association looks like this:

![image](https://github.com/fo-dicom/fo-dicom/assets/2063584/87f97f42-dd06-44af-a72b-7d567e6f435f)

Every DICOM message is encoded as a PDU, a Protocol Data Unit. A PDU always begins with 6 bytes, the first 2 contain the type of PDU ( 0x1 = Association Request, 0x2 = Association Accept, 0x3 = Association Reject, etc.) and the last 4 bytes contain the length of the PDU. 
Especially of note is this Length field: 

![image](https://github.com/fo-dicom/fo-dicom/assets/2063584/50de773a-8dc3-465e-a4ae-6a3ffd4a11d9)

These 4 bytes indicate how long the ensuing PDU will be, and thus how many bytes the DICOM server should expect to read.

You can find the code that reads  the first 6 bytes, and then the remaining [PDU Length] bytes into a MemoryStream here in DicomService:

https://github.com/fo-dicom/fo-dicom/blob/5524ebced843dee46d35febe664a0da570c953a3/FO-DICOM.Core/Network/DicomService.cs#L481-L542

As you can see, we first read into a 6 bytes sized buffer (the header) and then into a `rawPduLength` sized byte buffer.

Now, coming back to your issue, you're sending an HTTP GET request to this DICOM server. 
Sending an HTTP GET request involves sending the text "GET / HTTP/1.1" (in ASCII encoding if I recall correctly) to an HTTP server.

At the byte level, this is what that HTTP request looks like:

![image](https://github.com/fo-dicom/fo-dicom/assets/2063584/303ef3d6-973d-49b9-98c3-467536be0805)

When the DICOM server reads the first 6 bytes of that request, we get the following (hexadecimal) buffer: 
`[ 0x47, 0x45, 0x54, 0x20, 0x2F, 0x20 ]`

Now, the DICOM service reads the PDU type from the first two bytes and the PDU length from the remaining four bytes.
The PDU length is determined as follows:

1) Take the four bytes
`0x54, 0x20, 0x2F, 0x20`
2) Interpret them as a C# integer: 

```
01010100 00100000 00101111 00100000
-------  -------  -------   -------
  (0x54)   (0x20)   (0x2F)   (0x20)
```
The result of this is 1 411 395 360, or 1.4 million. Looks familiar?

When the following line executes, we will request a buffer of size 1.4 million bytes, which amounts to about 1.4GB. :-) 

```
rawPduBuffer = _memoryProvider.Provide(rawPduLength);
```

So, now that we know what the issue is, what can we do about it. The fact is that we obviously don't support HTTP requests to our DICOM server. So don't do that! :-) 
But there are probably things we can do to improve our resilience against random network traffic that does not adhere to the DICOM standard.

First of all, we could exit early if the first 2 bytes of the PDU header do not resolve to a known DICOM PDU type. In this case we probably want to close the connection too. 
Secondly, we could add some sort of timeout to the Networkstream reading code that bails out if the promised number of bytes don't arrive in a timely fashion. However, this would be tricky, as we don't know how many applications out there in the wild rely on us not closing a connection if it does not have any activity.

@gofal @mrbean-bremen Any input welcome here. Do you know how other DICOM libraries in other languages handle this?

**Comment by danzhik** [comment]
Just wow😅 Thank you so much @amoerie for digging out the truth, it was so kind of you to provide such a thorough explanation. I was definitely not expecting an answer, moreover a pull request fixing the problem in less than a day, huge kudos for all this👍 I had a gut feeling myself that the problem occurs due to an incompatible protocol and request data not conforming to PDU format, but ,of course, without in-depth knowledge of the library it would take me X-folds of the time you spent to find the root. Many thanks from our team, you folks are the MVPs of this week for us

**Comment by amoerie** [comment]
Glad to help, this was fun to figure out! 
The fix was rather straight forward too, but it might take some time before it gets merged and released. 

And thank you for the kind words, that's always nice to hear 👍

**Comment by gofal** [comment]
An very interesting issue. I was surprised that the DicomServer is so simply vulnerable to an DOS attack. But the explanation is more than clear. I would have guessed that because the DicomServer will not be able to parse a http request as DICOM Dataset, the connection will fail fast. It is bad luck that it happens that the length value is such a high value and the the DicomServer just waits until this amout of data arrived.

Orthanc handles http request and closes the association fast. DicomObjects on the other hand results in a timeout. 
I would vote for the fix to exit early if the first 2 bytes of the PDU header do not resolve to a known DICOM PDU type. 

And maybe we could also hardcode a maximum value for the length of an Association Request message? This would also lead to an early exit of an invalid request. And while a timeout solves the problem that the association stays open for long, it would not solve the memory consumption issue. but a max length for the rented array would.

**Comment by amoerie** [comment]
It's not just association requests, it's any kind of PDU message.
As for a max size, since the DICOM standard provides 4 bytes for an unsigned number, I think it can go up to 4 GB and still be possibly valid. But I agree, such large values would only be expected with P-DATA-TF messages, so we could maybe enforce some maximum on other types.

I think a more solid approach could be to not allocate (rent) the 1.4GB immediately, but only allocate it in chunks when we actually receive the data.
This is also how MemoryStream works under the hood, even if you specify a large capacity. But the PDU early bailout will already work wonders. 

If you talk about security, anyone intimately familiar with the DICOM network stack will always be able to hand craft a network message that allocates a lot. But I do agree that Fellow Oak DICOM should be more resilient against accidental network traffic such as HTTP requests.

**Comment by mrbean-bremen** [comment]
> If you talk about security, anyone intimately familiar with the DICOM network stack will always be able to hand craft a network message that allocates a lot.

This is exactly what I thought while viewing your PR. You can always make a hand-crafted DOS attack that way, so I think what you did here is good enough against accidental incorrect traffic. 

Securing against too much memory load from legitimate requests is a bit more complicated - restricting the size of data and the number of connections, and allocating memory in chunks as you wrote are certainly ways to go here.

**Comment by amoerie** [comment]
> This is exactly what I thought while viewing your PR. You can always make a hand-crafted DOS attack that way, so I think what you did here is good enough against accidental incorrect traffic. 
> 
> Securing against too much memory load from legitimate requests is a bit more complicated - restricting the size of data and the number of connections, and allocating memory in chunks as you wrote are certainly ways to go here.

Actually the best way to add security is probably to make use of our recently added TLS support. That way, you basically eliminate bad actors from being able to even contact your DICOM services at all, since they wouldn't get past the TLS handshake.
