### ISSUE TITLE
DLL "Dicom.Native" not found when rendering an image on .Net 4.8 (x64)

### ISSUE THREAD

**Issue by lalenzos** [fo-dicom/fo-dicom#1680]
**Describe the bug**
I'm currently facing the problem that I cannot convert/render a DICOM image to a png/jpg. I'm following the documentation, but unfortunately I'm always getting the Exception of type "DllNotFoundException" in Dicom.NativeCodecs.dll, stating that "the DDL 'Dicom.Native' could not be loaded: the module could not be found.".
The documentation also describes that the "Dicom.Native-win64.dll" or "Dicom.Native64.dll" should exist on an x64 platform, but both are not existing.
I'm refering to this: https://github.com/fo-dicom/fo-dicom/wiki/Native-codecs-on-.NET

**To Reproduce**
(attached example application (see line 45 "dicomImage.RenderImage()") with example Dicom files)
[DicomRenderImageTest.zip](https://github.com/fo-dicom/fo-dicom/files/13269796/DicomRenderImageTest.zip)

**Expected behavior**
Rendering/Converting the DICOM format into an image format (jpg, png, ...).

**Screenshots or test DICOM files**
![image](https://github.com/fo-dicom/fo-dicom/assets/23080941/b98ae29a-3418-4bda-a481-0ae0820242e3)

**Environment**
fo-dicom - version 5.1.1
fo-dicom.Codecs - version 5.10.8
fo-dicom.Imaging.ImageSharp - version 5.1.0
OS: Windows 11 Pro
Platform: .NET Framework 4.8 - x64

Thanks

**Comment by anishsingh0302** [comment]
I am also facing same error after upgrading to latest version of fo-dicom.
fo-dicom - version 5.1.1
fo-dicom.Codecs - version 5.10.8
fo-dicom.Imaging.ImageSharp - version 5.1.0

System.DllNotFoundException: Unable to load DLL 'Dicom.Native': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

  Stack Trace: 
DicomJpeg2000NativeCodec.Memset(Void* ptr, Int32 value, UInt32 num)
DicomJpeg2000NativeCodec.Decode(DicomPixelData oldPixelData, DicomPixelData newPixelData, DicomCodecParams parameters)
DicomTranscoder.Decode(DicomDataset oldDataset, DicomTransferSyntax outSyntax, IDicomCodec codec, DicomCodecParams parameters)
DicomTranscoder.Transcode(DicomDataset dataset)
DicomTranscoder.Transcode(DicomFile file)

Anyone of them found any solution?

**Comment by udiatcimd** [comment]
Facing the same problem after updating to the latests version of fo-dicom

I get the error trying to use dicomfile.Clone

I was working with fo-dicom: 5.0.3 and fo-dicom.codecs: 5.0.3 but since I updated to the latest version and now i get the same error when i try to clone a dicomfile:

`dicomFile.Clone(DicomTransferSyntax.ExplicitVRLittleEndian);`

I initialize the transcodermanager like this (it was working just fine on previous versions):

```
                new DicomSetupBuilder()
                .RegisterServices(s => s.AddFellowOakDicom().RemoveAll<FellowOakDicom.Imaging.NativeCodec.NativeTranscoderManager>())
                .Build();
```


Maybe we have to wait untill fo-dicom.codecs releases a 5.1.1?

thanks!

**Comment by amoerie** [comment]
@lalenzos 

I upgraded your solution + csproj to the SDK style format (using https://github.com/hvanbakel/CsprojToVs2017 ) and updated to the latest fo-dicom and fo-dicom.Codecs.
Then, I cleaned up your csproj properties to reduce the number of configurations. AnyCPU will never work, because you will always need 32 bit or 64 bit with the codecs. And setting PlatformTarget to x64 under the AnyCPU configuration is ... confusing. Visual Studio used to have bugs when there was no AnyCPU configuration, but those are fixed as far as I'm aware. JetBrains Rider can definitely handle it as well.

Anyway, here is a working zip file that contains your sample project where the codecs work. So it is definitely a matter of configuration. I did not find the minimal set of changes you guys need to get this working, I'll leave that exercise to you.

[DicomRenderImageTest2.zip](https://github.com/fo-dicom/fo-dicom/files/14007040/DicomRenderImageTest2.zip)

@anishsingh0302 and @udiatcimd See above. The codecs work on .NET Framework. We also have unit tests that prove this. 

Maybe, and this is just a suspicion, the old .csproj format is causing trouble here. Both the unit tests and my working sample use the SDK style. But I don't have time left to verify this, and it would also surprise me. But I have been surprised before. :-)

**Comment by jaime-olivares** [comment]
This issue should be closed if there is no more feedback.

**Comment by PatrikBrynolfsson** [comment]
Hello!

I can confirm that the issue is caused by the old .csproj format. The Dicom.Native.dll is missing when building the project.

To investigate, I created a new project targeting .NET Framework 4.7.2 using the old .csproj format, with the same Program.cs from [DicomRenderImageTest2.zip](https://github.com/fo-dicom/fo-dicom/files/14007040/DicomRenderImageTest2.zip), and the DLL was not present. However, when I built a project with the same .NET version (4.7.2) using the new SDK-style .csproj format, the Dicom.Native.dll was correctly included.

For those experiencing this issue and unable to convert their project to the new format, a workaround is to:

1. Create a temporary project with the same .NET version as your project.
2. Install the fo-dicom and fo-dicom.Codecs NuGet packages.
3. Use the Program.cs from [DicomRenderImageTest2.zip](https://github.com/fo-dicom/fo-dicom/files/14007040/DicomRenderImageTest2.zip) and build the project.
4. Once built, locate the Dicom.Native.dll and copy it to your legacy project.

This should resolve the missing DLL issue while keeping your project in the old .csproj format.

I should add that I changed the DicomSetupBuilder call to this in Program.cs

new DicomSetupBuilder()
   .RegisterServices(s => s
       .AddFellowOakDicom()
       .AddTranscoderManager<FellowOakDicom.Imaging.NativeCodec.NativeTranscoderManager>())
   .SkipValidation()
   .Build();

**Comment by zhaotianff** [comment]
I also encountered this problem and used the following method:
1. directly download the Nuget package and extract it. 
https://www.nuget.org/api/v2/package/fo-dicom.Codecs/5.16.3
2. get file Dicom.Native.dll in the `fo-dicom.codecs.5.16.3.nupkg\runtimes\win-x64 \native` path

> Hello!
> 
> I can confirm that the issue is caused by the old .csproj format. The Dicom.Native.dll is missing when building the project.
> 
> To investigate, I created a new project targeting .NET Framework 4.7.2 using the old .csproj format, with the same Program.cs from [DicomRenderImageTest2.zip](https://github.com/fo-dicom/fo-dicom/files/14007040/DicomRenderImageTest2.zip), and the DLL was not present. However, when I built a project with the same .NET version (4.7.2) using the new SDK-style .csproj format, the Dicom.Native.dll was correctly included.
> 
> For those experiencing this issue and unable to convert their project to the new format, a workaround is to:
> 
> 1. Create a temporary project with the same .NET version as your project.
> 2. Install the fo-dicom and fo-dicom.Codecs NuGet packages.
> 3. Use the Program.cs from [DicomRenderImageTest2.zip](https://github.com/fo-dicom/fo-dicom/files/14007040/DicomRenderImageTest2.zip) and build the project.
> 4. Once built, locate the Dicom.Native.dll and copy it to your legacy project.
> 
> This should resolve the missing DLL issue while keeping your project in the old .csproj format.
> 
> I should add that I changed the DicomSetupBuilder call to this in Program.cs
> 
> new DicomSetupBuilder() .RegisterServices(s => s .AddFellowOakDicom() .AddTranscoderManager<FellowOakDicom.Imaging.NativeCodec.NativeTranscoderManager>()) .SkipValidation() .Build();
