### ISSUE TITLE
Read DICOM file using UnseekableStream

### ISSUE THREAD

**Issue by bcarthic** [fo-dicom/fo-dicom#1703]
Is there a way to open a DICOM file using unseekable stream? I see UnseekableStreamByteSource in the source code but wasn't sure if this was supported. Today, we have to download the entire file in memory to do any processing, especially for transcoding. If we have to transcode a frame then we have to create a dataset and then do transcode. I was looking for better option where consume too much memory. Any insights would be really helpful. 

Thanks

@gofal @amoerie

**Comment by gofal** [comment]
Somehow the data has to be downloaded anyway.
The UnseekableStreamByteSource is just a helper class to avoid NotSupportedExceptions. but in fact, it reads the stream sequentially, stores it into a memorystream buffer and then does all the seeking within this buffer. 

If you want to transcode a frame, then you still have to download the dataset containing all the metadata first, because otherweise you do not know where the frame starts. In case you have a multiframe image with many frames and you only want to access the first frame, then you could expect an efficient way by stopping downloading data after the first frame.
But in case you want to download any frame in the middle - or the last frame - then you always have to download the whole data anyway. Since it is a unseekable stream, you can never jump to the position of the frame, but you always have to read all the content until that frame.

I do not know your exakt infrastructure, but I guess, fo-dicom is not the right spot where you should try to optimize your network traffic, because the (only) goal of fo-dicom is to parse, handle and proces DICOM data.
You should enhance your server application where you then load the Dicom file in memory and then on request of the client only deliver the desired frame.

**Comment by bcarthic** [comment]
@gofal , Thanks for your response, we do have caching mechanism at our server to send frame data. But we have issues when the file size is bigger and transcoding consumes lot of memory which results in OOM exception. I understand the goal of fo-dicom, I was trying to understand was there a better alternative.
