### ISSUE TITLE
DICOM dataset is missing pixel data element

### ISSUE THREAD

**Issue by patachi** [fo-dicom/fo-dicom#1712]
**Describe the bug**
Trying to render the image by using `DicomDirectoryRecord` provided by `DicomDirectory` at the Image/Instance level

**To Reproduce**
```
// Creating a new DicomDirectory to sort out existing chunks of dcm files and export them as png alongside
var dcmDir = new DicomDirectory();
foreach (var filePath in Directory.GetFiles(@"C:\DicomExports", "*", SearchOption.AllDirectories))
{
    try
    {
        var f = DicomFile.Open(filePath, FileReadOption.ReadAll);  // nope
        dcmDir.AddFile(f);
    }
    catch
    {
        // skip invalid files
    }
}

// Export
var counter = 0;
foreach (var patient in dcmDir.RootDirectoryRecordCollection)
{
    foreach (var study in patient.LowerLevelDirectoryRecordCollection)
    {
        foreach (var series in study.LowerLevelDirectoryRecordCollection)
        {
            foreach (var instance in series.LowerLevelDirectoryRecordCollection)
            {
                var dcmImg = new DicomImage(instance);     // is this correct ???
                using (var render = dcmImg.RenderImage())  // ERROR : DICOM dataset is missing pixel data element
                using (var img = render.As<Bitmap>())
                {
                    // TODO : fix naming pattern 
                    img.Save($"{counter++}.png");
                }
            }
        }
    }
}
```

**Expected behavior**
The `DicomImage `class should be able to fetch pixel data by given dataset or does the `DicomDirectory ` have a way to get raw bytes of instance to pass it to other classes?
filling the `(0004,1500) Refrence File ID` tag doesn't looks like solves anything either.
I don't know, Is there another way for it?

**Environment**
Fellow Oak DICOM version: 5.1.2
OS:  Windows11 x64
Platform: .NET 8.0

**Comment by gofal** [comment]
I guess you misunderstand the DicomDirectory. The class DicomDirectory is a wrapper around the DICOMDIR file (https://dicom.nema.org/dicom/2013/output/chtml/part10/sect_8.6.html).
If you have a whole fileset (e.g. a DICOM-CD or similar), then it would much too time-consuming to read all the files of the CD so that you can display to a user information about the content. This is, why there should be a file called DICOMDIR in the root directory. this only contains the most basic metadata. E.g. the Patientid, PatientName, DateofBirth of the patient contained in the fileset, and the list of StudyUIDs, Studydescriptions and Studydates, and for the series the SeriesDecriptions etc. And for the Images by default you only have the SopInstanceUID, the TransferSyntax, the SopClassUID and of course the ReferenceFileID (a.ka. Filename).

So when you are building up a FileSet (CD, USB-Stick, ...) you should build up a DicomDirectory and add all the DicomFiles (do not forget to pass the optional `referencedFileId` to the method `dcmDir.AddFile` with the filename and the relative subdirectory). And then you store the DicomDirectory with the filename "DICOMDIR" into the root path of the fileset.

On the other hand, when you get a fileset and want to present it in a viewer application, then all you have to do is to open the DICOMDIR file into a DicomDirectory instance. There you can iterate over the patient, study, series and even image instances and present the content to the user. If a user then selects an image, then get the `instance.GetString(DicomTag.ReferencedFileID)`, add it to the directory of the DICOMDIR file and then you have the filename to the DICOM file, which contains all the data including pixel data. You then can create a `DicomImage` instance from that filename and render the image.

**Comment by patachi** [comment]
@gofal I see, thanks.
