### ISSUE TITLE
dataset AddOrUpdate not find Encod args

### ISSUE THREAD

**Issue by wjm23714** [fo-dicom/fo-dicom#1786]
There are no encoding parameters

request.Dataset.AddOrUpdate(DicomTag.PatientName, "你好");

Name garbled after saving file

How to set encoding？

**Comment by wjm23714** [comment]
version fo-dicom 5.1.2

**Comment by mrbean-bremen** [comment]
The encoding should be done by the dataset encoding, taken from `SpecificCharacterSet`. If the character set cannot encode this string, it will get garbled. What encoding is set in your dataset?

**Comment by wjm23714** [comment]
> The encoding should be done using the dataset encoding, taken from `SpecificCharacterSet`. If the character set cannot encode this string, it will get garbled. What encoding is set in your dataset?

I can set the SpecificCharacterSet property to display normally, but in the previous version 4.0, AddOrUpdate was able to set character sets, so why not now.

4.0 code:
public DicomDataset AddOrUpdate<T>(DicomTag tag, Encoding encoding, params T[] values)
{
     return DoAdd(tag, encoding, values, allowUpdate: true);
}

The version of for-dicom v5 no longer has this encoding parameter

**Comment by mrbean-bremen** [comment]
An encoding parameter for an individual item does not make much sense, because all items must be encoded with the dataset encoding according to `SpecificCharacterSet`. Setting the encoding for an item to another value would produce invalid DICOM. I guess this was the reason it was removed.
If you have set `SpecificCharacterSet` in your dataset, and your data is still encoded incorrectly, then this may be a bug. See also my last comment in #1785.

**Comment by wjm23714** [comment]
Understood, thank you!

> An encoding parameter for an individual item does not make much sense, because all items must be encoded with the dataset encoding according to `SpecificCharacterSet`. Setting the encoding for an item to another value would produce invalid DICOM. I guess this was the reason it was removed. If you have set `SpecificCharacterSet` in your dataset, and your data is still encoded incorrectly, then this may be a bug. See also my last comment in #1785.
