### ISSUE TITLE
DicomJsonConverter throws for non-DicomElements

### ISSUE THREAD

**Issue by edespong** [fo-dicom/fo-dicom#1792]
**Describe the bug**
Trying to serialize a DICOM header that contains `DicomItem`s that are not `DicomElement`. This results in exceptions.

**To Reproduce**

Minimal program:

```using System.Text.Json;
using FellowOakDicom;
using FellowOakDicom.Serialization;
using JsonSerializer = System.Text.Json.JsonSerializer;

DicomDataset ds = new DicomDataset(new DicomOtherByteFragment(DicomTag.PixelData));
var jsonOptions = new JsonSerializerOptions {
    WriteIndented = true,
    Converters = { new DicomJsonConverter() }
};
string jsonArray = JsonSerializer.Serialize(ds, jsonOptions);
```

**Expected behavior**
To handle serialization gracefully, according to type. There are probably variations based on the subclass of DicomItem.

Basically, the code in the serializer is:

```
private void WriteJsonDicomItem(Utf8JsonWriter writer, DicomItem item, JsonSerializerOptions options) {
    writer.WriteStartObject();
    writer.WriteString("vr", item.ValueRepresentation.Code);

    switch (item.ValueRepresentation.Code) {
        case "PN":
               ......
        case "OB":
        case "OD":
        case "OF":
        case "OL":
        case "OV":
        case "OW":
        case "UN":
            WriteJsonOther(writer, (DicomElement)item);                <---- throws here
            break;
        case "FL":
```

There is no check anywhere that the `item` is actually a DicomElement.

**Environment**
fo-dicom 5.1.2

**Comment by gofal** [comment]
Thank you for reporting this bug!

**Comment by gofal** [comment]
@mrbean-bremen I am struggling with this, maybe you could help me with your knowledge from pydicom?
When parsing pixeldata, then fo-dicom distinguishes between "plain data", where the whole data is stored into a DicomOtherByte, or fragmented, where instead a DicomOtherByteFragment is instanciated and the data is split into fragments. The difference on how to tread the binary stream is well defined in Dicom standard.
But I do not find this difference in Dicom Json definition. So it seems even in case of fragmented data, the whole pixeldata has to be serialized as huge InlineBinary.
While for the serialization from DicomDataset to Json this would be fine, I wonder what to do when deserializing. When parsing a binary Dicom file, then the length of the DicomTag is important, if it is UndefinedLength (FFFFFFFF) then the following data is fragmented, else not. But the Json does not have a Length property. So this information is lost on serialization.

How does pydicom handle this? What is the json result, when serializing the file "CT1_J2KI" from fo-dicom.Tests/TestData?

**Comment by mrbean-bremen** [comment]
Interesting question - I have to admit that I haven't thought about this. My understanding so far was that each tag (including PixelData, even if it is encapsulated) is encoded as one single base64 encoded value. Admittedly, the cases I have heard of in practice have not used `InlineBinary` for Pixel Data, but send it separately via `BulkDataURI`.

The standard only says:
> If an attribute contains an "InlineBinary", this contains the base64 encoding of the enclosing attribute's Value Field.
There is a single InlineBinary value representing the entire Value Field, and not one per Value in the case where the Value Multiplicity is greater than one.

It says nothing about encapsulated data, at least as far as I can see. As far as I know, `pydicom` also handles it this way, e.g. as one opaque block of data.

**Comment by gofal** [comment]
Sure, I will be able to serialize the fragmented data as one block of data. But how does pydicom then handle the deserialization?

**Comment by mrbean-bremen** [comment]
As far as I can see, there is no special handling - it is just decoded from base64 and added as (byte array) value to the PixelData element, and handled as if read from a stream. 
There are some roundtrip tests (encoding in json, reading back from json and check that the datasets are equal), and this works also for compressed transfer syntaxes like JPEG2000. 
Note though that pydicom always handles PixelData as opaque blobs until it is needed to read, so the inner structure (e.g. the embedded sequences) are not considered at all at this level.

**Comment by gofal** [comment]
tried a lot, but still didn't manage to convert a jpeg2k compressed file with fragmented pixeldata into a json with available tools. some refused to convert. 
And dcmt converted everything but the pixeldata and wrote to the output, that json inlinebinary is not suppored for compressed pixeldata.
![image](https://github.com/fo-dicom/fo-dicom/assets/6769246/05005ca5-5ec1-45ac-8a85-baa273ad8ced)

I more and more get the impression, that by the DICOM standard DicomJson is intended for data exchange and similar to DICOM Media it is assumed that the data uns excanged uncompressed.

The currenst state, that an exception is throws, is not acceptable. As said, I try to serialize and deserialize the data in a compatible way, so that other applications still can work with the data that fo-dicom creates.
But other approaches would be, that 
- first the data should be transformed to an uncompressed transfersyntax and then Json-serialized, 
- or to skip the pixel data at all.

Any feedback is welcome!

**Comment by mrbean-bremen** [comment]
> I more and more get the impression, that by the DICOM standard DicomJson is intended for data exchange and similar to DICOM Media it is assumed that the data uns excanged uncompressed.

I don't think so. If the data is compressed, it would not be a good idea to uncompress it before transferring it over the wire, as that that may substantially increase the needed time. 

I would say that we go the `dcmtk` way, e.g. do not support `InlineBinary` for compressed data, but unfortunately, we also don't support `BuldDataURI` for that data, as it is handled the same way. 
If there is no easy way to handle this in fo-dicom, I would propose that fo-dicom shall not write the pixel data in this case and issue a respective warning or error (and adapt the documentation, of course), at least for the current version. 
This would at least avoid the crash.

Ultimately though this should be implemented, as I think this use case gets ever more common. I don't really know the code here, but I think the easiest way would probably be to write the pixel data into a buffer the same way it is written to a stream or file, and use that buffer for serialization. This would be memory intensive and not very efficient, so in the long run this should be optimized, for example by retaining the pixel data buffer as a byte array, and decoding (e.g. writing it into the fragment objects) only if needed. Or retain the pixel data buffer and have the fragment objects point to different offsets of the buffer. Or something else...
But this should probably be handled and discussed in a separate issue.

**Comment by gofal** [comment]
Had some interesting discussions about this topic. The summary is, that DICOM-standard is not clear about the encoding of native or encapsulated binary data. While in classical DICOM datasets the Value Length makes clear if the data is native (when the value length has some explicit value) or if the data is encapsulated (when the value length is Undefined Length (FFFFFFFF)), this information gets lost in DicomJson.

But from the Transfer Syntax is should be deductable how to interpret the pixel data, because various transfer syntaxes require that the pixeldata is encoded as native or as encapsulated. But this transfer syntax is not part of DicomJson. And furthermore this still causes problems when the pixel is not in root dataset (like it is in IconImageSequence).

So it should be no problem propably in most of the real live cases. But as said it is not clearly defined.

But then when it comes to compatilibily and how other applications or frameworks would deal with the data, if fo-dicom would encode the encapsulated data as InlineBinary.
I took a look at the two largest frameworks that I know, dcmtk and dcm4che. Both of them *do not support encapuslated pixeldata in InlineBinary*. Dcmtk refuses to write out InlineBinary and outputs a error message (see my comment above), and dcm4che produces something proprietary, instead of the single InlineBinary it create an Array called "FragmentData" and then dcm4che outputs one InlineBinary per fragment (this is in my optionion something, that I also would expect to find in DICOM standard definition).

This concludes me, that as long as the handling of encapsulated / fragmented Data in DicomJson is not exactly defined in DICOM standard and as long as other frameworks do not handle encapsulated data as InlineBinary well, the best thing that fo-dicom can do, is to avoid this situation by throwing an exception and asking the user to convert the DicomDataset to another format before serializing as DicomJson.

**Comment by edespong** [comment]
If I could write a CP for working group 27 I would, but I do not feel I have the in-depth knowledge that you have @gofal. Would you be open to writing a CP, or is it not worth the effort?

**Comment by mrbean-bremen** [comment]
I would probably bring that up in the [DICOM forum](https://groups.google.com/g/dicomforum) first (maybe also referencing this issue and #1864 which has some related discussion).
