### ISSUE TITLE
DicomValidation for VR PN Length

### ISSUE THREAD

**Issue by fepa73** [fo-dicom/fo-dicom#1820]
I wanted to point out odd behavior in setting a dicom tag value "PatientName" when the TAG value set exceeds 64 characters, 
returning me in the method of "dicomDataset.Add(new DicomPersonName(DicomTag.PatientName, dicomData.PatientLastName, dicomData.PatientFirstName))" a validation error.

In fact, according to the standard, the maximum length allowed for a PN TAG should be 64*5 (Surname^Name^PrefixName^MiddleName^SuffixName)

I'm probably making a mistake in setting up a PatientName and need some additional information in some method in the library.

Thank you so much for your support.

**Environment**
fo-dicom" Version="5.1.2"
.NET Core 8.0)

**Comment by mrbean-bremen** [comment]
Can you show the code that produces that error and the actual validation error?

**Comment by mrbean-bremen** [comment]
> In fact, according to the standard, the maximum length allowed for a PN TAG should be 64*5 

This is not completely true. A PN value can consist of up to 3 component groups (delimited by `=`), and each component group can contain up to 64 characters, so the maximum length is 3*64 characters. 
Each component group may consist of up to 5 components (delimited by `^`).

**Comment by gofal** [comment]
![image](https://github.com/user-attachments/assets/d1dc04e2-2a53-477c-88ee-1b226e3992d6)
Agree, 64 chars per component group

**Comment by gofal** [comment]
I opened a PR that contains a unittest, which tests the validation of PN lengths.
This issue is actually no bug, but the termas "Component" and "Component Group" are mixed up.
In fact, the "component group" may have a total max length of 64 characters and there may be 3 of these component groups.
But a single component (surename, given name, suffix, ..) may not have 64 chars with a total length of 5 times 64 for a component group.

So it seems there is nothing to fix here.
