### ISSUE TITLE
Strong-name key is not protected

### ISSUE THREAD

**Issue by jaime-olivares** [fo-dicom/fo-dicom#1821]
The SNK file should not be exposed in the source code. I suggest to regenerate and store it as a GitHub's project secret with base64 encoding.

The following sample YAML code would extract the secret and decode it during compilation time:

````
  - name: Prepare SN Key
    run: |
      echo "${{ secrets.STRONG_NAME_KEY }}" >FO-DICOM.Core/snk.base64
      certutil -decode FO-DICOM.Core/snk.base64 FO-DICOM.Core/fo-dicom.snk
````

**Comment by gofal** [comment]
Would you consider the strong name as security relevant?

As I understood, the strong name is to identify an assembly. The Global Assembly Cache uses the strong name to load the correct assembly. 

Since fo-dicom is open source, the content of the code is open, and it would be rather a feature, that someone can check out the source code, do some changes, customizations or enhancements that are not for public but only for personal need (e.g. we are running a version, that tracks the stream-position of tags when saving a dicom-file). Then using the available snk file the modified assembly can be used in production.

e.g. fo-dicom.coded is compiled with a reference to fo-dicom. if the snk was not public available, then noone could build his own version of fo-dicom and use your great codec library.

Or would you consider this as an issue with some risks? What are the downsides of having the snk public.
I am open to move the snk into github secrets, but I would like to be aware of the pros and cons.

**Comment by jaime-olivares** [comment]
Yes, I consider it relevant for certain use cases where there is a risk of breaching patients' personal information (PHI).

For example, I can create my own fork of fo-dicom and sign it with your SN key. The user will see the same PublicKeyToken, and .NET and Visual Studio will not notice that it is coming from a different source.
However, my malicious fork/forge of fo-dicom will send all the PHI to a third-party endpoint each time they open a DICOM file, for unknown reasons.

If somebody want's to create a fork of our codec, they just need to change its name and verify against a different token. I don't think it is good that the "improved" assembly contains the same name and signature being a different publisher. That breaks entirely the purpose of strong naming.

**Comment by edespong** [comment]
Microsofts guidance is found here: https://learn.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming

Especially relevant are:

✔️ CONSIDER adding the strong naming key to your source control system.

❌ DO NOT add, remove, or change the strong naming key.

And, the solution to the problem is to sign the assembly with a certificate (and keep the private key private):

Important! When the identity of the publisher of the code is desired, [Authenticode](https://learn.microsoft.com/en-us/windows-hardware/drivers/install/authenticode) and [NuGet Package Signing](https://learn.microsoft.com/en-us/nuget/create-packages/sign-a-package) are recommended. Code Access Security (CAS) should not be used as a security mitigation.

**Comment by gofal** [comment]
I completely agree to Erik and Microsofts guidance.
Strong naming is not intended to be a security feature, but only for identifying assemblies and solving the problem of having several versions on one system.
Sadly it consts money to sign assemblies, othewise I could sign the compiled dlls before publishing to nuget.

If some developer is concerned about security, then I strongly recommend, that they digitally sign their own application including the fo-dicom.core and fo-dicom.codec assembly that they use in that version. On execution, the application can check that the assemblies loaded are signed correctly - that prevents the application from using dlls that someone else just copies there.

So this kind of security in application should better be solved on application level by the developer building the application, not here in the library.

**Comment by jaime-olivares** [comment]
Closing this proposal as it doesn't seem to have traction.
