### ISSUE TITLE
Web application builder use SkipValidation()

### ISSUE THREAD

**Issue by Qeezy23** [fo-dicom/fo-dicom#1825]
I'm upgrade fo-dicom core 4.0.8 to fo-dicom 5.1.3, before upgrading I'm use:
`DicomValidation.AutoValidation = false;`

ChangeLog shows `DicomSetupBuilder.SkipValidation()` but I don't know how to use it.

My project is a NET 6 web application, this is how I builded:

`        public static void AddServices(this IServiceCollection services)`
`        {`
`            services.AddFellowOakDicom();`
`        }`
`        public static void UseConfig(this WebApplication app)`
`        {`
`            DicomSetupBuilder.UseServiceProvider(app.Services);`
`        }`

I need to know how to call SkipValidation() in web application.

Thanks.

**Environment**
Fellow Oak DICOM version: 5.1.3
OS: Windows 11 x64
Platform: NET 6

**Comment by gofal** [comment]
Agree, if using DicomSetupBuilder the syntax is not obvious.
What the static method `DicomSetupBuilder.SkipValidation(DicomSetupBuilder)` actually does, is that it sets other global static properites.

So what you could do now, is calling `DicomSetupBuilder.SkipValidation(null)` anywhere within the startup, e.g.

        public static void UseConfig(this WebApplication app)
        {
            DicomSetupBuilder.SkipValidation(null);
            DicomSetupBuilder.UseServiceProvider(app.Services);
        }

It would be more understandable for asp.net users if the SkipValidation would be an extension method of IServiceCollection instead of DicomSetupBuilder, or if the `.AddFellowOakDicom()` method would have some options parameters, where this can be set.

Suggestions, what would be the best place where to add the SkipValidation option, are welcome

**Comment by Qeezy23** [comment]
Thank you for your reply.
This is not a necessary option. I think it's just right to put it here. The problem is that I can't find this method in 5.1.3. 
Do I need to wait for the next release ?
![image](https://github.com/user-attachments/assets/ef6651ee-8c85-4c13-805d-e6981b7dcd71)

**Comment by Qeezy23** [comment]
There it is! It works fine.
`DicomValidationBuilderExtension.SkipValidation(null);`
