### ISSUE TITLE
fo-dicom returns default values for value-types when value does not exist in the dataset

### ISSUE THREAD

**Issue by MacL3an** [fo-dicom/fo-dicom#212]
If one runs `DicomDataset.Get<int>( [NonExistingValue] )`, fo-dicom will return 0 which could potentially lead to misinterpretations of the data. 
I think it would be better to encourage the use of nullables (e.g. `Get<int?>`) and throw an exception if someone tries to cast a value that does not exist in a dataset to a value-type.

**Comment by anders9ustafsson** [comment]
@MacL3an Thanks for posting the issue and PR #213. First of all, please note that the PR results in a number of unit test failures. Depending on personal preference, these failures might indicate whether the proposed change is feasible or not. 

Personally, I have not made up my mind up yet, I need to digest this suggestion for a little while longer. Maybe others have opinions to share about the proposal?

**Comment by anders9ustafsson** [comment]
I gave this some more thought, and I recollected that a similar question was brought up a while back in issue #10 . I am not implying that I have made up my mind yet :-) but I think it could be good to look at that issue as well for completeness.

**Comment by MacL3an** [comment]
Ah, interesting. I've updated my branch so that all but one unit test fails: 
https://github.com/MacL3an/fo-dicom/tree/pr/returning-empty-value-types

I actually noticed that several unit tests have test data that are missing Type 1-attributes and therefore should not work, but pass since the code returns the default-type for these missing attributes.

However, I'm working on an alternative solution. I'll try and complete it tomorrow!

**Comment by IanYates** [comment]
Yeah we've been done this road before with defaults, etc.

Being mindful of people relying on behaviour, and it's probably too soon to push out a v3, I can think of three approaches
a) Some global flag which, if set, causes exceptions to throw.  It's a bit of a global solution to a local problem
b) Add an "Exists()" method   (perhaps already there - I don't have the code open at the moment)
c) Add an alternate method called something like "DemandGet" or "MustGet" - I'm not a big fan of either name - which will throw exceptions instead of returning a default

**Comment by IanYates** [comment]
However, if everyone thought it was OK, we could just make the breaking change and start throwing.  This could be a variant on (a) above where we have the global flag, and default it to being set so exceptions are thrown unless someone specifically opts in to the old behaviour.

**Comment by anders9ustafsson** [comment]
@MacL3an I am a little bit on thin ice right now, but whether an attribute is Type 1 or not is context dependent, right? I don't have any example, but as far as I know the same tag could be used in different scenarios where it would be Type 1 in one scenario and Type 3 in the other, for example.

Of course the *fo-dicom* implementation could ultimately support validation on an IOD level, but it would be quite an undertaking to provide such functionality. For the time being, I think it has to be up to the consumer of the *fo-dicom* libraries to validate tags and values depending on context.

Having said that, the unit tests could of course be more consistent so that they do not use tags in a misleading way. If there are any obvious flaws, please feel free to point them out (and ideally include fixes in a PR).

**Comment by MacL3an** [comment]
Just created a new pull request (#213). I did some changes (it's not pretty), but I think everything should work now. The previous code created a defaultValue if the user hadn't provided it. With the new code a defaultValue is never created implicitly.

All unit tests pass except 3, which are all due to the same problem:
The image dataset in questions does not have PlanarConfiguration set. This is ok since the SamplesPixel is 1, but the code in Dicom.Imaging.Codec.Jpeg2000.cpp tries to get the value anyway. I tried setting PlanarConfiguration to a nullable, but then code doesn't compile and my C++ isn't good enough to fix it. One way of fixing it is changing PlanarConfiguration to return the default value, which is what the previous code did:
return Dataset.Get<PlanarConfiguration?>(DicomTag.PlanarConfiguration) ?? default(PlanarConfiguration);
However, I think this disguises the problem so I thought I would wait with checking that in to hear what you guys think. 

@anders9ustafsson yes you are correct that the Type is context dependent. However, in this case the testdata is correct, but fo-dicom crashes due to the code assuming the property should have a value, something the previous code concealed.

**Comment by Ed55** [comment]
Either I have a version mix or you break` Get<string>(tag, n)` on an existing tag but empty value.
Why should `Get<string>` on AccessionNumber present in the `Dataset` but with empty value not result in `String.Empty` but crash?
The issue seems to be that `(typeof(IByteBuffer).GetTypeInfo().IsAssignableFrom(typeof(T).GetTypeInfo()))` is not true for `EmptyBuffer` and T is string ?!

**Comment by IanYates** [comment]
@Ed55 - that does indeed sound like a bug.  I'd expect String.Empty in that case.  Should we start a new issue since @anders9ustafsson has merged this already?  Do you have a sample DICOM file with that (although it wouldn't be too hard to reproduce, just asking in case there's something else in the file that perhaps is mucking with parsing state and that leads to the eventual issue)?

**Comment by anders9ustafsson** [comment]
@Ed55 I will check more closely into this issue very soon, and file a bug report if necessary. Thanks for reporting!

**Comment by anders9ustafsson** [comment]
@Ed55 @IanYates Consider this: *Accession Number* is present but empty. What should these calls result in? `dataset.Get<string>(DicomTag.AccessionNumber)`? dataset.Get<int>(DicomTag.AccessionNumber)`?

**Comment by Ed55** [comment]
I would expect that
`dataset.Get<string>(DicomTag.AccessionNumber)` would return String.Empty;
`dataset.Get<int>(DicomTag.AccessionNumber)` would throw (based on above's decission);
`dataset.Get<int?>(DicomTag.AccessionNumber)` would return default(int?).

My quick hack, is placed just beneath `if (typeof(IByteBuffer).GetTypeInfo().IsAssignableFrom(typeof(T).GetTypeInfo())) return (T)(object)element.Buffer;`

                if (element.Buffer is EmptyBuffer)
                {
                    if (element.ValueRepresentation.ValueType.GetTypeInfo().IsAssignableFrom(typeof(T).GetTypeInfo()) && typeof(string).GetTypeInfo().IsAssignableFrom(typeof(T).GetTypeInfo()) )
                    {
                        return (T)(object)String.Empty;
                    }
                    else if (typeof(T).GetTypeInfo().IsValueType && typeof(T).GetGenericTypeDefinition() ==  typeof(Nullable<>))
                    {
                        return default(T);
                    }
                }
but may you find a better solution.

**Comment by IanYates** [comment]
@Ed55 - that seems reasonable
