### ISSUE TITLE
Log4net event logging config not working with AssemblyInfo.cs XMLConfigurator.

### ISSUE THREAD

**Issue by selflessFlash** [fo-dicom/fo-dicom#244]
### Expected behavior
Would like the AssemblyInfo.cs  XmlConfigurator to configure log4net using the xml config file.
**AssemblyInfo.cs**
```
// Copyright (c) 2012-2016 fo-dicom contributors.
// Licensed under the Microsoft Public License (MS-PL).
using log4net.Config;
using System.Reflection;
using System.Runtime.InteropServices;
[assembly: AssemblyTitle("ConsoleTest")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]
// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("cbfa0780-5726-437b-8f4a-e82964d6051f")]
[assembly: XmlConfigurator(ConfigFileExtension = "Logger", Watch = true)]
```

### Actual behavior
The XmlConfigurator is not recognized and log4net is not initialized with the config file for formatting and appenders etc...

### Steps to reproduce the behavior
Consider that you have your log4net config in a file called **ConsoleTest.exe.Logger**
```
<?xml version="1.0" encoding="utf-8"?>
  <log4net>
    <appender name="RollingfileAppender" type="log4net.Appender.RollingFileAppender">
      <file value="C:\temp\ConsoleTest.log" />
      <appendToFile value="true" />
      <rollingStyle value="Size" />
      <maxSizeRollBackups value="8" />
      <maximumFileSize value="2MB" />
      <staticLogFileName value="true" />
      <filter type="log4net.Filter.LevelRangeFilter">
        <levelMin value="DEBUG" />
        <levelMax value="FATAL" />
      </filter>
      <layout type="log4net.Layout.PatternLayout">
        <conversionPattern value="%date %level %thread %logger{1} - %message%newline" />
      </layout>
    </appender>
    <appender name="SMTPAppender" type="log4net.Appender.SmtpAppender">
      <threshold value="DEBUG" />
      <to value="some.one@somewhere.com"/>
      <from value="console.test@somewhere.com"/>
      <subject type="log4net.Util.PatternString" value="%property{log4net:HostName} Error: %appdomain" />
      <smtpHost value="smtp.host.com"/>
      <port value="25" />
      <bufferSize value="10" />
      <lossy value="true" />
      <evaluator type="log4net.Core.LevelEvaluator">
        <threshold value="ERROR" />
      </evaluator>
      <layout type="log4net.Layout.PatternLayout">
        <conversionPattern value="%date %-5level %logger - %message%newline%newline" />
      </layout>
    </appender>
    <root>
      <level value="DEBUG" />
      <appender-ref ref="RollingfileAppender" />
      <appender-ref ref="SMTPAppender" />
    </root>
  </log4net>
```
**app.config**
```
<configuration>
. . .
  <appSettings>
<!--diagnostics-->
    <add key="log4net.Internal.Debug" value="true" />
  </appSettings>
  <system.diagnostics>
    <trace autoflush="true">
      <listeners>
        <add name="textWriterTraceListener" type="System.Diagnostics.TextWriterTraceListener"
          initializeData="C:\\temp\\log4NetDiagnostics.log" />
      </listeners>
    </trace>
  </system.diagnostics>
. . .
</configuration>
```
This is the workaround I came across.
Add these lines to the **app.config**
```
<appSettings>
<!--Override the unrecognized XmlConfigurator-->
    <add key="log4net.Config" value="ConsoleTest.exe.Logger"/>
    <add key="log4net.Config.Watch" value="True"/>
```
**Program.cs**
```
// Copyright (c) 2012-2016 fo-dicom contributors.
// Licensed under the Microsoft Public License (MS-PL).
namespace ConsoleTest
{
    using System;
    using System.IO;
    using Dicom;
    using Dicom.Log;
    using Dicom.Network;
    internal class Program {
            try {
                LogManager.SetImplementation(Log4NetManager.Instance);
                Logger foDicomLogger = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType.ToString());
                foDicomLogger.Info("Info Test");
```

### fo-dicom version and OS/platform
fo-dicom ver 2.0.2
Win 7 64bit
Visual Studio 2015 Pro.

### From Gitter April 1, 2016
**anders9ustafsson 01:12**
@selflessFlash *I have to admit that I have very little experience with log4net. I implemented the connector pretty much like the NLog and MetroLog implementations. Are you unable to apply the config file due to limitations in the setup? In that case, feel free to post an issue and we'll try to correct it expediently.*

**Comment by anders9ustafsson** [comment]
@selflessFlash Have you verified that this issue is definitely *fo-dicom* specific? It seems strange that the *fo-dicom* Log4Net adapter should *not* work when you use the `[XmlConfigurator]` attribute, but work when you place the override settings in *app.config*?

Can you please double-check that `[XmlConfigurator]` works as intended for the *Log4Net* version you are running when used in a non-*fo-dicom* application.

**Comment by anders9ustafsson** [comment]
OK, I have now investigated this in more detail. I think the issue is summarized in the *log4net* manual on [Configuration](http://logging.apache.org/log4net/release/manual/configuration.html), section *Configuration Attributes*:

> Using attributes can be a clearer method for defining where the application's configuration will be loaded from. However it is worth noting that attributes are purely passive. They are information only. Therefore if you use configuration attributes you must invoke log4net to allow it to read the attributes. A simple call to LogManager.GetLogger will cause the attributes on the calling assembly to be read and processed. __Therefore it is imperative to make a logging call as early as possible during the application start-up, and certainly before any external assemblies have been loaded and invoked.__

If you put the `[XmlConfigurator]` declaration in the *AssemblyInfo.cs* file, it appears like the assembly loading completes too early, and the declaration is ignored. 

On the other hand, if you move the `[XmlConfigurator]` declaration to the top of the *Program.cs* file (after the `using` statements), the `[XmlConfigurator]` configuration is properly accounted for!

Another alternative is to call either of the `XmlConfigurator` static methods, `Configure` or `ConfigureAndWatch` before calling `Dicom.Log.LogManager.SetInstance`.

The `[XmlConfiurator]` attribute limitation is not something we can easily circumvent by changing the *fo-dicom.Log4Net* adapter, so if you @selflessFlash can confirm that my proposed workaround is sufficient my recommendation is that we instead add this information to a *Logging* wiki page.

**Comment by anders9ustafsson** [comment]
I stand corrected! If I add a static constructor to `Log4NetManager`, which makes a dummy call to `log4net.LogManager.GetLogger`, the `[XmlConfigurator]` attribute **can** be accounted for even if it is residing in *AssemblyInfo.cs*. 

I'll implement the change, but since there are already multiple easy workarounds I don't think it deserves a 2.0.x bugfix release. I'll add the fix to the regular *development* branch instead for future inclusion in 2.1.0. OK?

**Comment by selflessFlash** [comment]
I'm sorry I missed your investigative comments. I'll check my setting and make sure I'm getting mail from github. I wish I'd been there to collaborate with you on this. Kindest Regards.

**Comment by hoshiyarRawat** [comment]
For the Console application. we can use to configure using c# code

         string configFilePath = string.Empty;
          string  configFilePath = @"/log4net.config";
  
            XmlDocument log4netConfig = new XmlDocument();
            log4netConfig.Load(File.OpenRead(configFilePath));

            var repo = LogManager.CreateRepository(
                Assembly.GetEntryAssembly(), typeof(log4net.Repository.Hierarchy.Hierarchy));

            log4net.Config.XmlConfigurator.Configure(repo, log4netConfig["log4net"]);
