### ISSUE TITLE
ImageDisposableBase implicit destructor missing (may cause memory leak)

### ISSUE THREAD

**Issue by hdesouky** [fo-dicom/fo-dicom#322]
The class is not implementing the destructor. This will cause memory leaks when this object is not disposed and garbage collector releases it. The Dispose method should be called from default destructor

**Comment by IanYates** [comment]
What unmanaged resource is it holding?

The `PinnedIntArray` has its own finalizer / destructor so it's handled.
The various `TImage` implementations also have finalizers.

Dispose() will avoid the need for these finalizers to be called and save time, but if a user forgets to dispose the ImageDisposableBase instance then, when it's not being referenced and the GC eventually runs, both `TImage` and `PinnedIntArray` will find themselves into the finalizer queue and eventually be reclaimed.  Adding a finalizer to ImageDisposableBase doesn't buy us anything.

Of course I could be missing something as I've just been reading the relevant code in GitHub rather than actually cracking it open in VS.

**Comment by anders9ustafsson** [comment]
I am no expert in unmanaged resource handling, but @IanYates 's reasoning makes sense to me. 

@hdesouky What do you think?

**Comment by hdesouky** [comment]
I agree, wit @IanYates but i get used to create finalizers for any class has members of disposable classes.
However i will close the issue if such style is not needed for this project.

Please confirm to proceed to the closure

**Comment by anders9ustafsson** [comment]
It is good to know that there is (probably) no memory leak with the current solution, as @IanYates points out. On the other hand, it still makes a good practice to implement the destructor in an `IDisposable` class, as @hdesouky points out.

So in conclusion I think we should proceed and implement the destructors, not because it is required but because it is good practice.

**Comment by IanYates** [comment]
No worries - so long as we do the SuppressFinalize call there's no harm to have the destructor.  Usually if a see a destructor it just makes me think there's something unmanaged owned specifically by the class when that isn't strictly the case here.  I don't feel at all strongly about it though so 👍 👍 to adding the destructor.
