### ISSUE TITLE
Consistently asynchronous networking API

### ISSUE THREAD

**Issue by anders9ustafsson** [fo-dicom/fo-dicom#331]
Currently, the networking API is primarily synchronous, primarily to ensure backwards compatibility. However, it would make sense if for example the `protected` `Send...` methods in `DicomService` and analogously, the methods in `IDicomServiceUser` and the various provider interfaces were declared asynchronous.

API renaming could (and should!) coincide with a refactoring of particularly the `DicomService` and `DicomClient` classes to ensure a clearer and more reliable networking implementation.

**Comment by IanYates** [comment]
This would be great.  I see you've got v4.0 as the milestone.  What sort of timeframe did you have in mind for v3 or v4?  If v3 is still a month or two away then we could get something in ahead of its release...
I guess I should get on Gitter more often and actually discuss this rather than asking on random issues :)
