### ISSUE TITLE
MR Philips SOP Class unknown

### ISSUE THREAD

**Issue by mginformatica** [fo-dicom/fo-dicom#355]
The MR Philips send this 3 SOP Class:
Private MR Spectrum Storage = 1.3.46.670589.11.0.0.12.1
Private MR Series Data Storage = 1.3.46.670589.11.0.0.12.2
Private MR Examcard Storage = 1.3.46.670589.11.0.0.12.4
fo-dicom declare it unknown.

When the MR send me 325 images I receive only 17 images with fo-dicom.
If the MR send the images to the pacs, workstation or cd burner not there is the problem.

This is the log:
[log.txt](https://github.com/fo-dicom/fo-dicom/files/480448/log.txt)

Thank you
### Steps to reproduce the behavior

Receive images from MR Philips
### fo-dicom version and OS/platform

2.0.2 and 3.0.0.beta4

**Comment by anders9ustafsson** [comment]
@mginformatica As also others have reported, there are still some issues with the re-factored networking implementation. We will investigate and try to fix this for the 3.0 release.

**Comment by anders9ustafsson** [comment]
@mginformatica Do I understand correctly that you are trying to send these images to the *C-STORE SCP* server?

Since the listed storage SOP classes are not known to *fo-dicom* (they are not part of the current DICOM standard), any attempt to store them will fail. You will need to explicitly define these SOP classes and configure the C-STORE SCP application to recognize them.

Unfortunately, there is currently no functionality for manually adding private SOP Class UIDs to the list of known UIDs. I will implement functionality to support this feature.

**Comment by anders9ustafsson** [comment]
@mginformatica If you could provide us with an anonymized DICOM file of any of the above types for testing purposes, that would be terrific.

**Comment by mginformatica** [comment]
Yes, the MR Philips send to C-STORE SCP.
If the MR send to the PACS (http://www.pacsone.net talk of the philips SOP class and solve the problem,  http://www.pacsone.net/forum/viewtopic.php?t=1205) and then PACS send to C-STORE SCP I haven't problem.
I think the PACS change DICOM file, so I haven't the original philips dicom file.
I must ask to my customer if can save direct from the MR to a file.

Can be a dicom movie that is not read from C-STORE SCP?

**Comment by mginformatica** [comment]
Thank you

**Comment by anders9ustafsson** [comment]
Yes, I noticed in the PACSONE forum that they had resolved the problem there, by adding those SOP storage classes to the list of known SOP classes, right?

Anyway, I should hopefully be able to simulate an object with that SOP class, so it should work without a test file as well.

**Comment by mginformatica** [comment]
In some log I see that SOAP class has benn recognized. But I do not know / I see more.  
Ok. I hope my customer send me a file this week.

Thank you

**Comment by anders9ustafsson** [comment]
@mginformatica There is now a PR #387 which will soon be accepted into the repository. It allows you to register private SOP classes so that they can be recognized e.g. by a *fo-dicom* based storage server. For an example, see the following unit test `DicomServerTest.Send_PrivateRegisteredSOPClass_SendSucceeds`.

**Comment by kundanashish** [comment]
I am still facing this issue in version 5. Do I need to do any code explicit to handle this?
somebody pls help.

**Comment by mrbean-bremen** [comment]
As stated in the previous comment, you need to register your private SOP class. Did you do this? You can check the test code in the mentioned PR for an example how to do this.
