### ISSUE TITLE
Why fo-dicom doesn't support  RGBA format.

### ISSUE THREAD

**Issue by fjkfjk** [fo-dicom/fo-dicom#396]
### Expected behavior
PhotometricInterpretation support RGBA format.

### Actual behavior
![image](https://cloud.githubusercontent.com/assets/12387500/21976723/213785c2-dc0e-11e6-9030-a557ebef9069.png)

### fo-dicom version and OS/platform
windows wpf

**Comment by fjkfjk** [comment]
I am developing a Ultrasound device and should support dicom. I choose fo-dicom but find this libiary does not support RGBA image format, Should I add it by myself? what should I note that if I do it?

**Comment by anders9ustafsson** [comment]
@fjkfjk According to the [current](ftp://medical.nema.org/medical/dicom/current/output/html/part03.html#sect_C.7.6.3.1.2) DICOM Standard, ARGB photometric interpretation is a retired term.

Since it is retired, and since the alpha component can easily be represented in RGB via pre-multiplication, I would not consider adding ARGB support being a high priority.

Of course, if there is strong demand from the community that we **do** add it, I am of course willing to re-consider.

**Comment by fjkfjk** [comment]
@anders9ustafsson Well,I just found that after I've asked this question. I will transfer my pixel data to RGB. Many thanks for you! :)(This libiary is really excellent! )
