### ISSUE TITLE
Binding Redirect possibly required

### ISSUE THREAD

**Issue by IanYates** [fo-dicom/fo-dicom#40]
I finally got around to using the NuGet package in my web application and have spent a little while trying to get things working properly around codec loading.

I was getting a reflection type load exception where the loader error property of that exception indicated that Dicom.dll version 1.0.0.39 couldn't be find.  That's true - Dicom.dll is now at 1.1.0.0.

Adding 
```
      <dependentAssembly>
        <assemblyIdentity name="Dicom" publicKeyToken="3a13f649e28eb09a" />
        <bindingRedirect oldVersion="0.0.0.0-1.1.0.0" newVersion="1.1.0.0"/>
      </dependentAssembly>
```
to my web.config solved that issue.

Many NuGet packages try to add this binding redirect automatically.  Should we think of doing the same?  (I'm not sure how this is done - probably some PowerShell?).  If not then I'll at least add this to the wiki.

Happy to hear thoughts of others

**Comment by IanYates** [comment]
Further to this, I have at least one third-party assembly in my web site's bin folder where, if I just let fo-DICOM try to create its DirectoryCatalog using the default path, I get an error where ReSharper's annotation's DLL is apparently required (due to that third-party library referencing it).  

This isn't fo-DICOM's fault per-se but only surfaced via fo-DICOM's default DirectoryCatalog creation.  To avoid confusion I've stuck the native DLLs into a subfolder off my bin folder again.

Applying a smarter default if the search parameter to LoadCodecs is null - treating it as Dicom.Native*.dll rather than just not supplying anything to the DirectoryCatalog's constructor, might do the trick too

**Comment by anders9ustafsson** [comment]
> I was getting a reflection type load exception where the loader error property of that exception indicated that Dicom.dll version 1.0.0.39 couldn't be find. That's true - Dicom.dll is now at 1.1.0.0.

I am a little inexperienced when it comes to web applications; why is the application expecting a specific 1.0.39 version? Is this configured somewhere?

> Many NuGet packages try to add this binding redirect automatically. Should we think of doing the same?

Do you have an example of a NuGet package where this is done? In that case it should be possible to figure out how to solve this issue for *fo-dicom* as well.

Is this a critical issue for 1.1.0, or would it suffice to write a wiki page about it?

> Further to this, I have at least one third-party assembly in my web site's bin folder where, if I just let fo-DICOM try to create its DirectoryCatalog using the default path, I get an error where ReSharper's annotation's DLL is apparently required (due to that third-party library referencing it).

As I also mention in PR #41 I basically think the extra `try`-`catch` protection and logging you are adding makes sense. However, I am unsure about the validity of replacing `search = null` with the `Dicom.Native*.dll` string, as this action is taken via the static constructor as soon as the `DicomTranscoder`class is accessed. Isn't it so that `LoadCodecs` is declared `public` primarily to allow loading of codecs from third-party DLLs that are *not* included in the default *fo-dicom* distribution?

**Comment by anders9ustafsson** [comment]
I made some Googling on biding redirect, and found some valuable information:

* [Package Manager Console Powershell Reference](https://docs.nuget.org/consume/package-manager-console-powershell-reference)
* [NuGet versioning Part 3: unification via binding redirects](http://blog.davidebbo.com/2011/01/nuget-versioning-part-3-unification-via.html)
* [Updating Assembly Redirects with NuGet](http://weblog.west-wind.com/posts/2014/Nov/29/Updating-Assembly-Redirects-with-NuGet)
* [Could not load file or assembly… NuGet Assembly Redirects](http://blog.maartenballiauw.be/post/2014/11/27/Could-not-load-file-or-assembly-NuGet-Assembly-Redirects.aspx)

If I interpret these articles correctly, the binding redirect is normally applied automatically on the *app.config* and *web.config* files when installing a *NuGet* package to a VS project. It is not clear if the `Add-BindingRedirect` command is executed when updating a *NuGet* package. If not, you may run the PowerShell command `Get-Project –All | Add-BindingRedirect` from the Package Manager console to automatically update all *.config* files in your solution.

Since I don't have any web project myself to test this on, I cannot immediately verify the correctness of these assumptions. @IanYates maybe you can give it a try and see if the above works for you? If it does, I could add a wiki page with this information.

**Comment by anders9ustafsson** [comment]
@IanYates Have you had a chance to look at the alternative solutions for assembly binding redirect that I listed in my previous comment? Does it work? If you can confirm that it doeswork, I will add a wiki page about it

**Comment by IanYates** [comment]
Hi @anders9ustafsson  - no I haven't sorry.  It's been a crazy couple of weeks.  
I noticed on my sidekick's dev machine, who is using the NuGet version of fo-DICOM, that he gets a warning about our project being in AnyCPU.  I understand why this is the case, but we do ship our web app AnyCPU (some customers still have Server 2008 x86 *shudder*) and have no real problems with having both of the native DLLs present.

Anyway, I'll check on the binding redirects this week.

**Comment by anders9ustafsson** [comment]
Hi @IanYates , no hurry, I only thought I should follow-up before I wrote something to the wiki.

Regarding the *Any CPU* issue, you are absolutely right, it should not matter if both native DLLs are present. The *NuGet* build script is only a convenience so that native DLLs should not have to be copied manually. But a simple workaround for the *Any CPU* build configuration is to manually add the native DLLs to the project e.g. as "Content" items (*not* references), and set the files to be copied to the output directory upon build. That would make the build script redundant.

**Comment by anders9ustafsson** [comment]
@IanYates I have added a section on the wiki, [here](https://github.com/fo-dicom/fo-dicom/wiki/NuGet-installation-notes#assembly-binding-redirect). If the guidelines do not work, we can remove the text at any time.
