### ISSUE TITLE
Proposal: Dataset anonymization

### ISSUE THREAD

**Issue by jaime-olivares** [fo-dicom/fo-dicom#410]
I am currently working on an anonymization class. This entry is for discussing the features before filing a PR.
Initially I built a list of sensitive tags and some random actions for them (see the attachment) and it is already anonymizing without exceptions. An element can be blanked, removed or replaced with other value.

After that, I realized there is a formal specification for "de-identifying" Dicom files called **"DICOM Supplement 142"** (see http://www.dclunie.com/papers/D2_1045_Clunie_Deidentification.pdf), so I will start over with a more formal "de-identification profile" that I will put in an XML or JSON file rather than hardcoding it, so users can use a different profile according to their specific needs.

**Attached draft source code:** [Anonymizer.cs.zip](https://github.com/fo-dicom/fo-dicom/files/736405/Anonymizer.cs.zip)

Please feel free to comment.

**Comment by jaime-olivares** [comment]
I am attaching a more Dicom compliant version of the anonymizer. Still work in progress, but already functional.

The source code has been compiled using VSCode/.net core, but it can be easily ported to Visual Studio 201x.

Attachment: 
[Anonymizer.zip](https://github.com/fo-dicom/fo-dicom/files/758862/Anonymizer.zip)

**Comment by anders9ustafsson** [comment]
Many thanks, @jaime-olivares! Is the code portable enough to build for PCL profile 111 as well?

**Comment by jaime-olivares** [comment]
The code is plain old C#. I think the unique risky functionality is  `System.Reflection.Type.GetConstructor()`, but I think that should work as well.

**Comment by anders9ustafsson** [comment]
OK. You should probably use `TypeInfo.GetConstructor()` instead for maximum portability, but that's just a guess.

**Comment by anders9ustafsson** [comment]
@jaime-olivares I have taken a quick look at the anonymizer, and it looks like great and comprehensive work! Many thanks for providing it!

Since it is not interfering with any other source code I am considering to include it in the 3.0 release, provided you consider it ready enough by now.

In line with the other classes, I think I will rename the class to `DicomAnonymizer`. Any problems with that?

I am also thinking that it would be a good thing to be able to maintain the original DICOM dataset, so rather than having `Anonymize` modify the incoming dataset it would clone the incoming dataset and return an anonymized copy. What do you think of that?

Also, how to handle a DICOM file with meta information? If the SOP Class UID is modified this needs to be reflected in the file meta info, right?

**Comment by jaime-olivares** [comment]
Hi Anders, thanks for considering this proposal.

Regarding the class rename, there is no problem. I will rename it in the next delivery.

About maintaining the original dataset, it sounds reasonable, but in case of a big image (let's say a mammography of 1Gb+) I may generate a big memory consumption. What about making it optional?

I am not sure about the meta information, I can only see the (0002,0003) tag changed. Not sure about the implications; can you provide a concrete case?

I will keep working on this class for few more days. Hope to be on time. I suggest to label it as a "preview" in order to avoid too much expectations and encourage other's contributions.

**Comment by anders9ustafsson** [comment]
@jaime-olivares Sorry, I of course meant SOP Instance UID. I have changed that in my previous comment as well to avoid confusion. Yes, corresponding to (0002, 0003) in the File Meta Information header.

Regarding the API, I agree, optionality is the way to go. I am thinking something like this:

    void AnonymizeInPlace(DicomDataset)
    DicomDataset Anonymize(DicomDataset)
    void AnonymizeInPlace(DicomFile)
    DicomFile Anonymize(DicomFile)

where the `Anonymize` methods could be implemented something like this:

    {
      var clone = dataset.Clone();
      AnonymizeInPlace(clone);
      return clone;
    }

In the implementation of `AnonymizeInPlace(DicomFile file)`, I suppose this should do?

    {
      AnonymizeInPlace(file.Dataset);
      if (file.FileMetaInfo != null)
      {
        file.FileMetaInfo.MediaStorageSOPInstanceUID = file.Dataset.Get<DicomUID>(DicomTag.SOPInstanceUID);
      }
    }

**Comment by jaime-olivares** [comment]
@anders9ustafsson  I have created the PR #437 incorporating your suggestions.

**Comment by anders9ustafsson** [comment]
@jaime-olivares I have now pulled the request #437, many thanks for this invaluable contribution!

If you look more closely, I have made some adjustments; the most prominent being that I moved the main functionality from `PerformAnonymization` to `AnonymizeInPlace(DicomDataset)`. As I see it, it is sub-optimal to have a method (`PerformAnonymization`) where you in practice ignore the return value in half of its invocations. Better to do the cloning inside the methods really using that (the `Anonymize` overloads) and clearly return the clones from these methods only.

I have also made some rearrangements and clean-ups, in particular the section with date/time changes were originally never reached since the corresponding classes inherit from `DicomStringElement` which was handled completely earlier in the `BlankElement` method.

I have also adapted the code to use portable constructors with `GetTypeInfo` where appropriate, and explicitly creating a `char` array from a string, since in PCL and newer platforms `string` is not inheriting from `char[]`.

If you have any major concerns with my modifications, please don't hesitate to let me know.

**Comment by Zaid-Safadi** [comment]
Thank you @jaime-olivares for implementing this feature and @anders9ustafsson for adding it. This is really nice work!

I've wanted to include an anonymizer when storing images to the DICOMcloud server and this seems to fit the need exactly. I'll be looking to add it soon and can let you know once it is online to see it live :)

**Comment by Zaid-Safadi** [comment]
@jaime-olivares just wanted to let you know that I integrated the anonymizer -and it is working nicely- in the DICOMcloud. 

If you like to try it out, you can use the [live demo](http://dicomweb.azurewebsites.net/) which automatically anonymize on store. 👍

**Comment by siddharthasaha9** [comment]
@Zaid-Safadi I want to anonymize all the DICOM files for a particular Study. Can you please guide me how can I do this?
