### ISSUE TITLE
DicomFile.Dataset.Get<string>(DicomTag.PatientID) - \0 terminator left in string

### ISSUE THREAD

**Issue by OlegusTT** [fo-dicom/fo-dicom#457]
### Expected behavior
"0522c0001_Run374510204_Copy01"

### Actual behavior
"0522c0001_Run374510204_Copy01\0"
At the end \0 terminator is returned as part of String.

### Steps to reproduce the behavior
Use uneven length PatientID from example: "0522c0001_Run374510204_Copy01".
0 padding to even length is correct within DICOM file.
But I would expect, that Get<String> would trim ending \0 symbol.

### fo-dicom version and OS/platform
v.3.0.0
windows
[000000.zip](https://github.com/fo-dicom/fo-dicom/files/811709/000000.zip)

**Comment by jaime-olivares** [comment]
Related discussion: https://groups.google.com/forum/#!topic/fo-dicom/H8ZNBtg32ug

**Comment by anders9ustafsson** [comment]
Please see #359. Since the `/0` character is not part of the supported character repertoire e.g. for person names, we have decided to *not* trim this character from strings, with the notable exception of mapping enum values during parsing.

In general, DICOM expects the space character when strings are trimmed to even length.
