### ISSUE TITLE
Bug DicomImage Scale whith Overlay

### ISSUE THREAD

**Issue by maikel87** [fo-dicom/fo-dicom#46]
If you load a DicomImage that have overlays and scale the DicomImage, por example to 0.5, the library have a bug

**Comment by anders9ustafsson** [comment]
Thanks for reporting. Would it be possible for you to provide a DICOM file where you have observed this issue, and could you also please explain in more detail what you consider wrong?

Best regards,
Anders @ Cureos

**Comment by maikel87** [comment]
Hi Anders, where i can send you the dicom file?
The issue is in "OverlayGraphic" class, method "Render", i think that when we scale the DicomImage, the overlay must be scaled also, sorry by my english.
best regards

**Comment by anders9ustafsson** [comment]
Thanks, @maikel87. To upload a DICOM file, you can change the extension of the file to an image extension (.png, .bmp or .jpg) and add it to the issue or comment like a regular image file.

**Comment by maikel87** [comment]
![overlays](https://cloud.githubusercontent.com/assets/7071743/8755421/cedcccd6-2c98-11e5-8e63-b1d96f1022f1.jpg)
Hi, here a Dicom File with overlays

**Comment by anders9ustafsson** [comment]
@maikel87 Are you using the `DicomImage.RenderImage` or the `DicomImage.RenderImageSource` method to render the image?

**Comment by anders9ustafsson** [comment]
@maikel87 As far as I can tell, the *overlays* image scale as expected when the Windows Forms based `DicomImage.RenderImage` method is used, for example in the *DICOM Dump* tool. When I use the WPF based `DicomImage.RenderImageSource` though, the image does **not** scale. This is because, incorrectly, scaling is not applied in this method.

The scaling (and "no scaling") applies to the entire image; I have not observed that specific parts (overlays) of the image are scaled while others are not. Could you please confirm that this is also the behavior that you are observing, @maikel87, i.e. the image is not scaled **at all** when you are using `DicomImage.RenderImageSource`.

I intend to add the scaling functionality to `DicomImage.RenderImageSource` as soon as possible.
