### ISSUE TITLE
DicomDataset.Get<string> on empty tag should not throw

### ISSUE THREAD

**Issue by saviok04** [fo-dicom/fo-dicom#474]
### Expected behavior
The return value of DicomDataset.Get<string> when the requested tag exists without data in the dataset, should be an empty string

### Actual behavior
A DicomDataException, message "Element empty or index: 0 exceeds element count: 0" is thrown.

### Steps to reproduce the behavior
Create a dataset ds and add a tag with no data: ds.Add(DicomTag.XXX, (string)null)
Try to retrieve the empty data array: ds.Get<string>(DicomTag.XXX)

### fo-dicom version and OS/platform
3.0.1 / Windows 10/ .Net Framework 4.5.2

**Comment by saviok04** [comment]
It was working on fo-dicom 2.0.2. Started getting the exception after I updated to 3.0.1.

**Comment by anders9ustafsson** [comment]
@saviok04 This is by design, to ensure that `DicomDataset.Get<T>` returns a consistent result when a tag is present but empty.

In the case where `T` is a `string`, it might make some sense to return an empty string. On the other hand, if `T` is an `int`, what should the return value from an empty tag be then? For clarity, instead of returning the type default value, we are now consistently throwing in 3.0 and onwards.

What you can do is to change the `Get` method to return a string *array*  instead, i.e. `DicomDataset.Get<string[]>`. In this case, if the tag is present but empty, the `Get` method will return an empty string array.

**Comment by saviok04** [comment]
Makes sense. Thanks for that.
