### ISSUE TITLE
Cannot parse dicom files if the last tag is a private sequence containing only empty sequence items

### ISSUE THREAD

**Issue by Thunderstriker** [fo-dicom/fo-dicom#487]
### Expected behavior
fo-dicom should be able to parse the file

### Actual behavior
following exception is thrown
"Unable to read beyond the end of the stream."

### Steps to reproduce the behavior
open attached file in DICOM Dump
[177dc98a-d1d1-11e5-9db0-8e3eb9235903.zip](https://github.com/fo-dicom/fo-dicom/files/841361/177dc98a-d1d1-11e5-9db0-8e3eb9235903.zip)

### fo-dicom version and OS/platform
3.0.1

**Comment by Thunderstriker** [comment]
proposed fix:
pass along sequence length to the IsPrivateSequenceBad function in DicomReader.cs
then replace the while loop with this:
 ```
                    uint count = length;
                    while (new DicomTag(source.GetUInt16(), source.GetUInt16()) == DicomTag.Item)  
                    {
                        if (source.GetUInt32() > 0)
                            break;
                        count -= 8;
                        if (count <= 0)
                            return false;
                    }
```

**Comment by anders9ustafsson** [comment]
Thanks, @Thunderstriker! This seems like an unlikely error, or am I wrong? It's great that you have provided a fix, but I wonder if *fo-dicom* really should account for all types of invalid DICOM? How do other DICOM toolkits handle this file?

**Comment by Thunderstriker** [comment]
this is indeed an edge case but i got an file from a pacs like this (this was not a test image)
dcmtk was handling it fine and this is not an invalid dicom i think it is allowed to have only empty sequence items

**Comment by anders9ustafsson** [comment]
OK, thanks for checking! I will update.

**Comment by anders9ustafsson** [comment]
@Thunderstriker I have started looking at your proposed solution, and I have a number of questions where I would like your clarification.

1. You have moved the `source.GetUInt32() > 0` inside the `while` block, which means it will only be evaluated *if* the parsed tag is an item tag. However, in the code you are replacing, `source.GetUInt32()` is unconditionally evaluated (using `&` instead of `&&`) to ensure that the length is parsed regardless of tag type (`while (new DicomTag(source.GetUInt16(), source.GetUInt16()) == DicomTag.Item & source.GetUInt32() == 0)`). What is your view on this?
2. You are subtracting `count` with 8, where 8 represents... what? Size of an empty item? I haven't thought this through, but is this really generally applicable? What about implicit versus explicit item length for example?
