### ISSUE TITLE
Question about features

### ISSUE THREAD

**Issue by pauldotknopf** [fo-dicom/fo-dicom#510]
I am looking to potentially migrate from dcmtk to this project.

I'd like to know the status of a few things 

* Do you guys support loading large dicom files, without loading the entire tags (particularly, pixeldata)? We currently support videos, and we can't load the entire thing into memory.
* When capturing dicom files from DIMSE requests, do you support capturing the dicom file directly to the file system? The reason I need this is because of the previous point (large files).
* I imagine you haven't implemented all the SCPs/SCUs, but are all the components and DIMSE commands present for implementations to build, for example, a MPPS? Storage commitment?
* Decoding/encoding transfer syntaxes? JPEG? TIFF?
* Do you support the GZIP compression SOP?

**Comment by anders9ustafsson** [comment]
Hi @pauldotknopf, here are some answers for you:

> Do you guys support loading large dicom files, without loading the entire tags (particularly, pixeldata)? We currently support videos, and we can't load the entire thing into memory.

Yes, you can set a stop criterion when reading a file, e.g. terminating the read before a specific tag.

> When capturing dicom files from DIMSE requests, do you support capturing the dicom file directly to the file system? The reason I need this is because of the previous point (large files).

The response is handled via user-defined callback functions, so you have full control over the retrieval, whether you want to stream it to disk or anything else.

> I imagine you haven't implemented all the SCPs/SCUs, but are all the components and DIMSE commands present for implementations to build, for example, a MPPS? Storage commitment?

All DIMSE-C and -N commands are implemented. Regarding more complex support, e.g. storage commitment, I hope someone else in the community can fill in, because that is not my real area of expertise.

> Decoding/encoding transfer syntaxes? JPEG? TIFF?

JPEG (including lossless), JPEG-LS, JPEG2000 and RLE compressed codes are supported, TIFF is not.

> Do you support the GZIP compression SOP?

Yes.
