### ISSUE TITLE
Unity support

### ISSUE THREAD

**Issue by 1danielcoelho** [fo-dicom/fo-dicom#514]
The [wiki page](https://github.com/fo-dicom/fo-dicom/wiki/Unity) mentions that the Unity assembly has no support for networking or JPEGx compressed codecs, but gives no reason why that seems to be the case.

I assume that the lack of JPEGx compression results from FODICOM using a C library for this task in some way, but surely there are C#-based alternatives, or even methods of importing the compiled class library itself.

And what would be the reason behind the missing networking support? Would it be hard to supplement with user code?

**Comment by anders9ustafsson** [comment]
@1danielcoelho When it comes to compressed codecs, the reason is that there have been no compatible third party codec libraries available on Unity. However, I have recently looked more closely into this, and I intend to release an upgraded *fo-dicom* for Unity with support for JPEG2000, 8-bit lossy JPEG and hopefully also JPEG-LS fairly soon. What's more, also the deflated transfer syntax will be included in that release.

Regarding networking, those parts of *fo-dicom* rely heavily on asynchronous code constructs which are not available on the Unity platform. For the time being, I have therefore left the networking part out of the Unity release.
