### ISSUE TITLE
Need a way to set InternalTransferSyntax when building Dataset with secondary capture JPEGProcess1 from scratch

### ISSUE THREAD

**Issue by halsius** [fo-dicom/fo-dicom#553]
### Expected behavior
I am creating a DataSet by adding jpeg data streams in fragments in the pixel data tag (jpegFileToEmbed.JpegByteStream is a byte[] of jpeg data):

```
DicomDataset ds = new DicomDataset();
ds.Add(new DicomUniqueIdentifier(DicomTag.TransferSyntaxUID, Dicom.DicomTransferSyntax.JPEGProcess1));
DicomFragmentSequence emt = new DicomOtherByteFragment(DicomTag.PixelData);
Dicom.IO.Buffer.MemoryByteBuffer buf = new Dicom.IO.Buffer.MemoryByteBuffer(jpegFileToEmbed.JpegByteStream);
Dicom.IO.Buffer.IByteBuffer end_buf = Dicom.IO.Buffer.EndianByteBuffer.Create(buf, Dicom.DicomTransferSyntax.JPEGProcess1.Endian, 1);
emt.Fragments.Add(end_buf);
ds.Add(emt);
```

As this data is already JPEGProcess1 compatible I would like the DicomClient to not try to re-encode the data from ImplicitVRLE to JPEGProcess1 when sending.

### Actual behavior
When I try to send this Dataset (after making it a DicomCStoreRequest) the DicomClient sucessfully negotiates my ts to JPEGProcess1. However, DicomClient.Send gives me the "no codec available" error as it is trying to re-encode the internal ImplicitVRLE - my data is already JPEGProcess1 compatible - so I just want to send it.

To get around this without recompiling the library I currently write the constructed DataSet as a DicomFile to disk and re-read it (as that will set the InternalTS to the the FileMetaInfo TS).

My request:
 Is there a chance we could have a direct DicomDataset.UpdateInternalTransferSyntax(DicomTransferSyntax) method or release the internal restriction on the property? Or maybe a AddOrUpdatePixelData(DicomFragmentSequence, DicomTransferSyntax)?

**Comment by anders9ustafsson** [comment]
Thanks, @halsius! I will look into this issue and get back soon enough.

**Comment by anders9ustafsson** [comment]
@halsius I have looked into this issue, and I am currently planning on moving as much of this functionality as possible into the `DicomPixelData` class, including the ability to set/modify the transfer syntax. As part of gathering similar functionality  in one place, I also would like to remove the `DicomDataset.AddOrUpdatePixelData` method. Most likely I would also add some support for adding a `DicomFragmentSequence` (or similar) to the `DicomPixelData` class. What are your thoughts on this?

@Zaid-Safadi As you were the "inventor" of the `AddOrUpdatePixelData` method, do you have any input on my plan to move all pixel data updating to the `DicomPixelData` class?

**Comment by Zaid-Safadi** [comment]
It's probably cleaner to move all this functionality to its own class like the DicomPixelData, is there a proposed API you have in mind yet?

**Comment by anders9ustafsson** [comment]
@Zaid-Safadi Not yet, but I will post it as soon as I have one.

**Comment by halsius** [comment]
Moving it all into DicomPixelData is probably the cleanest and most intuitive solution. It will make the api a bit easier to follow too. I fully support this. Haven't looked into how fragment sequences fit into DPD, but I'll have a look and come with some suggestions if you need ideas.

**Comment by Zaid-Safadi** [comment]
@halsius, I'm looking at the current implementation of the Dataset and the usage of the InternalTransferSyntax and if I am not mistaken, using the code you have above, you can just use the DicomDataset constructor that accepts the internalTransferSyntax as a parameter and it will do it for you.

Can you please check this and let us know if that resolves your issue for the time being?

        /// <summary>
        /// Initializes a new instance of the <see cref="DicomDataset"/> class.
        /// </summary>
        /// <param name="internalTransferSyntax">Internal transfer syntax representation of the dataset.</param>
        public DicomDataset(DicomTransferSyntax internalTransferSyntax);

**Comment by anders9ustafsson** [comment]
Please note however that this constructor was very recently added to the code. It is not available in any NuGet package yet.

**Comment by halsius** [comment]
That constructor will do the job in my project, thanks!  As the discussion is started, I still think it would be nice to have a more extensive DickmPixelData class that would handle both fragments and TS modification.

**Comment by anders9ustafsson** [comment]
@halsius I am currently working with this issue to make some small adjustments to `DicomPixelData`. 

First of all, as @Zaid-Safadi also pointed out, there is a new `DicomDataset` constructor that allows you to specify desired transfer syntax. This is not included in any NuGet package yet, but if you build *fo-dicom* from the *development* branch source code it will be available.

Second, `DicomPixelData` contains the support you need already today for adding fragment data. `DicomPixelData.AddFrames(IByteBuffer)` should be sufficient for this purpose, provided you include all fragments for one frame in a `CompositeByteBuffer` (if there are more fragments than one per frame).

For `DicomPixelData` to work properly you need to have specified at least the principal image data in the dataset before creating your `DicomPixelData` instance, at the very least transfer syntax and bits allocated.

Then, if I am not entirely wrong, it should suffice for you to change your code like this:

```
DicomDataset ds = new DicomDataset(DicomTransferSyntax.JPEGProcess1);  // This constructor not yet (Aug 25, 2017) included in any NuGet package
ds.Add(DicomTag.BitsAllocated, 8);

Dicom.IO.Buffer.MemoryByteBuffer buf = new Dicom.IO.Buffer.MemoryByteBuffer(jpegFileToEmbed.JpegByteStream);

var pixelData = DicomPixelData.Create(ds, newPixelData: true);
pixelData.AddFrame(buf);
```

(I have assumed here that you only have one fragment; if there are more than one, `buf` needs to be a `CompositeByteBuffer`.)

Note in particular that you don't need to explicitly create an `EndianByteBuffer`; this is handled automatically in the `AddFrame` implementation.

The changes you make on the `pixelData` object will all be reflected in the underlying `DicomDataset ds`, so in principle you could also use `pixelData` to set `PhotometricInterpretation`, `Width`, `Height` etc. instead of adding the explicit `DicomTag` values to the dataset.

I am currently making some adjustments to allow for OW encapsulated data to be added. This will be part of the PR associated with this issue. But since the code you showed above only includes OB encapsulated data you should not need to wait for that PR to be pulled.

**Comment by halsius** [comment]
Thanks @anders9ustafsson for the effort and explanation - great work! Did not know that addframe did that. I will take the time to build the library from dev to get rid of my current workaround.
