### ISSUE TITLE
Inconsistency when open invalid file

### ISSUE THREAD

**Issue by devsko** [fo-dicom/fo-dicom#641]
### Expected behavior
`DicomFile.OpenAsync()` throws exception when opening an invalid file

### Actual behavior
When the file is less than 132 bytes OpenAsync() returns null instead of throwing

### fo-dicom version and OS/platform
Version 3.0.2 UWP

**Comment by mrbean-bremen** [comment]
As far as I can see, this is due to these lines in handling the parser result:
```cs
        if (result == DicomReaderResult.Processing)
        {
            throw new DicomFileException(df, $"Invalid read return state: {result}");
        }
        if (result == DicomReaderResult.Error)
        {
            return null;
        }
```
e.g. errors are handled by returning `null` intentionally. 
This would be easy to change if wanted, I'm just not sure why it was done in the first place, and if the changed behavior would cause other problems.
(checking old issues)

**Comment by mrbean-bremen** [comment]
Indeed, this is the only case where null is returned.
