### ISSUE TITLE
Invalid bitmap in backgroundworker from RenderImage().As(Of Bitmap)()

### ISSUE THREAD

**Issue by sdekker90** [fo-dicom/fo-dicom#651]
### Expected behavior
I am using the RenderImage method on cineloops to produce bitmaps of all frames. 

### Actual behavior
When I use this method in the main thread, it works fine. When I use this method in a backgroundworker thread, then I get the attached error message. The bitmap returned from RenderImage is invalid. The error is not reproducable in debug mode. The error only occurs when the built application is run.

![fo-dicom invalid param](https://user-images.githubusercontent.com/25793879/34762593-8fbb1a28-f5e8-11e7-975d-c76adb6b2134.png)

### Steps to reproduce the behavior
Insert the below code in a background worker and try to process the attached DCM cineloop.

[EXP0000.zip](https://github.com/fo-dicom/fo-dicom/files/1618028/EXP0000.zip)

` 
Dim dcm As New DicomImage(Dicom.DicomFile.Open("E:\DICOM Images\EXP0000").Dataset)

        'Gray Scale correction
        dcm.WindowCenter = 128
        dcm.ShowOverlays = False

        'All frames to stack
        For i As Integer = 0 To dcm.NumberOfFrames - 1

            Dim bmpSlice As Bitmap
            Dim bmpSlice2 As Bitmap

            Try

                bmpSlice = dcm.RenderImage(i).As(Of Bitmap)()

                bmpSlice2 = New Bitmap(bmpSlice)

            Catch ex As Exception
                MsgBox(ex.ToString)
            End Try

        Next 
`

### fo-dicom version and OS/platform
fo-dicom 3.0.1.0 and Windows 10 with .NET 4.5.2

Thank you so much for your help!

**Comment by gofal** [comment]
I tried but cannot reproduce. dcm is loaded in main thread and the RenderImage are alled in worker threads. but everything works fine.
In which line does the exception throw? When you copy the Bitmap from bmpSlice to bmpSlice2 or does it throw in dcm.RenderImage(..)? Maybe the exception is thrown because the Bitmaps bmpSlice or bmpSlice2 are still used in the main thread?

**Comment by sdekker90** [comment]
Hi, thanks for responding! The error is thrown on the line:

`bmpSlice2 = New Bitmap(bmpSlice)
`

The bmpSlice and bmpSlice2 are declared within the backgroundworker thread, so they cannot be in use by the main thread. In my project, I also open the dcm in the backgroundworker thread, so all the code I pasted in the original post is in the backgroundworker thread. Any ideas? Are you using the same version of fo-dicom?

**Comment by gofal** [comment]
Yes, I have fetched fo-dicom 3.0.1 from nuget and run my sample application in .net 4.5.2 under windows10. 
Since fo-dicom seems to return the Bitmap fine in dcmRenderImage(..) and the exception is thrown when you copy the Bitmap to an other Bitmap, I doubt the failure to be in fo-dicom.
What does your application do with the two Bitmaps? in this sample code they are created within the for-loop and then run out of scope. Since Bitmaps hold native GDI handles it is recomended to dispose them in a clean way instead of leaving it to the garbage collector (by calling bmpSlice.Dispose or coding the "using" clause).

**Comment by sdekker90** [comment]
That is very peculiar. Whenever I try to do anything with the rendered bitmap, whether it is reading a pixel value or copying it to a new variable, it always gives me this error. **One essential detail I forgot to metion, this error happens only when you run the built executable of the project, not when you run the application in debug mode!**

**Comment by gofal** [comment]
ah, yes. If I compile in Release and then run the executable manually (without visual studio) then I get an exception.
Fine (or not so fine), now I will research the cause.

**Comment by sdekker90** [comment]
Thank you so much!

**Comment by gofal** [comment]
Well, I see some handling with pinned pointers when creating the Bitmaps in RenderImage(..) in WinFormsImage.cs this can be effective because the bitmap does not allocate new memory for its pixel data but uses the native pinned pointer. but I assume that in release-mode there are some optimizations and so on that make this pointer invalid.
Please try the following: instead of 
`bmpSlice = dcm.RenderImage(i).As(Of Bitmap)()`
call a .Clone() directly after the RenderImage(i).As(Of Bitmap) so that the complete content (inclusive pixel data) is fully coppied in memory
`bmpSlice = dcm.RenderImage(i).As(Of Bitmap)().Clone()`
When I do this then everything works fiine for me.

**Comment by sdekker90** [comment]
You're the best! It works here as well. Thank you.

**Comment by IanYates** [comment]
Carrying this on in #634
