### ISSUE TITLE
Creating new Dicom file

### ISSUE THREAD

**Issue by murunwas** [fo-dicom/fo-dicom#653]
### Expected behavior
How do I create a new Dicom file from the raw data?
![image](https://user-images.githubusercontent.com/8838943/36025164-bd1f43ee-0d9a-11e8-9d14-5485ceee708f.png)

but I'm getting error: Tag: (0002,0010) not found in dataset

**Comment by gofal** [comment]
Hi,

in wiki there is a link to a working example of how to create a dicom file: https://gist.github.com/mdubey82/4030263
there are few things to notice from your example:

- the transfersyntax is not valid. Dicom has some defined UIDs and you cannot take any number. So use the enum DicomTransferSyntax for a valid value

- I would recommend first to create a DicomDataset and then create a instance of DicomFile with the DicomDataset as parameter in constructor. this is because the DicomFile also has some properties and it configures itself from the DicomDataset

- Dicom defines quite some mandatory DicomTags to be a valid Dicom file and you are missing some. The example you can find in the link given above shows you these type 1 attributes like SOPClassUID, SOPInstanceUID and so on.

**Comment by murunwas** [comment]
Thank you very much @gofal
