### ISSUE TITLE
Abort association if the association is stale

### ISSUE THREAD

**Issue by azzurro1971** [fo-dicom/fo-dicom#666]
### Expected behavior
If a dicom association is stuck and there is no respone anymore after a certain timeout, the association should abort.

### Actual behavior
The client waits forever for a response from the DICOM partner

### fo-dicom version and OS/platform
v.3.0.2

**Comment by FKupsch** [comment]
In a perfect DICOM world, both SCU and SCP would implement timeouts to handle inactivity by the communication partner.

**Comment by cjcaldwell** [comment]
@gofal pointed me to this bug, I've been seeing a related issue. If there's an outstanding request and the remote peer closes the TCP connection without warning, `Send()` (or `SendAsync()`) won't return because `CleanupAsync()` waits for the completion flag to be set but there's no other job that is going to set it.

When `DicomService.ListenAndProcessPDUAsync` encounters the end of stream (ie, `ReadAsync` returns a count of 0) it calls `TryCloseConnection()`, but if there are pending requests this call simply logs that the queues aren't empty and returns without setting the completion flag.

I think that the correct response to end of stream should be `TryCloseConnection(force:true)` or even `TryCloseConnection(new EndOfStreamException(),true)` so that the caller will be informed that the association ended unexpectedly.

I also think it might be wise for TryCloseConnection with force=true to log the lengths of the queues as a warning if any are non-empty before they are closed.

In terms of timeouts, the requirements on these would vary a lot and should probably be implemented in user code when the TCP session hasn't dropped, I think these should probably be implemented in user code.

**Comment by amoerie** [comment]
A lot of the issues with DicomClient should be solved now (especially in the new DicomClient, but also the old one), the only thing mentioned here that is not implemented is timeout behavior. 

But I would vote for excluding this from the 4.0.2 scope so the fixed issues in that release can go out, some people are waiting for them.
