### ISSUE TITLE
DICOM Conformance Statement

### ISSUE THREAD

**Issue by buckstephenh** [fo-dicom/fo-dicom#668]
Hi,

I am looking for a DICOM Conformance Statement for fo-dicom and couldn't find it.  Could you point me in the correct direction?

Thanks.

**Comment by gofal** [comment]
I'm sorry to tell you that fo-dicom does not have a dicom conformance statement and will not have one because a DICOM Conformance Statement is a description of the application you are building.

The DICOM standard defines many different services (store, qr, mpps, image availability, printing, ..) and quite a lot of different dicom tags and possibilities and so on. The reason for a DICOM Conformance Statement is to point out to other vendors and users which of these services your application implements and which of the dicomtags are used (of course the manatory have to be used but you should describe which of the optional values are evaluated and stored). 

For example if you implement a QR-SCP then the dicom conformance statement should point out for which of the dicomtags you support a filtering and if you support wildcard search or not and so on. 
If you implement a PrintSCP you have to describe in the dicom conformance statement which different paper sizes you accept and how you map it to the windows printers paper sizes.
If you implement a modality with worklist c-find you have to describe which of the dicom tags you use for procedure mapping (the scheduledprocedurestep-codes or the scheduledprocedure-description of it is up to configuration which of them is used).
...
And you have to describe some general information, for example if you support concurrent services or if you queue the requests (due to some database sync-locking) and so on.

The DICOM standard itself describes how such a conformance statement should look like: http://dicom.nema.org/dicom/2004/04_02pu.pdf. It makes the reading of such a technical document easier if every vendor uses the same structure and format.

**Comment by gofal** [comment]
Hope you managed to create a dicom conformance statement for your product. If you still have some questions or need further help, please feel free to ask on gitter or google groups forum.
