### ISSUE TITLE
Private tags lost in transport when using DicomDataset.Add

### ISSUE THREAD

**Issue by JoakimRaySearch** [fo-dicom/fo-dicom#671]
### Expected behavior
I can use and send private tags.

### Actual behavior
If you add a private tag directly (using Add<T>(DicomTag tag, params T[] values)) then no problem. The problem is if you use Add(params DicomItem[] items) because only the key in the dataset will then be masked with the private creator. The DicomItem and the tag there is not modified and this results in the private creator getting lost in the transport...

### Steps to reproduce the behavior
See 

[patch.zip](https://github.com/fo-dicom/fo-dicom/files/1889095/patch.zip)

This patch adds a test to the fo-dicom 3.0.2 code to highlight the problem. The last assert in that test fails for me.

### fo-dicom version and OS/platform
3.0.2, Windows 10

**Comment by anders9ustafsson** [comment]
The handling of private creator masks has been (hopefully sufficiently) corrected in a recent pull request (just can't remember the PR number right now). Please download and build *fo-dicom* from the latest source code to check if the problem described here is still present.

**Comment by JoakimRaySearch** [comment]
I just tried against the 48383f5fd77dab0b4043834ab0b2e828752f0e55 commit (latest, 18 apr 2018).

Got a brand new behaviour, still very much wrong though.
The result from
`responseDataset.Get<string>(privTag2, null)`
is suddenly "116" instead of the expected "test2". No idea what happened there.

**Comment by gofal** [comment]
116 is the ASCII for the character "t". the string is interpreted as array of bytes. Thats happening behind the scenes. Will fix it.

**Comment by gofal** [comment]
I can bring some light into this issue:
I took a look at your patch appended. When you create the request dataset and add the private tags with a string value, then fo-dicom internally adds the tags with some Value Representation that is guessed. In this case it was CS. But when the private tags are sent via c store then the SimpleCStoreProvider receives the 6 bytes. But the store scp does not know about the Value Representation. It is assumed as UN (unknown).
The method DicomDataset.Get<T> tries to convert into the managed type T. but since the undersying data structure is an array of 6 bytes the conversion to a string is "116". It is not obvious why only the first byte is returned. There is a pull request #679 with a change of the API where a new method DicomDataset.GetString would return "116\101\115\116\50\32" which more obvious looks like a byte array.

If you want to use private tags then you first have to tell fo-dicom some information about the private tags. There is a wiki page that describes how you can do this for a bulk of private tags: https://github.com/fo-dicom/fo-dicom/wiki/Adding-private-tags-to-dictionary.
But you can do it aso in code. For your unit test that would be:

                var privateCreator = DicomDictionary.Default.GetPrivateCreator("Testing");
                var privTag1 = new DicomTag(4013, 0x008, privateCreator);
                var privTag2 = new DicomTag(4013, 0x009, privateCreator);
                DicomDictionary.Default.Add(new DicomDictionaryEntry(privTag1, "testTag1", "testKey1", DicomVM.VM_1, false, DicomVR.CS));
                DicomDictionary.Default.Add(new DicomDictionaryEntry(privTag2, "testTag2", "testKey2", DicomVM.VM_1, false, DicomVR.CS));

Now fo-dicom knows that these two tags do have a Value Representation of CS. When you add these two lines then the unit test passes.

But I noticed one bug: when I try to send the request dataset with a explicit transfer syntax then the VR should be included in the request and the parser of the store scp should use this VR instead of only using the DicomDictionary.
But in case of an implicit transfer syntax the store scp only receives a byte array and cannot know without further information of the developer if this is a string, or a array of integer values or a decimal or ... Do you agree?

**Comment by gofal** [comment]
Tested a lot with the sample applications. The Value Representation when sending the private tags works without problems.

I see here no bug, because the behaviour can be explained well. To make sure that the correct VR is used to interpret the byte stream, the DicomDictionary has to be filled with the information.
