### ISSUE TITLE
Incorrect value of ReferencedFileID retrieving from DICOMDIR file

### ISSUE THREAD

**Issue by MrVine** [fo-dicom/fo-dicom#687]
I use following code to retrieve `ReferencedFileID` from `DICOMDIR` file:
```
var id = item.Get<string>(DicomTag.ReferencedFileID);
```

Expected value of `ReferencedFileID` (real value retrieved from my `DICOMDIR` file) is `7741\\7743`:
![scr_expected_id_value_2](https://user-images.githubusercontent.com/5161479/39805654-2a34f908-5380-11e8-8f67-70cd95ef2324.png)

But actual value, which I have in `id` variable is `7741`:
![scr_actual_id_value_2](https://user-images.githubusercontent.com/5161479/39805670-35aca8c6-5380-11e8-804d-9d01dafef6af.png)

Why?
How can I got real value from my `DICOMDIR` file to my `id` variable?

### fo-dicom version and OS/platform
I use following software:
**OS**: Windows 10 x64
**IDE**: Visual Studio 2017
**PROJECT TYPE**: Windows Forms
**.NET FRAMEWORK**: version 4.5.2
**fo-dicom**: verion 3.0.2 (from NuGet)

**Comment by gofal** [comment]
You are facing a very common problem with the DicomDataset.Get<> method. Take a look at wiki: https://github.com/fo-dicom/fo-dicom/wiki/Getting-data

Because this is so confusing, there is already a new API in development branch and will be released soon: https://github.com/fo-dicom/fo-dicom/pull/679.

Wait for the new release (hopefully end of this week) or use `var id = item.Get<string>(DicomTag.ReferencedFileID, -1);`

**Comment by MrVine** [comment]
It works!)
Thank you so much, @gofal ! :)
