### ISSUE TITLE
Add ImageSharp as IImage implementation

### ISSUE THREAD

**Issue by gofal** [fo-dicom/fo-dicom#693]
### Expected behavior
there are currently only platform specific implementations for IImage like WinformsImage, WpfImage, CGImage etc.
Having one platform independent implementation would complete the list.

### Actual behavior
when creating a portable library using fo-dicom, you still cannot rely which implementation of IImage will be used later depending on which platform the application runs.
Even if ImageSharp is slower than platform specific implementations, it has the advantage that you can implement image manipulations portable.

**Comment by roitenen1981** [comment]
Thanks, 
I am testing now under windows with the fo-dicom.NetCore, with fo-dicom.desktop I can get the Image but with the same Dicom file from fo-dicom.netCore I get an Exception (if the implementation is dependent on the platfor the implementation for windows should have been working with the fo-dicom.NetCore as well?).
I took your hint and started using ImageSharp instead of the IImage, so my code looks like this -

 DicomOtherByteFragment ob = fileDataSet.Get<DicomOtherByteFragment>(DicomTag.PixelData);
                    fileExtension = ".jpg";
                     byte[] bytes = ob.Fragments[0].Data;
                    MemoryStream stream = new MemoryStream(bytes);
                    using (System.DrawingCore.Image image = System.DrawingCore.Image.FromStream(stream))
                    {
               
                        image.Save(Path.Combine(_filesPath, fileName + fileExtension)); 
                    }

it works with some compressions, but not with others (for example RLE compression is not working. 
(tested with this example file - http://www.rubomedical.com/dicom_files/dicom_viewer_0020.zip, which is decoded correctly with IImage on fo-dicom.desktop. 
 is this a bug of the ImageSharp? (if so it seems that beside being slow it also has other disadvantages if you consider using it).
Thanks,
Roi

**Comment by gofal** [comment]
no, this is no bug in ImageSharp. RLE is not a typical image processing compression, but rather only used in medical image. So in case of RLE fo-dicom first has to decompress the raw bytes before passing to ImageSharp. So there will be some implementation to integrage ImageSharp, but it should not be too much.
There are also some other compressions like JpegLossless process 14, that is only used in medical image and where there is currently no net core implementation.

Did you measure the performance impact?

**Comment by roit1981** [comment]
I had to leave the project for now, so not yet.
Thanks for your help!
