### ISSUE TITLE
I miss the function to send requests on an existing association with the DicomClient

### ISSUE THREAD

**Issue by FKupsch** [fo-dicom/fo-dicom#707]
So think about a DICOM Query SCP that only supports the Patient Root Query SOP class.  To handle this case a Query SCU must propose both Query SOP classes (Patient and Study Root), open the association, check which of them are accepted by the SCP and then send its C-FIND requests on the negotiated abstract syntax. The current implementation does not allow this. Instead I have to create the request before the association was opened. At a time were I can´t know which SOP class is supported by the SCP. Besides, it is actually more effective to send sequential C-FIND requests in one association. 

### fo-dicom version and OS/platform
doesn´t matter

**Comment by gofal** [comment]
You are right, would be a great enhancement for more experienced dicom-technicans.
Because when sending the associationrequest, the dicomclient has to know all the abstract syntaxes that will be sent within the association. This is why fo-dicom is designed as it is now, it is simpler to use. About the Query SCP case you described. Typically this is not dynamically which sopclasses a server supports - it does not change all the time. My implementations have the possibility to configure the parameters. then I once find out and configure the client and then it works fine all the time.

Technically it will be difficult to extend the current dicomclient implementation. It is a good idea to create a new DicomClient class to open an association and send several requests.

**Comment by gofal** [comment]
@amoerie is doing a restructuring of DicomClient: https://github.com/amoerie/fo-dicom/blob/DicomClientRewrite/DICOM/Network/Client/DicomClient.cs.

His comment on gitter:

> #707 Can actually be done. If you call SendAsync during the IDLE state, it will connect and associate regardless of whether you have queued any requests. And queueing requests is always allowed, in every DicomClient state. So you can do something like this:
>
>     var client = new DicomClient("127.0.0.1", 104, "ClientAE", "ServerAE", ..)
>     client.AssociationAccepted += (sender, associationAcceptedEventArgs) => {
>          var association = associationAcceptedEventArgs.Association;
>          if( ... ) {
>               client.AddRequest(...)
>          } else {
>                client.AddRequest(...)
>          }
>     }
>
> client.SendAsync(cancellationToken);
> because the event handler "AssociationAccepted" is triggered BEFORE transitioning to the SENDING_REQUESTS state, any queued requests in the event handler should be sent immediately thereafter.
> and there's also the StateChanged event on the DicomClient which could be used to the same effect.

**Comment by gofal** [comment]
> One more note on #707: If you increase the linger timeout, you can always send more requests over the current association WITHOUT enqueuing them first. You just need to make sure the association has the necessary presentation contexts available to do so. I would not recommend using the same DicomClient for C-Find and C-Move requests, but multiple C-Finds over the same association of the same DicomClient should be no problem at all.

**Comment by gofal** [comment]
this is implemented with the new DicomClient
