### ISSUE TITLE
GetValues<object> for empty OB buffer throws an exception

### ISSUE THREAD

**Issue by rkm** [fo-dicom/fo-dicom#720]
### Expected behavior

`GetValues<object>(tag)` behaves the same as `GetValues<byte>(tag)`

### Actual behavior
`GetValues<object>(tag)` throws an exception:

```C#
System.ArgumentOutOfRangeException : Index is outside the range of available value items
Parameter name: item
   at Dicom.DicomValueElement`1.Get[T](Int32 item) in C:\fo-dicom\DICOM\DicomElement.cs:line 365
   at Dicom.DicomOtherByte.Get[T](Int32 item) in C:\fo-dicom\DICOM\DicomElement.cs:line 1137
   at Dicom.DicomDataset.GetValues[T](DicomTag tag) in C:\fo-dicom\DICOM\DicomDataset.cs:line 327
   at ... GetEmptyByteBuffer()
```

### Steps to reproduce the behavior

```C#
[Test]
public void GetEmptyByteBuffer()
{
    var ds = new DicomDataset
    {
      new DicomOtherByte(DicomTag.SelectorOBValue)
    };

    // Fine
    byte[] bytes = ds.GetValues<byte>(DicomTag.SelectorOBValue);

    // ArgumentOutOfRangeException 
    object[] objects = ds.GetValues<object>(DicomTag.SelectorOBValue);
}
```

### fo-dicom version and OS/platform
fo-dicom .NET 4.0.0-rc1, Windows 10.

**Comment by gofal** [comment]
The DicomDataset.Get methods give you access to the underlying data and return it as typed values.
These methods (the new ones since version 4 as well as the old ones until version 3) dont do any data manipualtion, they return the values and to casting or supported implicit conversions. say the real value of the value representation is a DS, then you can cann GetValue<double> since there is an implicit conversion from int to double. But it would not work vice versa.
And even if there is always a casting from byte to object possible, it is not possible in .net to cast from array of int to array of object. Thats why this GetValues does not work.

I agree the exception message is somehow misleading. 
To achive what you expect it would be necessary to copy the create a new array of object and to copy values.

**Comment by mia-san** [comment]
I've looked into this issue and I have rather different impression.

thanks to @rkm's sample program, I could reproduce the issue.
however, the exception is NOT thrown if DicomOtherByte is NOT empty.

also, not only DicomOtherByte, but also DicomOtherXxxx, DicomUnsignedXxxx, DicomSignedXxxx etc are also throw the exception only if the element is empty.

the exception comes from DicomValueElement.Get<T>, namely
https://github.com/fo-dicom/fo-dicom/blob/c01c64e857cea1931089eb2ebf93439d0f12a852/DICOM/DicomElement.cs#L365

the check is inside `if (typeof(T) == typeof(object[]))` case.

the bounds check against variable `item` seems strange, as the variable is always -1 on entering `Get<T>` when invoked indirectly via `DicomDataset.GetValues`, and it is immediately changed to 0 at the beginning of `Get<T>`.

also, later in same function, neither `if (typeof(T) == typeof(Tv[]))` nor `if (typeof(T) == typeof(string[]))` case have the bounds check.

now, I suspect that the bounds check is not necessary...
