### ISSUE TITLE
Extended DICOM association: fuzzy matching

### ISSUE THREAD

**Issue by hkoestin** [fo-dicom/fo-dicom#740]
Hello all!

I am currently trying to send a C-Find request to a PACS, enabling the fuzzy matching for patient names etc.

Searching the code base and the wiki, I only found references to the ExtendedNegotiatons property of the DicomAssociation class and the RootQueryRetrieveInfoFind class with its FuzzySemanticMatching property.

But so far I have not figured out how to actually request that at the association.
See: http://dicom.nema.org/Dicom/2013/output/chtml/part04/sect_C.5.html#table_C.5-1

How can I achieve fuzzy matching for strings?

Thanks in advance!
Harald

**Comment by gofal** [comment]
Interesting enough: in DicomClient there is no possibility to set Extended Negotiation SubItems. But fo-dicom seems to be well prepared: the DicomAssociation class contains a list of ExtendedNegotiations, that the SCPService can read when handling OnAssociationRequest.
And the DicomClient internally constructs a DicomAssociation, that has always an empty List of ExtendedNegotiations. But there are unit tests how the DicomClient would handle and render the list of ExtendedNegotiotions into the network stream (https://github.com/fo-dicom/fo-dicom/blob/87291c19a4fdec573a7253b1e1a02b2ec8a98c3c/Tests/Desktop/Network/PDUTest.cs#L57).

But there is some Api method missing where the user may add it. What would you suggest? There could be a method in DicomClient, that has to be called between DicomClient.AddRequest and DicomClient.SendAsync.
Or the DicomRequest could have a method to add ExtendedNegotioations. 
Or the DicomClient.SendAsync may mave an additional optional parameter.

**Comment by hkoestin** [comment]
Thank you for your fast reply. I have searched the API and found like all classes in place to perform the fuzzy matching for C-Finds etc., but there is, as you said, the API method missing to actually set the ExtendedNegotiation class.

When you have a look at the current DicomClient impl, e.g. the presentation context objects are read from the requests and added and also from the AdditionalPresentationContexts property on the client itself.
See https://github.com/fo-dicom/fo-dicom/blob/87291c19a4fdec573a7253b1e1a02b2ec8a98c3c/DICOM/Network/DicomClient.cs#L679-L686

For reasons of symmetry, I would suggest to have it the same way for the extended negotiations.

Here is a sketch for the API:

```c#
var request = new DicomCFindRequest(DicomQueryRetrieveLevel.Study);
// when setting a special PC, you can do that on the request already
request.PresentationContext = new DicomPresentationContext(...);
// SUGGESTION: setting the Extended Negotiations could also work on that object
request.ExtendedNegotions.Add();

var client = new DicomClient();

// also on the client, you can add additional PCs already
client.AdditionalPresentationContexts.Add(/* some context */);

// SUGGESTION: for symmetry reasons, I would also allow the adding of ENs here
client.ExtendedNegotiations.Add(
    new DicomExtendedNegotiation(
        DicomUID.StudyRootQueryRetrieveInformationModelFIND,
        new RootQueryRetrieveInfoFind(1, 1, 1, 1, null)));
```

What do you think about that suggestions?

Because I somehow very much dislike constructors as the one for the RootQueryRetrieveInfoFind, where you pass in 5 nullable types and easily can mix them up, I would also consider to add an overload, maybe using a flag-enum or the like? The constructor internally then can set the correct values. This would make life easier when you set the negotiations.

```c#
[Flags]
public enum QueryRetrieveExtendedNegotiations 
{
   None = 0,
   RelationalQueries = 1,
   DateTimeMatching = 2,
   FuzzySemanticMatching = 4, 
   ...
}

// and the constructor then
public RootQueryRetrieveInfoFind(QueryRetrieveExtendedNegotiations negotiations) 
{
   this.RelationalQueries = negotiations.HasFlag(QueryRetrieveExtendedNegoations.RelationalQueries) 
                                                ? 1 : null;
   // etc.
}

// constructing then is nice, as it is "self-speaking" when reading the code
var x = new RootQueryRetrieveInfoFind(QueryRetrieveExtendedNegoations.RelationalQueries |
                              QueryRetrieveExtendedNegoations.FuzzySemanticMatching);
```

**Comment by hkoestin** [comment]
Oh, forgot about that ....

More importantly for me, when would you see that being implemented? Or can I even help with that?

I would need this better sooner than later ;-)
In an official release if possible.

**Comment by gofal** [comment]
Completely agree with you. I also prefereded the API to extend the DicomRequest class. Since the ExtendedNegotiations are in context of AbstractSyntaxUID.
But the user has to be made aware that if he enqueues two CFind-requests on DicomClient and adds a ExtendedNegotiaionSubitem to one of the Requests, then the DicomClient will send this and the SCP will handle both requests with this option.

**Comment by gofal** [comment]
It would be best, if you could implement and create a pull request. Then it will be implemented soon, since I have quite some issues in my queue and I prefer to fix bugs prior to add enhancements.
Currently I see no workaround, so it has be be implemented first. I don't know when the next release will published. Thats the part @anders9ustafsson is doing.

**Comment by hkoestin** [comment]
I will work on that soon. Guess I find some time this afternoon/evening or tomorrow. 
Will create a PR afterwards.

**Comment by hkoestin** [comment]
I started to implement now and finished with most of the things.
But now I am facing some issues.

According to the standard, it should behave like this:

> The Association-requester, for each SOP Class, may use one SOP Class Extended Negotiation Sub-Item. The SOP Class is identified by the corresponding Abstract Syntax Name (as defined by PS3.7) followed by the Service-class-application-information field.

How should we handle the merge now best?
Merge behavior is actually now best sitting in the concrete IExtendedNegotiation SubItem class, because only that class knows how to merge with another item. But on the level of the association, I only have the DicomExtendedNegotiation with its SubItem. Casts there are ugly I would say ;-)

See this part of the code:
https://github.com/hkoestin/fo-dicom/commit/acabfe57001537161d67c4b5102ab399e3f9cba4#r31132250

@gofal  What do you suggest?

**Comment by gofal** [comment]
Thanks, great. I addes my thoughts.

**Comment by hkoestin** [comment]
Thanks for the comments on that.

Having thought about my current implementation now for a while, I am not really happy with it. Actually, what would be needed, is another parent class for those requests, which - according to the standard - support association negotiation using extended negotiation. 
Namely, these are: C-FIND, C-MOVE, C-GET

This is listed right in the beginning here:
http://dicom.nema.org/Dicom/2013/output/chtml/part04/sect_C.5.html

What would you think about introducing a new class in the hierarchy:
```c#
public abstract class DicomExtendedNegotiationRequest : DicomPriorityRequest 
{
     public DicomExtendedNegotiation ExtendedNegotiation { get; set; }

     // see below
     internal override void EnrichAssociation(DicomAssocation association) 
     {
         association.MergeExtendedNegotiationFromRequest(ExtendedNegotiation);
     }
}
```

CGet, CMove and CFind would then derive from that one, which is IMHO cleaner and more reflects the actual standard.

In the DicomRequest class we introduce a new method, which is more generic and can be used to "enrich" a DicomAssociation with "flavor". For most of the request types, this is not used, but for the extended negotiation requests, we can override it and add some "meat" there.

```c#
public class DicomRequest
{
   internal virtual void EnrichAssociation(DicomAssociation association)
   {
   }
}
```

In the DicomClient, we would then just have the following 
```c#
foreach (var request in _requests)
{
   association.PresentationContexts.AddFromRequest(request);
   request.EnrichAssociation(association); // each request then knows what exactly to do and how to enrich it
}
```

The rest I would do then as you suggested. So having the Merge method on the IExtendedNegotiationSubItem interface etc.
And since the DicomAssociation would first search for the matching SOP Class, we actually should never run into the exception case of merging two different items, right?

What do you think?

**Comment by gofal** [comment]
I think you have put a lot of thoughts into this architecture and it sounds very clear and well understandable for other developers. Like it very much, thanks!

**Comment by hkoestin** [comment]
@gofal I implemented the merging behavior now in Commit https://github.com/hkoestin/fo-dicom/commit/9222195d5215de14e20558eace3a4a5deeb74f1d
Also added unit tests for that behavior, which should be fine now.

This actually all works fine and nice, but the tests are failing because of the following:
The DicomAssocation class has the ExtendedNegotiations property, which is a simple list.
Lots of other pieces of code call .Add() on that property and simply add negotiations there, e.g. the PDU class.
https://github.com/hkoestin/fo-dicom/blob/development/DICOM/Network/PDU.cs#L904

So for them, I cannot control the behavior to merge in the negotiations. There is now some symmetry lost. On sending the request, the negotiations would be merged, but on receiving association objects when it is accepted, the negotiations would be simply added.

Actually, we would need to have a special collection around, which would always only merge things, right? This would be similar to the DicomPresentationContextCollection, which already exists.

I am not sure though, how deep this would go and if I still can implement all that stuff without any knowledge there.
Help/advice appreciated ;-)

Maybe you and also @anders9ustafsson can have a look at this?

**Comment by hkoestin** [comment]
Are there any thoughts on this how I should go on with the implementation?

**Comment by hkoestin** [comment]
So you would suggest, that I simply change the type of the ExtendedNegotiations collection on the association and implement something similar to the presentation context collection?

Thing is, even when reading data from the network using the PDU code, the extended negotiation sub-items have to be merged in correctly.

When I find some more time, I will have a look at this again.

**Comment by davidsybren** [comment]
Hi @gofal, @hkoestin , 

I have been working on a rewrite for the extended negotiation as well because the current implementation has a couple of more issues than mentioned above. And i think that my new implementation handles most of the concerns in this thread as well. See: [https://github.com/davidsybren/fo-dicom/commit/349a49bfcd23965d933d31d811aab2f62bb1e2c5](https://github.com/davidsybren/fo-dicom/commit/349a49bfcd23965d933d31d811aab2f62bb1e2c5 )

The following changes are included in my rewrite:
* Adding support for all items of the SOP Class Extended Negotiation service class application information fields currently known in the DICOM standard. (like fuzzy matching for queries and element coercion for storage classes, etc.)
* Added convenient classes for C-Find, C-Get, C-Move and C-Store with the possibility to create custom convenience classes and inject a factory method to decide which class should be used for which sop class.
* Adding support for the SOP Class **Common** Extended Negotiation so that the service class uid and related general sop classes can be notified in extended negotiation for storage sop classes.
* As an SCU have the ability to add extended negotiation to either the DicomClient or DicomRequest. With adding it to the DicomRequest you have to take into account that it will affect all request with the same SOP class within one association. The extended negotiation that is set to the last request will be used though.
* As an SCP it will be necessary to explicitly Accept the extended negotiation requested by the SCU (just like the presentation contexts). It will be omitted from the AAssociateAC if it is not accepted, otherwise it will look like the SCP supports everything that is requested. 
* Removed the PDU related code from the extended negotiation class.
* Old SubItem classes are removed so it will break current implementations that make use of it.

What do you think? Do you see any other concerns?

Thanks,
Dave

**Comment by amoerie** [comment]
I perused through your changes briefly, and these are a few first impressions:

- Nice, well structured code!
- Seems to follow existing style and techniques rather neatly 👍
- the constructor of DicomCFindApplicationInfo could perhaps benefit from an Enum with [Flags] instead of five booleans, to make the API a little nicer to use. But perhaps it's not appropriate.
- you've made a significant amount of changes to the code, but I'm missing the equivalent amount of unit tests. Is most of the logic already covered by existing tests, or am I missing something? It's a genuine question, I'm no Fellow Oak DICOM expert by far. 🙂

**Comment by davidsybren** [comment]
Thanks for your feedback @amoerie 

Your idea of using an Enum in the constructor of DicomCFindApplicationInfo is rather a good idea, so i've changed this part of the code in my rep, as well as for CMove and CGet.

You are probably right about the unit tests. I think that the most critical parts are covered, but the amount of tests is quite minimal. I will have a look and see if I can improve the test coverage.

**Comment by amoerie** [comment]
Also, you should definitely create a PR! It facilitates the discussion and makes it easier to see the changes you've made. Don't worry if it's not entirely ready yet, it can be a WIP 😉
