### ISSUE TITLE
DicomClient seems to keep opening TCP connecion after association release

### ISSUE THREAD

**Issue by mia-san** [fo-dicom/fo-dicom#745]
### Expected behavior
TCP connection should be closed (semi-)instantly after association release.

### Actual behavior
TCP connection is kept open after association release for timeout period specified by Send(Async).

### Steps to reproduce the behavior
I'm attaching minimum program and logs from related programs.
program performs same study query twice in a row, one by one.
for dcmqrscp-session.log, Dicom.Core.dll is built by myself with extra logging for debugging puropse.
netstat shows 2 TCP connections are alive.

[ConsoleApplication1.zip](https://github.com/fo-dicom/fo-dicom/files/2545903/ConsoleApplication1.zip)
[dcmqrscp.log](https://github.com/fo-dicom/fo-dicom/files/2545918/dcmqrscp.log)
[dcmqrscp-session.log](https://github.com/fo-dicom/fo-dicom/files/2545907/dcmqrscp-session.log)
[netstat.log](https://github.com/fo-dicom/fo-dicom/files/2545920/netstat.log)

### fo-dicom version and OS/platform
fo-dicom 4.0.0, Windows 10, Visual Studion 2015.
fo-dicom 3.1.0-alpha and fo-dicom 3.0.2 also exhibits same.
I noticed this on C-FIND only, other protocols may be affected.

**Comment by mia-san** [comment]
some backgrounds.

As you might know, dcmqrscp is "single task"; i.e. it handles one request at a time.
I noticed that my program behaves extremely "slow" against dcmqrscp.
After some investigation, I found my program is waiting for request to be prosessed except first one.
using netstat, I noticed that session is kept opened for some duration of time.

After more investigation,  following line seems to be suspicious.
  https://github.com/fo-dicom/fo-dicom/blob/4c3e6986e9a3d3b2f45172bb4cc40ae18eca2b00/DICOM/Network/DicomClient.cs#L540
  `await Task.WhenAny(_serviceRunnerTask, SendOrReleaseAsync(millisecondsTimeout)).ConfigureAwait(false);`

It seems to me that:
- if SendOrReleaseAsync terminates early, it alerts _completionFlag and CleanupAsync will dispose _networkStream, it is expected.
- if _serviceRunnerTask terminated early for some reason, _completionFlag is unalerted and CleanupAsync leave _networkStream open.
And, actually RunAsync terminates before SendOrReleaseAsync, as you see in dcmqrscp-session.log.

This might not be a problem against "production" DICOM server, as they usually handles multiple requests at once, and connection might be closed after timeout period  eventually.
but it is not a good idea to occupy server socket for no good reason, IMHO.

I tried to fix, but but I'm not sure where to alert _completionFlag.
Should alert _completionFlag after WaitAny above?
If it is, adding _completionFlag.Set() before CleanupAsync in finally clause might be enough.

**Comment by gofal** [comment]
I think the reason for this "force" parameter was exactly to determine if the connection should be closed or not. 
The method CleanupAsync is called from the Send and SendAsync methods. Both methods have 2 overloads, one with host and port as parameters and one with a INetworkstream as a parameter. 
In first case, the client create a connection to host and port, and in second case the method gets passed in a alreade opened connection. 
I believe, the intention was that the client closes the connection in first case if it opened the connection, but that it should keep the connection open in second case there the connection have been opened somewhere outside. Because maybe the user once opens the connection and then calls the DicomClient.Send several times with this one connection, then the user doesnt want the DicomClient to automatically close the connection.

Does this sound reasonable? I would rather correct the "force" parameter in the Send-calls than adding the "_requests.IsEmpty" condition. What do you think?

**Comment by mia-san** [comment]
I agree that connection should not be closed on INetworkStream case.
Somehow I missed those overloads.
_requests.Empty is just a quick hack to make dcmtk happy, correcting "force" may be better.
Perhaps add "force" flag to DoSendAsync? I'm not sure...
I'd be happy as long as connection is closed after association release, 

also, storescp without --fork seems to be affected, too.

**Comment by gofal** [comment]
update on status. This takes me longer than I thought. Still investigating. What I have is a status where the sample application posted above works fine against the storescp, but now some unittest fail, where the same DicomClient instance is used many times in a loop for OpeningAssociation, SendEcho, CloseAssociation against a fo-dicom server. There I get exceptions because of accessing disposed network streams.

There is a big synchronisation issue. the sender queue and the tcp listener waiting for resposes are separated in two threads and hardly do synchronisation. until now
* the client sends its associationrequest
* then it waits for a associationaccepted or associationrejected - thats synced
* but then it sends all its requests that are in the queue and sends the associationreleaserequest
- here the synchronisation did not work so fine, the client.Send method finished and the main code went on while there still is this open connection where the storescp wants to send its responses...

my fix so far was adding more synchronisation. Will commit the code, that I have so far, into a branch. I am not sure if I go into the right direction. 
@mia-san I would much appreciate if you could review the changes so far

**Comment by mia-san** [comment]
@gofal  oh, I sure will, though I have very little knowledge about fo-dicom's networking code.
let me know when you're done.

**Comment by gofal** [comment]
Please take a look at branch GH-745.
What I did so far

* dicomclient.Send now closes the connection if the connection was opened within the Send-method. This is done by forwarding the property "force" in method DicomClient.CleanupAsync
* this connection closing may not happen too early, the dicomclient has to wait until the AssociationReleaseResponse has been received and processed.

With these two changes the sample application you posted against dcmtk works fine. Also some other quick tests against dicomobjects worked.

But: there are some unittests where the same DicomClient instance is used in a for loop and the DicomClient.Send(...) is called several times. after some calls there are exceptions that a disposed network connection is accessed. When I create new instances of DicomClient in every loop iteration then it works fine. But I think the DicomClient should be able to be called several times.
I cannot find the spot where I miss some synchronisation or cleanup or similar. Maybe you can find something?

**Comment by mia-san** [comment]
GH-745 essentially adds sync object to know if association was actually released, right?
it looks fine to me.

regarding failing unit test, I'll look into it.
it may take some time.

btw, current code is highly async, rather excessively.
something like following dumb and simpler code might be useful, in longer term ?
```
open network connection
await association
foreach requests {
  await request
}
dispose network connection
```

**Comment by gofal** [comment]
An update of the issue:
I did lot of intensive testing and tried many different things. I cannot find the reason why some unittests that sends many requests still fail because plenty of response handlers are not called.
Finally I observed, that if I start the DicomServer on an other machine and execute the unittests with the modification to send the requests to the DicomServer on the other machine, the tests always execute green.
So maybe this is not an issue of the DicomClient any more, but an issue of the DicomServer that happens only if the dicomclient and dicomserver are on the same machine. This would indicate some race condition. I will continue investigating in this direction.

**Comment by mia-san** [comment]
I think I also observed strange failures.
in some cases, such unit tests succeeds by changing 'timeout' in the test longer.
(e.g. flag.Wait(10000); to flag.Wait(60000);)
I'm not sure if the failure is just a matter of timeout, though.

in other cases, DicomClient try to open many connections at once and fails.

probably threads or sockets are contending ?

**Comment by mocsharp** [comment]
FYI: I tested 4.0.0 on Linux (Ubuntu 18.04 with .NET Core 2.2).

**Orthanc** We have 2 threads using DicomClient to send one single DICOM at a time.  After sending a few files (with a queue of 100+), it would stop processing.

**DCMTK storescp --fork** With a queue of 100K files, after sometime, we'll see network exception, i believe it ran out of port to use.

**Comment by mia-san** [comment]
@mocsharp you mean #780 doesn't work for you?

**Comment by mocsharp** [comment]
Looks like if I explicitly call `client.Release()` everything works fine with Orthanc.
```
request.OnResponseReceived += (req, response) =>
                    {
                        Console.WriteLine("\t\tC-Store Response Received, Status: " + response.Status);
                        client.Release();
                    };
```

**Comment by deyung** [comment]
> Looks like if I explicitly call `client.Release()` everything works fine with Orthanc.
> 
> ```
> request.OnResponseReceived += (req, response) =>
>                     {
>                         Console.WriteLine("\t\tC-Store Response Received, Status: " + response.Status);
>                         client.Release();
>                     };
> ```

That's what I had to do to get this to work. Without it, it was keeping the connection open.

**Comment by mocsharp** [comment]
Calling `client.Release` seems to solve the issue reported above.  I'm calling it inside `request.OnResponseReceived` not sure if this would be any issue.

**Comment by amoerie** [comment]
@gofal This is probably not relevant anymore for the new DicomClient. The association will be kept open as specified by LingerAsync, after the association is closed the connection will always be properly disposed.

**Comment by gofal** [comment]
Agree. The new DicomClient shall be the go forward implementation. the old DicomClient has been made far more robust and stable with the next release, for those who do not want to update to new DicomClient.
