### ISSUE TITLE
UID: Unknown [1.2.276.0.50.1.2.1] is not a transfer syntax type

### ISSUE THREAD

**Issue by SrividyaTR** [fo-dicom/fo-dicom#749]
### Expected behavior
Cmove request should be accepted and should succeed against the Jivex PACS https://www.visus.com/fileadmin/content/pictures/Downloads/Kommunikationsstandards/conformancestatement_dicom_en.pdf

### Actual behavior
Cmove request does not get accepted, instead the following exception is thrown
Dicom.DicomDataException: UID: Unknown [1.2.276.0.50.1.2.1] is not a transfer syntax type.
   bei Dicom.DicomTransferSyntax.Lookup(DicomUID uid)
   bei Dicom.Network.AAssociateRQ.Read(RawPDU raw)
   bei Dicom.Network.DicomService.<ListenAndProcessPDUAsync>d__58.MoveNext()

### Steps to reproduce the behavior
Trying to perform a CMove against the Jivex PACS gives this error. 
**This was working fine in fo-Dicom version 3.0.2**

### fo-dicom version and OS/platform
fo-dicom 4.0.0
Windows, .NET framework 4.7.1

**Comment by SrividyaTR** [comment]
Just want to add to the observation that this issue is observed even if there are multiple transfer syntax offered by the MoveSCP/StoreSCU among which even one is unknown private transfer syntax. Since the other offered transfer syntax are standard DICOM compliant ones (like LittleEndian Implicit etc), is there a way to accept the Store request with the standard transfer syntax? (and not reject the store just because one of the transfer syntax offered is unknown)

**Comment by mia-san** [comment]
#703 and #739 seems to be duplicate.

**Comment by gofal** [comment]
On issue #739 I asked if it was duplicate to #703, which was negated. But you think, your pull request (thanks!) also fixes those two issues?

**Comment by mia-san** [comment]
as far as I understand, yes.

#739 is easy to see, same fo-dicom version, same stack trace.

#703 looks different at a glance, but look carefully, it is also caused by
`Dicom.DicomTransferSyntax.Lookup(DicomUID` uid)`


let me explain my understanding again.

in class DicomTransferSyntax:
1 Parse passes what DicomUID.Parse returns anyway down to Lookup.
  1-A.  DicomUID.Parse returns cached UID if it is exist in internal dictionary (_uids), which is expected to have proper type(DicomUidType.TransferSyntax).
  1-B.  otherwise returns ad-hoc UID object with DicomUidType.Unknown. while DicomUID.Parse can't tell what uid type should be for the string, it is reasonable to set DicomUidType.Unknown.
2 Lookup throws if
  2-A. the UID does not exist in its internal dictionary(Entries), and
  2-B. the UID does not have type DicomUidType.TransferSyntax


in case string given to Parse is 1.2.840.10008.1.2(Little Endian Implicit VR), which is well-known transfer syntax uid.
  - exists in _uids.

it should have proper type and Lookup is happy.


in case the string is 1.2.840.113619.5.2(GEPrivateImplicitVRBigEndian), which is private transfer syntax uid.
fortunately, GEPrivateImplicitVRBigEndian is registered into Entries by static constructor, so:
  - does not exist in _uids.
  - exists in Entries.

we're still safe.


in case of #739 and #749, the string is private transfer syntax uid, which is private transfer syntax uid.
unfortunately, it is totally unknown to fo-dicom, so
- does not exist in _uids.
- does not exist in Entries.

now we get exception.


in case of #703, the string is 1.2.840.10008.1.2.2.123456(ImplicitVRBigEndian), defined in DicomTransferSyntax to be pseudo.
ImplicitVRBigEndian is not registered into Entries by static constructor, perhaps being pseudo, so:
- does not exist in _uids.
- does not exist in Entries.

we also get exception.
in other word, ImplicitVRBigEndian is considered unknown private transfer syntax uid.


so I think #703 is duplicate, too.


following one liners may demonstrate my theory.
`DicomTransferSyntax.Parse("1.2.840.10008.1.2.2.123456"); // #703`
`DicomTransferSyntax.Parse("1.2.752.24.3.7.7"); // #739`
`DicomTransferSyntax.Parse("1.2.276.0.50.1.2.1"); // #749`

**Comment by gofal** [comment]
Great explanation, thanks!
So if fo-dicom somehow accepts all transfersyntaxes, do you see a problem with encoding? How does fo-dicom know how to handle data if the transfersyntax is some unknown? Whouldn't that at least require to add encodings to TranscoderManager.Codecs collection for the uid?
Or even if fo-dicom will throw when accessing the pixel data and the transfersyntax is unknown, also reading the dataset requires to know if the transfersyntax is litte or big endian. Currently it is hardcoded that in this case Explicit is ture and Endin is Little. Is this valid?

The fix you commited as pull request is great, because a scp should at least handle the transfersyntax in association request to reject it. currently the associationrequest throws an exception as soon as the client even asks for the transfersyntax, what is not fine. 

But with this fix, fo-dicom would allow to open any file that is stored with any transfersyntax and allow to access the dicom tags, doesn't it? Or are this unsubstantiated worries?

Maybe it should be fine to parse any transfersyntax, but add extra handling if trying to open a file that is encoded in such a unknown transfer syntax. Or allow the user to add ihts own elements to DicomTransferSyntax.Entries collection

**Comment by mia-san** [comment]
good point.

SCP can either accept or reject the transfer syntax during association request, namely OnReceiveAssociationRequestAsync, right ?
so if they accept private transfer syntax, they should know how to handle it, except endianness and VR encoding.


regarding to endianness and VR encoding, we cannot tell if the transfer syntax's endianness or VR encoding from string.
so I love your idea that
> allow the user to add ihts own elements to DicomTransferSyntax.Entries collection

this way, at least they can access to any tags that need to decode/encode pixel data properly.

in practice, 'standard' transfer syntaxes are almost little endian and explicit VR, it would be unlikely that private transfer syntax implies big endian or implicit VR.
so assuming little endian and explicit VR should be safe bet.


regarding to pixel data, if they do not have any interests to pixel data, they should be fine, as far as endianness and VR encoding are correct as above.
if they do want to decode or encode on unknown transfer syntax, exception is thrown anyway, even as of now ? (Dicom.Imaging.Codec.DicomCodecException, IIRC).
if they know how to handle the pixel data, they can access to any tags and raw pixel data, and do what they want.

**Comment by buckstephenh** [comment]
One comment from this perspective is that receiving content is a different concept than displaying, reading tags or manipulation of that content.  Besides receipt and writing to a file which should require no knowledge of contents, it might be possible to iterate through known syntaxes until successful, if the object requires display or manipulation.  The goal of which would be to be generally accepting of unknown syntaxes in order to participate in the “real world”, while perhaps sacrificing or failing at a later stage during tag or image operations.  Tag and image operations could have dynamic controls to change little/big endian, image format, and encoding if they don’t already.  Private syntaxes are apparently quite popular, though the range of actual encoding and image format combinations is relatively narrow.

Maintenance of private syntaxes via predetermine configuration file doesn’t scale in distribution, though it’s better than hard-coded syntaxes. 

So the more dynamic and friendly to unknowns, the better from this perspective.  

Cheers!

Sent from my iPhone

On Dec 2, 2018, at 3:44 PM, Reinhard Gruber <notifications@github.com> wrote:

Great explanation, thanks!
So if fo-dicom somehow accepts all transfersyntaxes, do you see a problem with encoding? How does fo-dicom know how to handle data if the transfersyntax is some unknown? Whouldn't that at least require to add encodings to TranscoderManager.Codecs collection for the uid?
Or even if fo-dicom will throw when accessing the pixel data and the transfersyntax is unknown, also reading the dataset requires to know if the transfersyntax is litte or big endian. Currently it is hardcoded that in this case Explicit is ture and Endin is Little. Is this valid?

The fix you commited as pull request is great, because a scp should at least handle the transfersyntax in association request to reject it. currently the associationrequest throws an exception as soon as the client even asks for the transfersyntax, what is not fine.

But with this fix, fo-dicom would allow to open any file that is stored with any transfersyntax and allow to access the dicom tags, doesn't it? Or are this unsubstantiated worries?

Maybe it should be fine to parse any transfersyntax, but add extra handling if trying to open a file that is encoded in such a unknown transfer syntax. Or allow the user to add ihts own elements to DicomTransferSyntax.Entries collection

**Comment by mia-san** [comment]
another idea is that, just add a functionality that suggested by @gofal
> allow the user to add ihts own elements to DicomTransferSyntax.Entries collection

without  #753.

this way, Entries would maintain "registered" transfer syntax only.

also, regarding @buckstephenh's comment (thanks!)
if might be nice if "register" unknown transfer syntaxes into Entries in DicomTransferSyntax.Lookup dynamically, assuming little endian and explicit VR.

if any transfer syntax is either in big endian or implicit VR, it must be "registered" manually, as UID string doesn't tell us endianness and VR encoding.

**Comment by gofal** [comment]
ok, to sum up. pull request #753 is fine so that the SCP can handle association requests.
If an application wants to open or process a dataset with an unknown transfersyntax, then we assume it to be little endian and explicit VR, what is a very good guess.
In case there is a transfersyntax bit endian or implicit and the user wants to process it, the user ahs to register this in TransferSyntaxes.Entries. If the user wants to process the pixel data, he has to read the raw byte array and do whatever is necessary.

For that, all that is still missing is a public RegisterCustomTransfersyntax method in class TransferSyntaxes that adds an item to Entries (and of course checks for duplicate uids etc). 

Fine with that?

**Comment by buckstephenh** [comment]
Seems like that plan will solve many interop problems.

Sent from my iPhone

On Dec 3, 2018, at 4:33 PM, Reinhard Gruber <notifications@github.com> wrote:

ok, to sum up. pull request #753 is fine so that the SCP can handle association requests.
If an application wants to open or process a dataset with an unknown transfersyntax, then we assume it to be little endian and explicit VR, what is a very good guess.
In case there is a transfersyntax bit endian or implicit and the user wants to process it, the user ahs to register this in TransferSyntaxes.Entries. If the user wants to process the pixel data, he has to read the raw byte array and do whatever is necessary.

For that, all that is still missing is a public RegisterCustomTransfersyntax method in class TransferSyntaxes that adds an item to Entries (and of course checks for duplicate uids etc).

Fine with that?
