### ISSUE TITLE
Building DICOMDIR - Adding files, looking for same patients by ID and name

### ISSUE THREAD

**Issue by martinweihrauch** [fo-dicom/fo-dicom#765]
When using this:
dicomDir.AddFile(dicomFile, String.Format(@"000001{0}", file.Name));

### Expected behavior

Then the method AddFile currently checks, if Patient ID and name are already "known". If yes, then data are added to the existing patient, if no, then a new patient is created.

### Actual behavior

If patient "Miller^Richard" is in one DicomFile and
patient "Miller^Richard^^^" in another, then 2 patients are created. 
I have also seen patient records like this: Miller^^Richard.
So, probably it is a good idea to limit carets to a max. of 1 and trim those at the end:

This may help:
patientName = Regex.Replace(patientName, @"\^+", "^");
char[] charsToTrim = { '^', ' ' };
patientName = patientName.Trim(charsToTrim);

### Steps to reproduce the behavior
s. above

### fo-dicom version and OS/platform
Nuget last version (4.0) and Win 10

**Comment by gofal** [comment]
Removing the double "^^" in the middle is not a good idea. 
Dicom defines the meaning of each component: FamilyName^GivenName^MiddleName^NamePrefix^NameSuffix.
If there are empty fields, then the empty delimiters may be omittet. so Miller^Richard is exactly the same as Miller^Richard^^^, but Miller^^Richard is an other name: there Richard is not the given name but the middle name. 
If a modality software has a bug and generates wrong names then they are about to fix it, But, expect there is a very good reason, fo-dicom should be as standard compilant as possible. 

So instead of comparing the whole string, I will split up the name into components and compare each component separately.
