### ISSUE TITLE
DicomImage WindowCenter & WindowWidth are not taken into account when rendering a 24 bit color image

### ISSUE THREAD

**Issue by janadel** [fo-dicom/fo-dicom#785]
I am trying to render a 24 bits color image but it seems that rendering does not take into account WindowCenter & width set before rendering.

I am not really sure if this is normal or not but I have seen dicom viewers where users are allowed to change window center & widths even for these images.

Thank you.

### fo-dicom version and OS/platform
4.0.0.

**Comment by mia-san** [comment]
are you rendering image of JPEG baseline?
#706 might be a some kind of help?

**Comment by gofal** [comment]
As the title in issue 706 tells, this is some pseudo windowing. Windowing in DICOM standard is only defined for >8bit grayscale images. a 24bit color image ( = 3 x 8 bit for red, green and blue) does not have a windowing since it can be rendered without any loss of information. Please try the code provided by EdwardMarcus and give feedback how it works for you. This code will very likely be added to fo-dicom but I think via some extra method call, not via WindowWith and WindowCenter property, since this is some different than the DICOM-windowing.

**Comment by gofal** [comment]
Yes. Because the ```var bitmap``` in your example holds exactly the same information as the 24bit rgb color pixel data.
You see, this pseudo imaging does not show more information, but rather reduces the available information to some parts that for the user somehow might be more interesting. This is why you can do it afterwards, after the RenderImage method.
