### ISSUE TITLE
DicomServer does not close TCP connection

### ISSUE THREAD

**Issue by mia-san** [fo-dicom/fo-dicom#795]
reported by @cjcaldwell via gitter

### Expected behavior
DicomServer closes TCP connection after client closed connection.

### Actual behavior
DicomServer leaves TCP connection open after client closed connection.

### Steps to reproduce the behavior
send C-ECHO request repeatedly to DicomServer<DicomCEchoProvider> and observe sockets.
see additional comments.

### fo-dicom version and OS/platform
4.0.0

- while #158 seems similar, network codes are getting evolved since then, this issue seems to be different one.

- @cjcaldwell spotted that TcpClient does not get closed.

  DesktopNetworkListener receives TcpClient into local variable.
  https://github.com/fo-dicom/fo-dicom/blob/c1abfb82db5498464b3d3117a14cc6d336e9455b/DICOM/Network/DesktopNetworkListener.cs#L71

  TcpClient is passed to DesktopNetworkStream's constructor.
  but DesktopNetworkStream does not store the reference.
https://github.com/fo-dicom/fo-dicom/blob/c1abfb82db5498464b3d3117a14cc6d336e9455b/DICOM/Network/DesktopNetworkListener.cs#L82

  now, no one has reference to the TcpClient.
  TcpClient leaks without closing.

- WindowsNetworkListener seems to be leaking socket in slightly different manner also.

  WindowsNetworkListener passes new socket to WindowsNetworkStream's constructor.
https://github.com/fo-dicom/fo-dicom/blob/c1abfb82db5498464b3d3117a14cc6d336e9455b/DICOM/Network/WindowsNetworkListener.cs#L115

  WindowsNetworkStream's constructor stores the socket into member variable.
https://github.com/fo-dicom/fo-dicom/blob/c1abfb82db5498464b3d3117a14cc6d336e9455b/DICOM/Network/WindowsNetworkStream.cs#L84

  however, canDisposeSocket is set to false.
https://github.com/fo-dicom/fo-dicom/blob/c1abfb82db5498464b3d3117a14cc6d336e9455b/DICOM/Network/WindowsNetworkStream.cs#L85

  which makes socket leave open.  
https://github.com/fo-dicom/fo-dicom/blob/c1abfb82db5498464b3d3117a14cc6d336e9455b/DICOM/Network/WindowsNetworkStream.cs#L144

  now socket leaks without closing.

- comment on DesktopNetworkListener's constructor says that closing TcpClient is caller's responsibility.
https://github.com/fo-dicom/fo-dicom/blob/c1abfb82db5498464b3d3117a14cc6d336e9455b/DICOM/Network/DesktopNetworkStream.cs#L80

  probably it was at the moment the comment was written, but it is suspicious now.

  WindowsNetworkStream's constructor also has similar comment.
https://github.com/fo-dicom/fo-dicom/blob/c1abfb82db5498464b3d3117a14cc6d336e9455b/DICOM/Network/WindowsNetworkStream.cs#L74

thank you again to @cjcaldwell

**Comment by mia-san** [comment]
//
//  sample C-ECHO SCP
//
﻿using Dicom.Log;
using Dicom.Network;
using System;

namespace ConsoleApp1
{
    internal class Program
    {
        public static void Main(string[] args)
        {
            LogManager.SetImplementation(ConsoleLogManager.Instance);

            using (var server = new DicomServer<DicomCEchoProvider>())
            {
                server.StartAsync(null, 12345, null, null, null, null)
                    .GetAwaiter()
                    .GetResult();
            }

            Console.ReadLine();
        }
    }
}

**Comment by mia-san** [comment]
```
REM
REM request C-ECHO repeatedly with dcmtk echoscu.exe
REM

SET ECHOSCU_PROGRAM=echoscu.exe
SET ECHOSCU_HOST=127.0.0.1
SET ECHOSCU_PORT=12345
SET ECHOSCU_CALLING=ANY-SCU
SET ECHOSCU_CALLED=ANY-SCP

FOR /L %%c IN (1, 1, 100) DO %ECHOSCU_PROGRAM% --aetitle %ECHOSCU_CALLING% --call %ECHOSCU_CALLED% %ECHOSCU_HOST% %ECHOSCU_PORT%

netstat -na | find "%ECHOSCU_PORT%"

pause
```

**Comment by mia-san** [comment]
I found that just letting NetworkStream to keep reference to socket or TcpClient is not enough.

DicomServer<T> takes DicomService-derived class as type parameter.
https://github.com/fo-dicom/fo-dicom/blob/c1abfb82db5498464b3d3117a14cc6d336e9455b/DICOM/Network/DicomServer.cs#L21

DicomService-derived class is instantiated by CreateScp.
https://github.com/fo-dicom/fo-dicom/blob/c1abfb82db5498464b3d3117a14cc6d336e9455b/DICOM/Network/DicomServer.cs#L219

scp is assigned to local variable
https://github.com/fo-dicom/fo-dicom/blob/c1abfb82db5498464b3d3117a14cc6d336e9455b/DICOM/Network/DicomServer.cs#L248

scp's RunAsync is invoked, and scp variable is just forgotten.
https://github.com/fo-dicom/fo-dicom/blob/c1abfb82db5498464b3d3117a14cc6d336e9455b/DICOM/Network/DicomServer.cs#L254

this means that DicomService-derived class would only be disposed via finalizer.

we have to make DicomServer<T> to dispose instance of class T as well.

**Comment by gofal** [comment]
@cjcaldwell found another source for this leak.
Copied from gitter:

`Anyway, terrible timing in terms of something that could've made it into 4.0.1, but one of my colleagues just identified a resource leak.
In DesktopNetworkListener.AcceptNetworkStreamAsync there's a call to Task.WhenAny(_listener.AcceptTcpClientAsync(),Task.Delay(-1,token))
Every time it gets a new connection it calls Task.Delay again.
But those tasks don't end until their token is cancelled, even though there's nothing awaiting them.`

`So when you're getting LOTS of connections (and I am), it slowly chews up memory storing all these abandoned delay tasks.
You could create one delay task and then use it every time (ie, pass it in instead of the CancellationToken)...
... or something like
var cancelSource = new CancellationTokenSource();
var cancelToken = CancellationTokenSource.CreateLinkedTokenSource(token, cancelSource.Token).Token;
var awaiter = await Task.WhenAny(_listener.AcceptTcpClientAsync(), Task.Delay(-1, cancelToken)).ConfigureAwait(false);
cancelSource.Cancel();
Ugh, pasting code here doesn't work how I expect it to.
Anyway, the trick there is to set up a local cancellation source inside the call that can be cancelled to make the Delay task die.`

`CreateLinkedTokenSource makes a token that cancels when either of its parents cancel, so that way it stops when the token in the parameter cancels OR the local source cancels. Then we cancel the local source after the Task.WhenAny completes.`
