### ISSUE TITLE
RemoveUnusedServicesAsync throw exception

### ISSUE THREAD

**Issue by timurposhva** [fo-dicom/fo-dicom#812]
### Expected behavior

DicomService should clear services without errors.

### Actual behavior

Exception removing disconnected clients, System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
```
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Threading.Tasks.Task.WhenAny(IEnumerable`1 tasks)
   at Dicom.Network.DicomServer`1.<RemoveUnusedServicesAsync>d__46.MoveNext()
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Threading.Tasks.Task.WhenAny(IEnumerable`1 tasks)
   at Dicom.Network.DicomServer`1.<RemoveUnusedServicesAsync>d__46.MoveNext()
```

### Steps to reproduce the behavior

Run a DICOM service and send many dicoms to it. Number of senders: 33.

### fo-dicom version and OS/platform
4.0.0, Windows server 2016

**Comment by mia-san** [comment]
just curious, do you see any problem other than exception getting logged?
does 4.0.1 make any difference?

if the exception is logged to be warning, then it should be caught inside RemoveUnusedServicesAsync and practically harmless.

but, member variable _services is simple List<Task> which is not thread-safe, accessed by different tasks asynchronously, namely RemoveUnusedServicesAsync and ListenForConnectionsAsync.
I suppose _services should be guarded by lock construct or such.

**Comment by timurposhva** [comment]
> but, member variable _services is simple List which is not thread-safe, accessed by different tasks asynchronously, namely RemoveUnusedServicesAsync and ListenForConnectionsAsync.
> I suppose _services should be guarded by lock construct or such.

I believe that it will be a good practice to make a thread-safe collection here. I'm doing load testing now. During testing, I received a huge number of errors like "Socket error while reading PDU: ConnectionAborted". After a few minutes of service work, I get stuck on C-Store. Tomorrow I will do a comparative analysis of other versions.

**Comment by cocosip** [comment]
### Expected behavior
`
Dicom.Network|WARN|Exception removing disconnected clients, {"Type":"System.ArgumentException", "Message":"The tasks argument included a null value.\r\nParameter name: tasks", "ParamName":"tasks", "Data":{}, "TargetSite":"Void ThrowArgumentException(System.ExceptionResource, System.ExceptionArgument)", "StackTrace":"   at System.Threading.Tasks.Task.WhenAny(IEnumerable`1 tasks)\r\n   at Dicom.Network.DicomServer`1.RemoveUnusedServicesAsync()", "Source":"System.Private.CoreLib", "HResult":-2147024809}
`

### Actual behavior


### Steps to reproduce the behavior
When client don't send dicom file for a long time ,and can't connect it again。

### fo-dicom version and OS/platform
4.0.3   windows server 2012

**Comment by cocosip** [comment]
Is there any update for this issues? @gofal

**Comment by amoerie** [comment]
I've introduced locking around the _servers field in this PR: https://github.com/fo-dicom/fo-dicom/pull/1058

The "RunningDicomService" class also checks for null values in its constructor, so I can't see when you would ever get a null exception like you described @cocosip
