### ISSUE TITLE
Sending to Philips Pacs 4.4.551 fails

### ISSUE THREAD

**Issue by rogueriver** [fo-dicom/fo-dicom#819]
### Expected behavior
DICOM Sends work

### Actual behavior
Fails (all files)

### Steps to reproduce the behavior
client.Send()

### fo-dicom version and OS/platform
4.0.0, 4.0.1. Al works fine against Philips Pacs 4.4.543. The issue occurs testing against Philips Pacs 4.4.551. Please let me know what other info I need to include, if any

**Comment by rogueriver** [comment]
[fail_DICOMlog.txt](https://github.com/fo-dicom/fo-dicom/files/2994305/fail_DICOMlog.txt)
[success_DICOMlog.txt](https://github.com/fo-dicom/fo-dicom/files/2994306/success_DICOMlog.txt)

**Comment by rogueriver** [comment]
I added a fail log (4.4.551) and a success log  (4.4.543)

**Comment by rogueriver** [comment]
Closed by accident

**Comment by mia-san** [comment]
the issue seems to be triggerd by calling ae title being null, as log suggests
> Calling AE Title:       
> Called AE Title:        STENTORTST_SCP

probably SCP response may differ on null calling ae title.


RawPDU.ToCharArray(String s, Int32 l, Char p) is defined at
https://github.com/fo-dicom/fo-dicom/blob/f481050984c37463c1cdfab986238cc3f7d4ed6d/DICOM/Network/PDU.cs#L340
regarding function definition and exception, it's likely that s is null.

it is called from RawPDU.Write(string name, string value, int count, char pad).
https://github.com/fo-dicom/fo-dicom/blob/f481050984c37463c1cdfab986238cc3f7d4ed6d/DICOM/Network/PDU.cs#L293

it is called from AAssociateRQ.Write as stack trace indicates.
https://github.com/fo-dicom/fo-dicom/blob/f481050984c37463c1cdfab986238cc3f7d4ed6d/DICOM/Network/PDU.cs#L430
as it is used for both calling and called ae title, it is likely that calling ae title is null as we already see.

**Comment by rogueriver** [comment]
I am setting the AE Title to the workstation name in this call:

 client.Send(MainForm.g_IPAddress, MainForm.g_PortNumber, false,
AETitle_Sending, MainForm.g_Server_AE_Title);

I don't know why it is showing as blank. I can add more logging but it is
being set. I'll validate that it is being set.

**Comment by rogueriver** [comment]
You are correct, the sending AE title was blank and didn't get set because it had a space in the value because of a data entry error, plus not checking the field for spaces. This issue can be closed. Thanks!
