### ISSUE TITLE
Slightly incorrect DICOMDIR

### ISSUE THREAD

**Issue by devsko** [fo-dicom/fo-dicom#828]
I have a DICOMDIR containing 1 patient, 1 study, some series and many files. All sequences are parsed successfully and end up in DicomDirectoryReaderObserver. But the offsets to all records but the first are off by 22 bytes. I am sure this is somehow related to the patient name that contains 11 non ASCII characters. In the end DicomDirectory.Open() correctly returns an instance that contains only the patient because all other records are not found where they are meant to be.

I could put together a PR that changes the way the DicomDirectoryReaderObserver searches for records to a less strict way that after resolving all exact offset matches a second round resolves the remaining records also for non exact matches.

What do you think? Would you accept such a PR?

**Comment by gofal** [comment]
So is it a bug in DicomDirectory class? or is the DICOMDIR file invalid because the tag SpecificCharacterSet (0008,0005) is missing?

Anyway: the policy of fo-dicom is to be as strict as possible when creating some data, but be as tollerant as possible when receiving data.
So if it is only a small correction that makes life for some people out there without fo-dicom violating the standard, then such a PR would be of course accepted.

Thanks

**Comment by devsko** [comment]
It's clearly an invalid DICOMDIR because the offsets are wrong. But yes it would help us. Will try not to break anything. I am closing this, PR is coming.
Thanks

**Comment by jasonwurzel** [comment]
@gofal  Friendly ping, could you look into the PR for this (I recreated devsko's PR)
