### ISSUE TITLE
Question about .NET Core 3 support

### ISSUE THREAD

**Issue by devsko** [fo-dicom/fo-dicom#838]
In a view weeks .NET Core 3 (and .NET Standard 2.1) gets released with support for many scenarios that were .NET Desktop only until now. Are there any plans to add a fo-DICOM platform version for this release? It should include more or less the DICOM.Desktop version in respect of files/networking/codecs/imaging. Especially supporting the native JPEG codecs would be interesting.

**Comment by gofal** [comment]
currently the cross platform is PCL, which is rather outdated. I have plans to raise it to .net standard 2.0, where some of the current platform spcific implementations of networking- or filesystem managers are already included.
Since .net standard 2.1 will not be supported by net framework, which is still a very big thing, I personally am not so much interested in net standard 2.1. But maybe someone else is? Pull requests for a new project are wellcome.
