### ISSUE TITLE
Get rid of flaky/unreliable unit tests

### ISSUE THREAD

**Issue by amoerie** [fo-dicom/fo-dicom#868]
### Expected behavior
When unit tests are red, it should mean something is broken.

### Actual behavior
When unit tests are red, it usually helps to run them again. This is not good.
Some tests are testing performance characteristics, which can vary.
Some tests reach out to the internet and download stuff, which can fail.

### Steps to reproduce the behavior
Look at the tests on AppVeyor and inspect the failing builds. It's usually the same 10 suspects.

### Suggested solution
Remove or adapt the unit tests that are flaky to make them solid again.

I would remove performance related unit tests, these belong in Benchmarks or other places.
I would embed files downloaded from the internet in the solution itself, and add them to source control. If the files are really too large, there's always a few techniques we can use, such as git submodules to keep the repository size small.

### List of flaky tests

See https://ci.appveyor.com/project/anders9ustafsson/fo-dicom/builds/24805790/tests

Dicom.Bugs.GH526.OldCStoreRequestSend_VideoFileServerSupportsMPEG2_TransferSuccessful
Dicom.Bugs.GH526.CStoreRequestSend_VideoFileServerSupportsMPEG2_TransferSuccessful
Dicom.Media.DicomDirectoryTest.AddFile_AnonymizedSeries_AllFilesAddedToSamePatientNode
Dicom.Media.DicomDirectoryTest.AddFile_AnonymizedSeries_AllFilesAddedToSameStudySeriesNode 
Dicom.Media.DicomDirectoryTest.AddFile_AnonymizedSeries_AllFilesAddedToDifferentPatientNodes 

See https://ci.appveyor.com/project/gofal/fo-dicom/builds/24805352/tests

Dicom.Serialization.JsonDicomConverterTest.TimeParseTag
Dicom.DicomDictionaryTest.GetEnumerator_ExecutionTime_IsNotSlow

There are some NLog related tests that often fail, because they statically assign some inner property. I've seen these tests fail over and over on my system, oddly enough not that much in CI as I can't find any right now. This is a short list:

Dicom.Bugs.GH258.Log_ExceptionInFormattedString_DisplaysExceptionMessage
Dicom.Bugs.GH258.Log_ExceptionNotInFormattedString_ExceptionLoggedNotIncludedInMessage
Dicom.Log.TextWriterLoggerTest.Log_ToTextWriterLogger_SufficientlyLogged

**Comment by amoerie** [comment]
I'm willing to take up this issue when the DICOM client rewrite PR is merged.

**Comment by gofal** [comment]
Agree, instead of downloading from internet the files could be included in the solution. I did not observe a failure of such a test, to be honest. But maybe because the DicomClient-tests have been such mach flaky that I did not notice it.

Please don't remove the performance related tests, some refactoring caused some performance issues some time ago. It is good to have some performance related tests. But agree, while the own development workstation gives constant performance, the CI build server shares a lot of other build processes and therefore this may flake. 
Instead I could use more apropriate methods. Instead of using `StopWatch` which measures the wall time, I would use the difference of `Process.GetCurrentProcess().UserProcessorTime`
