### ISSUE TITLE
DicomFile.DataSet.TryGetValue should return true if the tag exists but its value is `string.Empty`

### ISSUE THREAD

**Issue by milasch** [fo-dicom/fo-dicom#871]
### Expected behavior
Calling `dicomFile.DataSet.TryGetValue(DicomTag.PatientName, 0, out string patientName)` should return true if the tag `DicomTag.PatientName` exists but its value is `string.Empty`

### Actual behavior
The method returns false.

### Steps to reproduce the behavior
- Use a tool such as dcmtk's dcmodify to set `DicomTag.PatientName` of a dicom file to empty
- Create a console application and open the `DicomFile`
- Call method DicomFile.DataSet.TryGetValue to retrieve the patient name.

### fo-dicom version and OS/platform
fo-dicom.Desktop 4.0.1 on Windows 10.

**Comment by milasch** [comment]
I want to throw an exception if a DICOM tag that should be there isn't, such as patient name.

To do that, on the current state of the fo-dicom design decision, I need to add an extra conditional to test `dicomFile.Dataset.Contains` on the `DicomTag.PatientName`, for example.

**Comment by gofal** [comment]
I am affraid, the wiki entry as well as the api documentation is not clear enough.
Therre are different methods for acessing data. In case of Items with Value Multiplicity greater than 1 the two methods `(Try)GetValue(tag, Index)` and `(Try)GetValues(tag)` are the ones to use. the first one requres an index while the second returns the whole array. In case of Value Multiplicity equal to 1 you can use `(Try)GetSingleValue(tag)` to ommit the 0-index parameter. And there is always the `(Try)GetString(tag)` possible to get the whole value as string.

In your case you call `TryGetValue(DicomTag.PatientName, 0, out string patientname)`. So you want to have the value at index 0 (the first item) of the tag PatientName. Since this tag is present but does not have any value at index 0, the method returns false.
If you would call `TryGetValues(DicomTag.PatientName, out string[] patientnames)` then it would give you true if the tag exists (even if it has length 0) and false if it does not exist. and you then can further test for `patientnames.length == 0` to test if the tag was empty
If you call `TryGetSingleValue(DicomTag.PatientName, out string patientname)`, then you get true if the tag exists (with exactly 1 value or without value), and false if the tag does not exist or if there is an array of values.
And finally you can always call `TryGetString(DicomTag.PatientName, out string patientname)` that returns false if the tag does not exist and returns true if the tag exists with or without value.

I hope this explanation makes it clearer.

**Comment by milasch** [comment]
@gofal Thanks that helps. However, `string.Empty` in my opinion is a valid value in a DICOM tag. So, if the tag exists in the file, but its corresponding value is empty (or what you say, there's no value), in my opinion the method should return `string.Empty`. 

Similarly, one would expect when querying a SQL table and trying to get the value of a single nullable column that is null, that the query will succeed and return null, instead of failing.

That's my opinion, obviously. Thanks for all the hard work.

**Comment by gofal** [comment]
of course string.emtpy is a valid value. And the methods `TryGetString`, `GetGetSingleValue`and `TryGetValues`actually behave exactly as you want. 
But the `TryGetValue` method is the only big exception. It is the only method with the index- parameter you have to pass. It treats the value as an Array and tries to access the n-th item. So `TryGetValue(tag, 0, out...)` is the same as `// pseudocode: (dataset[tag] as object[])[n]`. It converts the value to an array and accesses the indexer. if you convert string.empty to an array you get an 0-length array. and if you then access the 0-nth element of this error, this fails.

**Comment by milasch** [comment]
@gofal Ah, I understand the reasoning behind. Well, thank you for taking the time to explain it.
