### ISSUE TITLE
Unable to create DICOM element of type UL with values of type System.UInt64

### ISSUE THREAD

**Issue by sdekker90** [fo-dicom/fo-dicom#876]
### Expected behavior
I'm trying to add new DICOM tags as a sequence to my dicom file. The expected VR is UL. 

### Actual behavior
I use CULng on my integer, but still the new DICOM tags is not accepted, the message being "Unable to create DICOM element of type UL with values of type System.UInt64". I must miss something here..

### Steps to reproduce the behavior
` Dim sqContent As DicomDataset = New DicomDataset()

Dim intResponse As Integer = InputBox("ImageRegion Xmin")

sqContent.AddOrUpdate(DicomTag.RegionLocationMinX0, CULng(intResponse))`

### fo-dicom version and OS/platform
4.0.1 on Windows 10

Thanks very much for your help

**Comment by gofal** [comment]
Please take a look at the definition of value representation UL (taken from http://dicom.nema.org/dicom/2013/output/chtml/part05/sect_6.2.html)

ULUnsigned Long | Unsigned binary integer 32 bits long. Represents an integer n in the range:0 <= n < 232. | not applicable | 4 bytes fixed
-- | -- | -- | --

So use `CUInt` instead of `CULng`.

**Comment by sdekker90** [comment]
Awesome thank you.
