### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Michael2157** [fo-dicom/fo-dicom#885]
I export from Unity to iOS, run normally in Unity Editor, and test error in Xcode. I don't know where the problem is. Or what assemblies it needs I didn't add.

### Actual behavior
NullReferenceException: Object reference not set to an instance of an object.
  at Dicom.IO.IOManager.get_BaseEncoding () [0x00000] in <00000000000000000000000000000000>:0

### Steps to reproduce the behavior
List<DicomImage> Images {get; private set;} = new List<DicomImage>();
 Images.Add(new DicomImage(file.FullName));

### fo-dicom version and OS/platform
fo-dicom 3.5 ; mac Xcode 10.3

**Comment by frugalspark** [comment]
Seeing a similar error on Windows and Mac standalone platforms using Unity 2019.1.12f1 (and earlier versions) when using IL2CPP as the scripting backend. Note, not seen when building in Unity with Mono scripting backend - however this scripting backend is being phased out. On mobile platforms only IL2CPP is available.

Error occurs when trying to open any Dicom file e.g. 

> Dicom.DicomFile.Open( <path to file>, Encoding.Default );

Resulting in:

> System.NullReferenceException: Object reference not set to an instance of an object.
>   at Dicom.IO.IOManager.CreateFileReference (System.String fileName) [0x00000] in <00000000000000000000000000000000>:0 
>   at Dicom.DicomFile.Open (System.String fileName, System.Text.Encoding fallbackEncoding, System.Func`2[T,TResult] stop, Dicom.FileReadOption readOption) [0x00000] in <00000000000000000000000000000000>:0 

Occurs with current latest fo-dicom commit 9656fd992f662aced6806c3aecae6234e7e02a1b (30 June 2019) and also with v4.0.

**Comment by Michael2157** [comment]
so how can i fix it ?

**Comment by frugalspark** [comment]
@Michael2157, I don't think there's a quick fix, see IL2CPP links above - parts of fo-dicom probably needs to be rewritten to support IL2CPP/AOT compilation.
@gofal , @mia-san, is this something that could be supported?

**Comment by gofal** [comment]
I read something similar on gitter.im on 7th april 2016. Alexandre Tolskenko implemented successfully for unity and he wrote that the code had to be rewritten without any reference to windows, to drop everything related to networking, threading, imaging etc. He wrote

> Thanks for your response I will work in that way. Unity3D uses a custom branch of mono created by them. Their branch is stable and officially support .NET2.0 but has many improvements of others versions such as Linq. My shooting guess is they are working this way in order to support their new IL2CPP(a tool to convert mono IL instructions to CPP to improve performance). Most users says Unity supports approximately .NET3.5 but it lacks new implementations of .NET threads and security. 

Maybe you can try to contact him?

**Comment by gofal** [comment]
@Michael2157 any updates on the issue?
we are currently moving fo-dicom to pure netstandard2.0. Would this help you?

**Comment by Michael2157** [comment]
@gofal sorry, i read some info on IL2CPP,it is too difficult for me,so i prepare to give up

**Comment by zorderjohn** [comment]
I'm facing the same issue.  I think the problem is related to the use of reflection to get the implementations from the assembly. I get exception in "setup.cs", method "GetSinglePlatformInstance",  and more specifically when executing this line:
`var type =
                    assemblies.SelectMany(assembly => assembly.DefinedTypes)
                        .Single(t => t.IsSubclassOf(typeof(T)) && !t.IsAbstract);`

I'll try to make a workaround to avoid the use of reflection here and see if it works.

**Comment by zorderjohn** [comment]
The workaround did the job! 
I replaced the calls to **Setup.GetSinglePlatformInstance** with the concrete implementation for my platform and it works. For instance:

`SetImplementation(Setup.GetSinglePlatformInstance<IOManager>());`
becomes
`SetImplementation(new WindowsIOManager());`

However, this breaks the code for the rest of platforms, so a more elegant and general solution is needed for the repo.

One ugly alternative might be using #defines

**Comment by frugalspark** [comment]
@zorderjohn great going! Can you confirm that the workaround allows fo-DICOM to work under IL2CPP builds in Unity?

**Comment by zorderjohn** [comment]
@frugalspark Thanks! Yes, I loaded a dicom file and extracted the patient ID just fine. I have tested it compiling for x64, not sure about the rest of the architectures.

**Comment by gofal** [comment]
Yes, this reflection causes a lot of issues. It was introduced because fo-dicom should run on many platforms but required a lot of classes that were different in various platforms. So there was the shared project and a lot of platform specific projects implementing the various interfaces. Via reflection fo-dicom tried to load the right implementation.

But this all is legacy. With fo-dicom version 5 this all was built in netstandard2.0. There are no platform specific implementations any more and therefore no loading via reflection. Instead DependencyInjection containers are used where the developer can register a custom implementation.

Please give version 5 a try. See here: https://github.com/fo-dicom/fo-dicom/wiki/Upgrade-from-version-4-to-version-5

**Comment by gofal** [comment]
Rather than trying to fix version 4, I would like to help to make version 5 running smooth in your application

**Comment by zorderjohn** [comment]
Thanks @gofal. I'm just starting to integrate fo-dicom in my application, so it makes sense trying version 5 for future maintainability. I'll let you know how it goes.

**Comment by zorderjohn** [comment]
Hi @gofal . I got fo-dicom v5 running on the Unity Editor just fine. I also managed to compile it to UWP x64, but the DI system throws me an error in execution time. 

> InvalidOperationException: A suitable constructor for type 'FellowOakDicom.IO.FileReferenceFactory' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.

I'm trying to figure out a solution looking at the fo-dicom source code, but maybe you can give me a hint.

This is the test code I'm using:

```
var setupBuilder = new DicomSetupBuilder();
setupBuilder.RegisterServices(s => s.AddImageManager<UnityImageManager>());
setupBuilder.Build();

var dcmfile = DicomFile.Open("test.dcm");
var patientid = dcmfile.Dataset.GetString(DicomTag.PatientID);
```

**Comment by gofal** [comment]
I have no idea. Because FileReferenceFactory does not have a constructor at all - so only the implicit parameterless contructor exists. It's registered as static instance in DI. 
I cannot reproduce it, but maybe if the class FileReferenceFactory requires an explicit parameterless constructor? This would be weird, but would be the only explanation for the exception.

**Comment by zorderjohn** [comment]
I tried making a explicit parameterless constructor for FileReferenceFactory, but it didn't make any difference. Must be something related to Unity's IL2CPP, but to debug it I need to go through the transformed CPP files, and that makes it very difficult. 
I'm afraid I'll have to go back to v4 for now.

**Comment by jbddrexel** [comment]
@zorderjohn @gofal there wouldn't happen to be a Unity asset for FO-DICOM 5 laying around anywhere would there? I have a project that will not build for iOS because of the above-mentioned issue with IL2CPP and I would like to see if I can figure out a workaround so I can get it to run.

I'm not sure what version of FO-DICOM is in the current asset on the Unity store but it I'm guessing FO-DICOM 4? I didn't see any mention of the FO-DICOM version on the asset store so I'm not sure.

**Comment by gofal** [comment]
@jbddrexel The Unity asset has never been a part of the core fo-dicom project, but always a side-project, that Anders Gustafsson updated. But he posted all the sourcecode as attachment within an issue. 
I guess it is a fork of fo-dicom version 3. 
I have no experience in Unity, so I am affraid I cannot help you. do you know, what it would require to have fo-dicom for unity available? since the core library is netstandard2.0 compatible, all it would take is some imaging adapter?

**Comment by jbddrexel** [comment]
@gofal I think I would need to take the fo-dicom 5 source code and build it for Unity. I think I would need to make a native C# plug-in but I don’t really know as I haven’t looked into it too deeply. It would be great to run the latest version of fo-dicom but I’m not sure that would fix the IL2CPP issue.
