### ISSUE TITLE
1.2.840.10008.5.1.4.1.2.2.3 Alternative

### ISSUE THREAD

**Issue by Neuroforge** [fo-dicom/fo-dicom#891]
Hello,

I am working with fo-dicom and dicoogle. The file i am working from is (https://github.com/fo-dicom/fo-dicom-samples/blob/master/Desktop/QueryRetrieve%20SCU/Program.cs)

It is specifically the C-GET request. The C-Find appears to work great!

[ERROR] No accepted presentation context found for abstract syntax: Study Root Query/Retrieve Information Model - GET [1.2.840.10008.5.1.4.1.2.2.3]

I was unable to see any options to alter/add this SOP class in Dicoogle.

Is there another pattern to make fo-dicom work with this PACS server?
Is there any advice on how to make this library work with this dicom server?

Regards,

**Comment by gofal** [comment]
I could not find a dicom conformance statement for dicoogle, but when looking at the code in https://github.com/bioinformatics-ua/dicoogle/tree/dev/dicoogle/src/main/java/pt/ua/dicoogle/server/queryretrieve it is clear to me, that dicoogle only supports C-Find and C-Move, but not C-Get.
C-Move and C-Get are similar, except that C-Get returns the datasets within the same association, while with C-Move you trigger a store on a new association. While C-Get would be so much nicer, only few PACS vendors have implemented it and support it.

So if you want to retrieve images from dicoogle you have to use C-Move instead of C-Get, no mather which dicom library you are using as client.

**Comment by Neuroforge** [comment]
Is there a relevant example of how to achieve this?

I have been working with the fo-dicom Desktop samples for my implementations.

**Comment by Neuroforge** [comment]
It is possible to detect which approach to take with a particular server? i.e. can fo-dicom query the available transfer syntaxes accepted by a server?

**Comment by gofal** [comment]
The QR SCU sample contains all of them: C-Find, C-Get and C-Move. the move starts here: https://github.com/fo-dicom/fo-dicom-samples/blob/ce8c6b3a4e7f86c9f280abdcab82cae7f9033fc0/Desktop/QueryRetrieve%20SCU/Program.cs#L82
The difference is, that you mast have a store scp running somewhere and the PACS needs to know the connection data from this store scp. then you send this C-Move Request with an DestinationAETitle where to send the images. The responses of the C-Move Request are only short messages if the sending is still in progress or when the sinding is finished.

**Comment by gofal** [comment]
The first thing is when you connect to a system is, to read the DICOM Conformance Statement. If you are developing an application that interacts with others, you should also write your DICOM Conformance Statement to give it to other vendors. There you will find, which DICOM services are supported. But if you want to have some kind of "general purpose" client, then let your application to a c-Get in the first run. And if you then receive this error "No accepted presentation context found for abstract syntax: Study Root Query/Retrieve Information Model - GET", then you can write a configuration file that says not to use the C-Get any more. And then you call a C-Move. on the next run you know what is supported.

**Comment by Neuroforge** [comment]
Thank you.
