### ISSUE TITLE
DicomFile.Open with SkipLargeTags throws "Unexpected tag" when other options do not

### ISSUE THREAD

**Issue by ivantarapov** [fo-dicom/fo-dicom#893]
This might be related to #763, but actually seems like a bug to me. 

The ReadAll option can read the files that are not quite valid and allow me to parse them while SkipLargeTags option results in an exception. 

I'm attaching two files that trigger this: one is actually coming from [RSNA Kaggle challenge](https://www.kaggle.com/c/rsna-pneumonia-detection-challenge), so this is definitely the case where people would have a legitimate need to parse the file even if some sequences are not correct. The other file is synthetic and is an Explicit VR Little Endian file while transfer syntax is manually set to JPEG Process 1.

[ImageSamples.zip](https://github.com/fo-dicom/fo-dicom/files/3484294/ImageSamples.zip)

### Expected behavior
DicomFile.Open(file, FileReadOption.SkipLargeTags) behaves similarly to other options that read the file fully

### Actual behavior
DicomFile.Open(file, FileReadOption.SkipLargeTags) throws "Unexpected tag in DICOM fragment sequence" while DicomFile.Open(file, FileReadOption.ReadAll) does not (neither does ReadLargeOnDemand).

### Steps to reproduce the behavior
Run `DicomFile.Open(file, FileReadOption.SkipLargeTags)` and `DicomFile.Open(file, FileReadOption.ReadAll)` with the two attached files.

### fo-dicom version and OS/platform
4.0.1
.Net Core 2.2

**Comment by gofal** [comment]
Found the reason. When the large tag is skipped, then an empty buffer is returned, but unfortunately the cursor within the stream was not set to the end of the skipped bytes. Since pixeldata is typically the very last tag within a dataset, this was not an issue until now. Your files contain fragments in pixeldata which are skipped and the pixeldata tag then has to be read to the end.
