### ISSUE TITLE
SourceApplicationAET of dicom file overwritten with hostname during Save

### ISSUE THREAD

**Issue by SrividyaTR** [fo-dicom/fo-dicom#895]
### Expected behavior
The SourceApplicationAET, if present in the original dicom file should be retained on Saving a DicomFile

### Actual behavior
SourceApplicationAET is replaced with the hostName during Save

### Steps to reproduce the behavior
var file = DicomFile.Open(filePath);
string sourceAET = file.FileMetaInfo.SourceApplicationEntityTitle;
           
file.Save(newFilePath);
var file2 = DicomFile.Open(newFilePath);
sourceAET = file.FileMetaInfo.SourceApplicationEntityTitle;

### fo-dicom version and OS/platform
4.0.1 windows/x64

**Comment by gofal** [comment]
The Dicom File Meta Information has to be updated if the file is written, either if it was created newly or received/copied from any other source. The SourceApplicationAET has to contain the AET of who last wrote/updated the file, so it has to be updated on writing. See http://dicom.nema.org/medical/dicom/current/output/chtml/part10/chapter_7.html#sect_7.1 and the explation from David Clunie himself https://groups.google.com/d/msg/comp.protocols.dicom/gGFooa7b7xE/2a6gTBRiBgAJ
Since fo-dicom does not know the AETitle, there was a discussion if it should either deleted or if it should write the hostname. Because the intention of the Source Application AET is the traceability, the result of the discussion was that it is better to write the hostname than to always clear it. 

So this behaviour is as designed.

But I am open to discussion. Not to change the SourceApplicationAET is against Dicom Standard, so this will not be implemented in fo-dicom. But any other ideas? What could be a better default than the hostname?

**Comment by SrividyaTR** [comment]
Thanks a lot for clarifying the intent of the SourceApplicationAET tag. We are actually looking for a way to find out the node who originally created the dicom file. So, SourceApplicationAET tag would not help here. Can you pls let us know how we could know information (eg: AET) about the original node who initially created a dicom file?

**Comment by gofal** [comment]
We use the dicom tags "0008,0070 Manufacturer", "0008,1010 Station Name", "0008,1090 Manufacturers Model Name" or "0040,0241 Performed Station AE Title". Sadly not all vendors write all of these tags. So some write the Manufacturer and Station Name, other vendors write the Performed Station AE Title for example. You have to check the tags of the images you are processing.

**Comment by SrividyaTR** [comment]
Thanks a lot for your response. We already use "0008,0070 Manufacturer", "0008,1010 Station Name", "0008,1090 Manufacturers Model Name", but with this combination, we were still unable to uniquely identify a scanner. (especially when a single institution has multiple scanners of the same manufacturer and model). Your hint on "0040,0241 Performed Station AE Title" is useful. We will see if we can make use of it. In case you have any further suggestions on this topic, do let us know. Else you can close this topic.
