### ISSUE TITLE
A basic question on imaging

### ISSUE THREAD

**Issue by saschke** [fo-dicom/fo-dicom#906]
While I have worked successfully with the communication part of fo-dicom I never touched imaging. Today I did with little success.

 DicomFile imageFile = await DicomFile.OpenAsync(@"E:\DicomBilder\US\b1.dcm");
 var dicomImage = new **DicomImage(imageFile.Dataset);**

gives me the Exception

_**Dicom.Imaging.Codec.DicomCodecException: "Decoding dataset with transfer syntax: JPEG Baseline (Process 1): Default Transfer Syntax for Lossy JPEG 8 Bit Image Compression is not supported."**_

I guess I am missing something. Can someone help me out what?

Thank you so much.

-Schlomo

**Comment by gofal** [comment]
You are building in .net core, aren't you?
A big topic when doing imaging is the encoding of pixel data. fo-dicom ships with full support of codecs when you build on net framework, because it uses native built codecs. But when you use more portable platforms then not all compressions are supported. See here:
https://github.com/fo-dicom/fo-dicom/wiki/Supported-Transfer-Syntaxes

Happily there is a company that published some codec implementations for fo-dicom which run on windows and linux if you build for net core. Take a look at this issue: https://github.com/fo-dicom/fo-dicom/issues/886#issuecomment-522423070

**Comment by gofal** [comment]
Ah, one more thing to note: if you are building net framework, then you have to explicitly build x86 or x64, not AnyCpu. Because fo-dicom has to know which native libraries to load for codeds. So if you build AnyCpu it might also happen, that no codecs are found.

**Comment by saschke** [comment]
Ahhh, thats it. Thank you!

Dr. med. S. Aschkenasy 
FMH Kardiologie 
Psychotherapie
Klosbachstrasse 104 
8032 Zürich 

Tel 044 252 45 60 
Fax 044 252 45 66 

www.herzdoktor.ch 
praxis@herzdoktor.ch
