### ISSUE TITLE
Is there a way to disable transcoding the image data when sending dicom instance

### ISSUE THREAD

**Issue by hc7510** [fo-dicom/fo-dicom#920]
### Expected behavior
A configuration to disable image data transcoding when the accepted transfer syntax is different from the actual transfer syntax of the dicom instance. It should fail if the transfer syntaxes are different. 

### Actual behavior
The image data was transcoded when the accepted transfer syntax is different from the actual transfer syntax of the dicom instance. 

### Steps to reproduce the behavior
Send a dicom instance to a SCP which doesn't support the transfer syntax of the instance but Little Endian Implicit.

### fo-dicom version and OS/platform
4.0.1, Windows 10

**Comment by gofal** [comment]
Hm, but thats how DICOM works. The Store SCU sends a request and offers various transfer syntaxes. The Store SCP then decides which transfer syntax to use. ImplcitLittleEndian is the only mandatory transfer syntax which every service has to offer/support (part 5, 10.1).

The `DicomRequest`, which is a base class for `DicomCStoreRequest`, has a method `CreatePresentationContext` to override the creation of presentation contexts. But since DICOM standard requires ImplicitLittleEndian to have available, this mechanism is not used for DicomCStoreRequests.

So there is currently no way to disable decoding. This would be an enhancement. But where to hook in? Breaking the standard and explicitly set the presentationcontexts without LittleEndianImplicit? Or having some event just before the DicomCStoreRequest is sent with the possiblility to cancel/break the request?

**Comment by hc7510** [comment]
Thank you, Reinhard! The reason why we want to disable this feature is because we don't want to manipulate the image dataset as our software is only doing archiving. However I guess you are right it is required by the DICOM standard. 
I am trying to solve this in our application code. My plan is to handle AssociationAccepted event and check the accepted transfer syntax against the instance transfer syntax. If they are different, throw an exception to stop the transaction. Do you see any issues in this approach?
Thanks,

**Comment by gofal** [comment]
No, I dont see any issue. Except that you then will never be able to send the image to the other archive.

If you are really building an archive where you never want to manipulate images AND you want to be DICOM conformant, then your receiving Store SCP should reject every transfersyntax except ImplicitLittleEndian. This forces the other clients, that send the images to you to decode the images and you will always be able to send the images to any other receiver.

**Comment by gofal** [comment]
I close this due to inactivity.
If my suggestion did not help, or you still face any problems, please reopen this issue again.
