### ISSUE TITLE
New Dicom.Network.Client.DicomClient does not linger in blocking mode

### ISSUE THREAD

**Issue by vbaderks** [fo-dicom/fo-dicom#930]
### Expected behavior
Association is not closed between sending requests

### Actual behavior
Association is closed

### Steps to reproduce the behavior
I have a small C-STORE SCU test application that does the following:

```
var client = new DicomClient(s_serverHost, s_serverPort, false, s_ownAet, s_serverAet);
client.NegotiateAsyncOps();

var dicomFile = DicomFile.Open(fileName);

// .. updating the dicomFile...

for (int i = 0; i < 1000; i++)
{
    var instanceUid = DicomUID.Generate();
    dicomFile.Dataset.AddOrUpdate(DicomTag.SOPInstanceUID, instanceUid);
    var request = new DicomCStoreRequest(dicomFile);
    client.AddRequestAsync(request).Wait();
    client.SendAsync().Wait();
}

```
When I use this test application to send test images to a C-STORE SCP running on the same computer I see that the association is closed and re-created.
Am I doing something wrong? or is this behavior by design? I am using Wait() calls to ensure that I don't update the instance UID while the DicomClient is sending the instance.

### fo-dicom version and OS/platform
Fo-dicom v4.0.3 on Windows 10

**Comment by amoerie** [comment]
This is expected behavior. 

Some notes:

1. You should not call .Wait() on async APIs, it's better to make your methods async and await the results instead of blocking your application.
2. You should add all of the requests to the client and then call SendAsync once if you want them to be sent over the same connection. DicomClient.SendAsync will complete when all queued requests are sent and the association is cleaned up.
3. If you still want to send your requests one by one, you can use DicomClient.NegotiateAsyncOps(1,1) to ensure only one request is sent at a time.

**Comment by vbaderks** [comment]
thanks for the quick reply. 

I have only 1 DicomFile in memory that I am updating and resending all the time. This DicomFile is passed as reference to AddRequestAsync. I assume that AddRequestAsync does not makes a copy of it. How do I know when the DicomClient is finished with sending and my code can update the UIDs for the next send action?

**Comment by amoerie** [comment]
You could use the OnResponse property of each request to add another request as you see fit.

**Comment by vbaderks** [comment]
Thanks for the tip. I have reworked the loop to add the next instance in the OnResponse delegate and now everything is working with an excellent performance.
