### ISSUE TITLE
Async event handlers for Dimse events from DicomService are missing

### ISSUE THREAD

**Issue by rickardraysearch** [fo-dicom/fo-dicom#935]
### Expected behavior
It is possible to implement a fully async DicomService.

### Actual behavior
Requests are not possible to handle asynchronously.

### fo-dicom version and OS/platform
development / Windows and netcore

**Comment by rickardraysearch** [comment]
I started a solution proposal in #936

**Comment by gofal** [comment]
netstandard2.1 will not be supported by netframework any more. But .net framework is still a very widely used platform. Specially the support for codecs in fo-dicom is only fully available in .net framework. Thats why I really want the code to be compilable in netstandard2.0

**Comment by amoerie** [comment]
Great! We had the same idea! See https://github.com/fo-dicom/fo-dicom/pull/925

Adding support for IAsyncEnumerable would be ideal of course, but I didn't want to add a target for .NET core 3.0 without first discussing this with other contributors.

**Comment by rickardraysearch** [comment]
Argh - I missed that PR! Sorry for repeating stuff.

About the netstandard2.1 issues: I tried to keep everything that goes into DICOM.Desktop compatible with .NET Framework, and only upgraded projects specific to DICOM.NetCore to netstandard2.1. Is it also problematic to upgrade the DICOM.NetCore projects to use netstandard2.1, and keep DICOM.Desktop on Framework compatible versions?

**Comment by gofal** [comment]
No, that would not be problematic.
But the further plan is, to drop these platform specific implementations and go forward with one netstandard library. Of course it would then need additional libraries for platform specific implementations as encodings or support for system.drawing in net framework. 
The current projects will not be replaced or deleted, the netstandard library will be a additional library, but enhancements and so on will be implemented there.

**Comment by amoerie** [comment]
I agree that having a .NET Standard 2.0 library would make our lives a lot easier. 

We could investigate how we can add proper support for AsyncEnumerable in .NET Standard 2.1. It's not just a matter of adding an extra library, since the DicomService class and friends need to be aware of the specific implementations. We would have to provide hook points that automatically light up according to the target platform.

**Comment by rickardraysearch** [comment]
@amoerie : Doesn't making DicomService.PerformDimseAsync `protected virtual` instead of `private`, as in the linked PR make that possible?

**Comment by amoerie** [comment]
You're breaking a few assumptions there if you do this:

- Logging of the DICOM message always happens before it is handled. Because you override this order, it is now possible that code crashes and the DICOM message is not logged.

- There is a check whether the DicomMessage is a response and not a request. Is it important that this check happens first? Maybe.

- ICStoreProvider.OnCStoreRequestException is called from DicomService.ProcessPDataTFAsync, and must only be called when an exception occurs in a specific part of the code. How will you solve this just with inheritance?

In an early stage, we can split up the logic of DicomService in smaller methods so that we can make more precise cuts in the logic using inheritance.

But in the long run, we should look into how things are done in .NET Core, which is using dependency injection. Right now, DicomService instances are created using Activator.CreateInstance, but it would be much better to use the built in DI framework provided by .NET core if possible.

That would open up a lot of new possibilities, one of which is better support for scenarios like this where we want to "compose" parts of the DicomService.

**Comment by rickardraysearch** [comment]
> You're breaking a few assumptions there if you do this:
> 
> * Logging of the DICOM message always happens before it is handled. Because you override this order, it is now possible that code crashes and the DICOM message is not logged.
Sure. That's part of what I tried to convey with "started a solution proposal"...

> * There is a check whether the DicomMessage is a response and not a request. Is it important that this check happens first? Maybe.
If DicomMessage.IsRequest(dimse.Type) returns false for any of the types I handled in the override, that would be a bug there, right? If another override was added, I would hope that there was a good reason for that.

> * ICStoreProvider.OnCStoreRequestException is called from DicomService.ProcessPDataTFAsync, and must only be called when an exception occurs in a specific part of the code. How will you solve this just with inheritance?
Since I don't really touch the CStore handlers, I don't see the problem. OnCStoreRequestException is as you say only called when exceptions are thrown from the weird rebaking of the dataset to a DicomFile, which is not affected by anything I am touching there.

> In an early stage, we can split up the logic of DicomService in smaller methods so that we can make more precise cuts in the logic using inheritance.
That sounds like a plan. I'll sketch a new solution.

> But in the long run, we should look into how things are done in .NET Core, which is using dependency injection. Right now, DicomService instances are created using Activator.CreateInstance, but it would be much better to use the built in DI framework provided by .NET core if possible.
>
> That would open up a lot of new possibilities, one of which is better support for scenarios like this where we want to "compose" parts of the DicomService.
I completely agree - and this is a great long-term direction.

Thanks for the detailed feedback!

**Comment by amoerie** [comment]
You're welcome! I'm looking forward to your adapted proposal!

**Comment by amoerie** [comment]
I think this issue can be closed. Support for async enumerable should be a new issue, if anyone is still requiring this feature.
