### ISSUE TITLE
How do we get around this error

### ISSUE THREAD

**Issue by Yoda-Man** [fo-dicom/fo-dicom#946]
Decoding dataset with transfer syntax: JPEG Lossless, Non-Hierarchical, First-Order Prediction (Process 14 [Selection Value 1]): Default Transfer Syn

tax for Lossless JPEG Image Compression is not supported.

I have attached a sample file

**Comment by gofal** [comment]
First of all take a look at this wiki-page: https://github.com/fo-dicom/fo-dicom/wiki/Supported-Transfer-Syntaxes
Depending on the platform you are building, not all transfer syntaxes are supported.

If you are building for desktop but stil get this message, then build explicit in x86 or x64, not in AnyCpu. Thats because the native codecs have to be linked on building and there fo-dicom needs to know which of the native dlls to link.

if you are building netcore, then take a look at https://github.com/Efferent-Health/Dicom-native. They shared their codec that runs on every netcore platform.

**Comment by Yoda-Man** [comment]
> First of all take a look at this wiki-page: https://github.com/fo-dicom/fo-dicom/wiki/Supported-Transfer-Syntaxes
> Depending on the platform you are building, not all transfer syntaxes are supported.
> 
> If you are building for desktop but stil get this message, then build explicit in x86 or x64, not in AnyCpu. Thats because the native codecs have to be linked on building and there fo-dicom needs to know which of the native dlls to link.
> 
> if you are building netcore, then take a look at https://github.com/Efferent-Health/Dicom-native. They shared their codec that runs on every netcore platform.

Thank you it worked
