### ISSUE TITLE
Decoding dataset with transfer syntax: JPEG Lossless, Non-Hierarchical, First-Order Prediction (Process 14 [Selection Value 1]): Default Transfer Syntax for Lossless JPEG Image Compression is not supported

### ISSUE THREAD

**Issue by Sicos1977** [fo-dicom/fo-dicom#948]
### Expected behavior
Converting DICOM file to JPG

### Actual behavior
Throwing error: Decoding dataset with transfer syntax: JPEG Lossless, Non-Hierarchical, First-Order Prediction (Process 14 [Selection Value 1]): Default Transfer Syntax for Lossless JPEG Image Compression is not supported

### Steps to reproduce the behavior
var image = new DicomImage(inputFile.FileName);
image.RenderImage().AsSharedBitmap().Save(tempFileName);

I can't post the file that is giving the error because it is a medical file.

### fo-dicom version and OS/platform
NuGet package: fo-dicom v4.0.3 on Windows 2012 R2 server

**Comment by Sicos1977** [comment]
Another question, is there some way to get the image data so that I can save it as JPG myself?

**Comment by DMIAOCHEN** [comment]
Is the Dicom.Native library not loaded successfully?

**Comment by Sicos1977** [comment]
Yes it is, I debugged the source code today and it just cant find a coded to decode it. So I guess it is really not supported.

**Comment by gofal** [comment]
First of all take a look at this wiki-page: https://github.com/fo-dicom/fo-dicom/wiki/Supported-Transfer-Syntaxes
Depending on the platform you are building, not all transfer syntaxes are supported.

If you are building for desktop but stil get this message, then build explicit in x86 or x64, not in AnyCpu. Thats because the native codecs have to be linked on building and there fo-dicom needs to know which of the native dlls to link.

if you are building netcore, then take a look at https://github.com/Efferent-Health/Dicom-native. They shared their codec that runs on every netcore platform.

**Comment by mia-san** [comment]
this question is asked time to time, perhaps we should make the issue as 'Pinned issues', which appears on top of 'Issues' page.

regarding to Any CPU build on desktop environment, copying both Dicom.Native.dll and Dicom.Native64.dll may help.
fortunately, fo-dicom seems to pick up proper dll on the fly in Any CPU build.

**Comment by gofal** [comment]
There is a wiki-entry for this: https://github.com/fo-dicom/fo-dicom/wiki/Native-codecs-on-.NET
and if someone having this problem searches the issues then he will find the answer. So anyone having this issue should find the answer.

@Sicos1977 just for interest: where did you search for a solution before you opened this issue?

I wonder If I should add a link to the wiki-entries into the exception message of the `DicomCodecException`, just like you sometimes get links to msdn pages from framework-internal exceptions?

**Comment by mia-san** [comment]
@gofal

wiki page is good, but I think the page should mention the exception message to make their life easier:
> JPEG Lossless, Non-Hierarchical, First-Order Prediction (Process 14 [Selection Value 1]): Default Transfer Syntax for Lossless JPEG Image Compression is not supported.

btw, the issue is already tried to be addressed at compile time warning like so:
fo-dicom native libraries require the target platform to be explicitly specified. Change 'ConsoleApplication1' Platform Target Build Project Property from 'AnyCPU' to either x86 or x64 to remove this message.
but people tend to misses the message and get surprised by runtime exception (and create new issue).

also, the exception message is not obvious about missing native dlls without logging.
it just says 'not supported', not 'not supported due to missing native dll, possibly Any CPU build'.

so what about:
1. putting link in exception message as you said.
2. put exception message into wiki page.
//

**Comment by gofal** [comment]
added the exception to wiki page
