### ISSUE TITLE
Render Error when DX with VOI LUT Sequence[0028,3010] tag

### ISSUE THREAD

**Issue by DMIAOCHEN** [fo-dicom/fo-dicom#949]
hi all~
This is source [dicom file](https://github.com/DMIAOCHEN/RawGit/blob/master/Dicoms/ErrorDx.dcm?raw=true)

this file is well in v4.0.1, like this:
![Correct render](https://raw.githubusercontent.com/DMIAOCHEN/RawGit/master/Images/CorrectDX-4.0.1.jpg)

and now with v4.0.3 render:
![Some Error](https://raw.githubusercontent.com/DMIAOCHEN/RawGit/master/Images/ErrorDX-4.0.3.jpg)

i debug the source found that:
```csharp
        public GenericGrayscalePipeline(GrayscaleRenderOptions options)
        {
            _options = options;
            if (options.ModalityLUTSequence != null)
                _modalityLut = new ModalitySequenceLUT(_options);
            else if (_options.RescaleSlope != 1.0 || _options.RescaleIntercept != 0.0)
                _modalityLut = new ModalityRescaleLUT(_options);
            
            // so this code cause the problem, when i remove this it will be ok
            if(_options.VOILUTSequence != null) _voiSequenceLut = new VOISequenceLUT(_options);
            // end
            _voiLut = VOILUT.Create(_options);
            _outputLut = new OutputLUT(_options);
            if (_options.Invert) _invertLut = new InvertLUT(_outputLut.MinimumOutputValue, _outputLut.MaximumOutputValue);
        }
```
Is this a bug? Or after applying this property, is it displayed like this?

**Comment by aerik** [comment]
Pretty sure that's a bug.  _voiLut OR _voiSequenceLut should be used, but not both.

See http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.11.2.html

it says, "If any VOI LUT Table is included by an Image, a Window Width and Window Center or the VOI LUT Table, **but not both**, may be applied to the Image for display. Inclusion of both indicates that multiple alternative views may be presented."

**Comment by gofal** [comment]
Agree, the windowwidth/windowcenter windowing shall not be applied. 
I introduced an property `UseVOILUT` in DicomImage class. If there is an voilut but you want to apply some kind of windowing, then you can set this property to false and then the properties `WindowWidth` and `WindowCenter` are applied.

now you image looks like that:
![image](https://user-images.githubusercontent.com/6769246/72531059-008e3100-3871-11ea-9cce-a17042040368.png)
Its better than in version 4.0.1, where the VOI LUT was not applied at all, because the light areas are not so blured out.

**Comment by DMIAOCHEN** [comment]
Great! :+1:, is time to close this issue
