### ISSUE TITLE
ThreadPoolQueue dead lock issue

### ISSUE THREAD

**Issue by Thunderstriker** [fo-dicom/fo-dicom#95]
The order of locking is different in Queue and ExecuteProc function which leads to deadlocks in some cases
```C#
        private void Queue(WorkItem item)
        {
            lock (_lock)  //<-- HERE
            {
                WorkGroup group = null;
                if (!_groups.TryGetValue(item.Group, out group))
                {
                    group = new WorkGroup(item.Group);
                    _groups.Add(item.Group, group);
                }

                lock (group.Lock) group.Items.Enqueue(item);  //<-- HERE

                Execute(item.Group);
            }
        }
```

```C#
        private void ExecuteProc(object state)
        {
            var group = (WorkGroup)state;

            do
            {
                if (_stopped) return;

                WorkItem item = null;

                bool empty;
                lock (group.Lock)
                {
                    empty = group.Items.Count == 0;

                    if (!empty) item = group.Items.Dequeue();
                }

                if (empty)
                {
                    var linger = DateTime.Now.AddMilliseconds(Linger);
                    while (empty && DateTime.Now < linger)
                    {
                        Thread.Sleep(0);
                        lock (group.Lock)
                        {
                            empty = group.Items.Count == 0;

                            if (!empty) item = group.Items.Dequeue();
                        }
                    }

                    if (empty)
                    {
                        lock (group.Lock)  //<-- HERE
                        {
                            group.Executing = false;

                            lock (_lock)  //<-- HERE
                            {
                                if (!group.Key.Equals(DefaultGroup)) _groups.Remove(group.Key);

                                return;
                            }
                        }
                    }
                }

                try
                {
                    if (item.Action != null) item.Action();
                    else if (item.Callback != null) item.Callback(item.State);
                }
                catch
                {
                    // log this somewhere?
                }
            }
            while (true);
        }
```

**Comment by IanYates** [comment]
Well spotted!  

I've not looked through the `ThreadPoolQueue` class in any depth at all, but based on the excerpt here, it seems that changing

                    if (empty)
                    {
                        lock (group.Lock)  //<-- HERE
                        {
                            group.Executing = false;

                            lock (_lock)  //<-- HERE
                            {
                                if (!group.Key.Equals(DefaultGroup)) _groups.Remove(group.Key);

                                return;
                            }
                        }
                    }

to

                    if (empty)
                    {
                        lock (_lock)  //<-- HERE
                        lock (group.Lock)  //<-- HERE
                        {
                            group.Executing = false;
                            if (!group.Key.Equals(DefaultGroup)) _groups.Remove(group.Key);

                            return;                            
                        }
                    }

would be reasonable (probably with some extra curly braces).

Did you want to do a PR?

**Comment by IanYates** [comment]
Although PR #94 (which I'm reading through now)changes this to use a timer and doesn't have the double lock.  I'll need to read through it more.  

I'll close this now simply because it'll not apply shortly anyway.  Thanks for raising it though and bringing careful ordering of locking to our attention :)

**Comment by anders9ustafsson** [comment]
Very well spotted indeed, @Thunderstriker !

As @IanYates points out, I have made some modifications in `ThreadPoolQueue` within PR #94, but these modifications do not affect the validity of this issue report.

I have tried to come up with a unit test case that would consistently induce the deadlock, but so far I have not been able to come up with anything. Any suggestions?

When it comes to solutions, I am thinking along two tracks, not sure which one is the best:

1. Avoid enclosing one `lock` inside another. As far as I can tell right now, it should be possible to limit the `lock` scopes so that no `lock` is placed inside an outer lock.

2. Remove the `Lock` field from `WorkGroup` and use the single `_lock` variable everywhere.

For minimal changes, I am leaning towards using option 1 right now, but maybe I am not thinking straight. What are your thoughts? Are there better options?

**Comment by IanYates** [comment]
@anders9ustafsson - I think reordering them as suggested is probably enough.

Threading code is always fun and needs more reasoning than I can give it today.  I made a comment in PR #94 because it has changed the behaviour of this bit of code.  I closed this issue on the basis that #94 would be ready soon.  If that's not the case then yes, let's leave this open and PR the fix I suggested.

Slightly off topic - more for PR #94 and its follow-on: In the long run, if we're going async/await everywhere, it's better to not use lock anyway.  I use AsyncLock (https://github.com/StephenCleary/AsyncEx#asynclock) extensively as it gives locking semantics whilst being very happy with async/await.  Whether we take a dependency on that project, or just take AsyncLock and include that one file as an internal class (after checking the licence), I'll leave up for discussion.

**Comment by Thunderstriker** [comment]
@anders9ustafsson its very hard to consistently induce putting the Linger timout to 0 will greatly increase the amount of times it happens  but still not fails alot.

I agree with @IanYates reordering should be good enough but we have another issue.
As there is no lock between the moment we determine the group is empty and we go on to remove it there is a moment a new item can be added and its actually possible to remove a non empty group now.

```C#
					var linger = DateTime.Now.AddMilliseconds(Linger);
					while (empty && DateTime.Now < linger) {
						Thread.Sleep(10);
						lock (group.Lock) {
							empty = group.Items.Count == 0;

							if (!empty)
								item = group.Items.Dequeue();
						} //<-- FROM HERE
					}

                    if (empty)
                    {
                        lock (group.Lock)//<-- TO HERE
                        {
							group.Executing = false;

                            lock (_lock)
                            {
								if (!group.Key.Equals(DefaultGroup))
									_groups.Remove(group.Key);

								return;
							}
						}
					}
```

**Comment by anders9ustafsson** [comment]
Thanks @IanYates and @Thunderstriker for this additional input. If I interpret you correctly, I should then reorder the locks to avoid that one lock occurs inside another. And, I will also make sure that group removal is made more reliably than it is right now. I will update `ThreadPoolQueue` via PR #94.

**Comment by anders9ustafsson** [comment]
@Thunderstriker @IanYates I have made several attempts to solve the problem described in this report, but so far I have failed miserably. As far as I can tell, the current implementation works well, and I am unable to trigger the expected deadlock. Therefore I will not try to solve the issue within the scope of PR #94, but I will leave this issue open for others to come up with more reliable fixes than I managed to accomplish.

**Comment by anders9ustafsson** [comment]
As part of #116 , I have removed the `ThreadPoolQueue` successor `TaskQueue` altogether, which means that this deadlock issue is no longer relevant to the current source code. Nevertheless, @Thunderstriker , many thanks for being so observant!
