### ISSUE TITLE
How to get the string value by Group and Element of an dicom file?

### ISSUE THREAD

**Issue by dwanboweb** [fo-dicom/fo-dicom#956]
I just want's to get the string value(to save to our database) of the tag by Group and Element and don't care the type of the data. How do I do that?
As the DicomStringElement.StringValue is private and ToString() include other infomations that I don't want(I just need the stringValue).
Thank you so much.

**Comment by gofal** [comment]
The method you are looking for is `var value = dataset.GetString(dicomTag)` or  `dataset.TryGetString(dicomTag, out var value)`.
if you do not have the dicomtag, but really only group- and elementnumber, then use `var value = dataset.GetString(new DicomTag(group, element))`

**Comment by dwanboweb** [comment]
Thank you.Before your comment I tried to write code like :
`var item = dicoms.FirstOrDefault(d => d.Tag.Group == group && d.Tag.Element == element);
if (item is DicomElement aitem)
return aitem.Get<string>()`
And later,I try to use `dicoms.GetString` .But some Elements can't Get by `dataset.GetString`,But can be got by DicomElement.Get<string>.
Such as an Element: "aitem = Tag: "Chemical Shift" ("2001","1001"), VR: "FL", VM: 1, Value: "0" ,which  throws out a message "Dicom.DicomDataException:“Tag: (2001,1001) not found in dataset” .
What's wrong with it?
Thank you very much

**Comment by rcd** [comment]
I think the problem is that (2001,1001) is a private tag, which means you need to specify the private creator of the tag. The following are a few examples of how to get a string value from a `DicomDataset`. The last example specifies a private creator for the tag. You will need to either look at the DICOM Conformance Statement of the instance creator or look at a dump of the dataset to find the private creator for the tag.
```csharp
// get string value from predefined tag
var s = dataset.GetString(DicomTag.StudyDescription);

// get string value using group and element numbers
var s = dataset.GetString(new DicomTag(0x0008,0x1030));

// get string value from private tag
var s = dataset.GetString(new DicomTag(0x2001,0001,"PRIVATE CREATOR NAME"));
```

In the screenshot below of the output of the `Dicom.Dump.exe` tool, `GEMS_PARM_01` is the private creator, so the tag definition would be `new DicomTag(0x0043,0x0010,"GEMS_PARM_01")`. Note that you generally don't need to define the first two digits of a private tag as the library should sort that out for you based on the private creator.

![Windows 10 2019-12-27 13-54-34](https://user-images.githubusercontent.com/280475/71530646-70338080-28b0-11ea-84f0-2045ec83507a.png)

**Comment by amoerie** [comment]
You can automatically add the private creator as needed by using the following snippet:

```c#
                var dicomTag= new DicomTag(@group, element);

                // Automatically lookup private creator
                if (dicomTag.IsPrivate)
                {
                    for (ushort privateCreatorElement = 0x0010; privateCreatorElement <= 0x00ff; privateCreatorElement++)
                    {
                        if (privateCreatorElement == element)
                            continue;

                        var privateCreatorTag = new DicomTag(@group, privateCreatorElement);
                        if (dicomDataSet.TryGetSingleValue(privateCreatorTag, out string privateCreatorValue))
                        {
                            dicomTag= new DicomTag(@group, element, privateCreatorValue);
                            break;
                        }
                    }
                }
```

**Comment by gofal** [comment]
Close this due to inactivity. Please feel free to reopen this issue if you still face problems.
