### ISSUE TITLE
Unable to add private tag sequence to specific OEM's dataset

### ISSUE THREAD

**Issue by sdekker90** [fo-dicom/fo-dicom#963]
### Expected behavior
I am creating private tags using this method:
```
Dim dcm As DicomFile = DicomFile.Open(%path_to_dcm_file%)

Dim creator As New Dicom.DicomPrivateCreator("CM")

Dim PrivateCreatorTag As Dicom.DicomTag = DicomTag.Parse("dddd,0042")
PrivateCreatorTag.PrivateCreator = creator

Dim ds As New DicomDataset()

'The actual tags
ds.AddOrUpdate(Dicom.DicomVR.LO, DicomTag.Parse("dddd,4201"), "d451e53a-1cfe-4889-a5d1-8f39240ce69a")
ds.AddOrUpdate(Dicom.DicomVR.LO, DicomTag.Parse("dddd,4202"), "d451e53a-1cfe-4889-a5d1-8f39240ce69b")
ds.AddOrUpdate(Dicom.DicomVR.LO, DicomTag.Parse("dddd,4203"), "d451e53a-1cfe-4889-a5d1-8f39240ce69c")

'Add the sequence
Dim sq As New DicomSequence(PrivateCreatorTag, ds)
dcm.Dataset.AddOrUpdate(sq)

'Save under different name
dcm.Save(%path_to_dcm_file% & "_ready.dcm")
```

### Actual behavior
On most data sets, this works fine. The private tag sequence shows up and contains my private data sequence. On datasets of one OEM (BK), the method above does not work. Only the (DDDD,0010) PrivateCreator shows up in the dataset, the rest is not present when I view the file in MicroDICOM. 

### Steps to reproduce the behavior
Add a private sequence to the following dataset using the above method:
https://drive.google.com/open?id=1YBfZe5udTStWBA2ILh_ETjqkN_5EY8hi

This will produce a DICOM file like this:
https://drive.google.com/open?id=1t5CCTR6UIgfv0B-chKzDKv8-_C9_jHuE

### fo-dicom version and OS/platform
fo-dicom 4.0.2 on Windows 10, VB.NET

Your help would be much appreciated!

**Comment by gofal** [comment]
Hm, may be a bug in MicroDicom? Because with fo-dicom (using the tool DicomDump thats included in sourcecode), with ClearCanvas Viwer and with Synedra View Personal I can see the DicomTag (dddd,1042) in file "BK_with_incomplete_private_sequence.dcm" you uploaded on google drive.

Please also try some other tools to verify this.

**Comment by sdekker90** [comment]
**MicroDicom:**
dddd,0010 present, rest absent

**DVTk DicomEdit:** 
dddd,0010 present
dddd,1042 present but with incorrect data
Rest of tags missing

**Comment by sdekker90** [comment]
When I view the data sequence item in the debugger, all the tags are there.. they have the correct value as well.

![image](https://user-images.githubusercontent.com/25793879/72732066-3c890500-3b95-11ea-966e-96f0c3f1d08c.png)

**Comment by gofal** [comment]
The data is present in the BK datasets, but when displaying it, the viewer applications say: Unknown value representation ("UN"), but some data with 136 bytes. Thats why they do not parse it as DicomSequence.
fo-dicom has a feature, to extend the internal list of kown DicomTags, so that it knows how to interpret the private tags: (https://github.com/fo-dicom/fo-dicom/wiki/Adding-private-tags-to-dictionary). if you apply it, then the BK file should be displayed as desired with fo-dicom.

or you save the file with some explicit transfer syntax. Then every dicomtag is 2 bytes bigger, containing the ValueRepresentation. Also your private tags then do have the VR.

**Comment by sdekker90** [comment]
I checked the IsExplicitVR booleand you are correct, the BK datasets are Implicit and other datasets are explicit.

**Comment by sdekker90** [comment]
I went for saving the datasets in a explicit VR.. thanks so much.
