### ISSUE TITLE
Can't render a dicom file

### ISSUE THREAD

**Issue by WanderInCode** [fo-dicom/fo-dicom#966]
### Expected behavior
I'm trying render a dicom file to bitmap, most time following code works well. But sometimes, the program got stuck on dcmImage.RenderImage(), I have no idea why this happens.

var dicom = DicomFile.Open(imgFile);
DicomDataset dataset = dicom.Dataset;
DicomImage dcmImage = new DicomImage(dataset);
var render = dcmImage.RenderImage();

### Actual behavior
the program got stuck on dcmImage.RenderImage()

### Steps to reproduce the behavior
[B422433D.zip](https://github.com/fo-dicom/fo-dicom/files/4049557/B422433D.zip)
got stuck dicom file
### fo-dicom version and OS/platform
fo-dicom 4.0.3
fo-dicom.Desktop 4.0.3
windows 10 x64
net framework 4.5

**Comment by gofal** [comment]
I cant tell you in detail, but I am pretty sure the DICOM file is broken.
The codec runs into a loop because of invalid jpeg data. ClearCanvas and Synedra also cannot display this image.
Where do you have it from? Can you view this 739x975 pixel file with some other software successfully?

**Comment by WanderInCode** [comment]
> 
> 
> I cant tell you in detail, but I am pretty sure the DICOM file is broken.
> The codec runs into a loop because of invalid jpeg data. ClearCanvas and Synedra also cannot display this image.
> Where do you have it from? Can you view this 739x975 pixel file with some other software successfully?

i cant open it in other dicom viewer, it seems this file was broken exactly. can I have any chance to avoid this infinity loop? how can i found the image in dicom was broken?

**Comment by gofal** [comment]
sorry I cannot tell you for sure. the jpeg decoder expects valid jpeg stream. if something is broken, then in 99% the code crashes with some exception. This is a seldom case where the broken part is exactly where the implementation has a while-loop. on my side the rendering did not do an infinite loop but crashed after 60 seconds because of managed/unmanaged interop problem (stack corrupted). If we would add checks to the codec implementation everywhere where the stream may be corrupt, then the code would do more checks than actual computation.
If the application crashes reproducable on some images, then you should check the image could be broken. Try opening it with other applications. If none can open it, you can be pretty sure the file is broken.

**Comment by gofal** [comment]
Close this due to inactivity. Please feel free to reopen this issue if you still face problems.
