### ISSUE TITLE
Donating to fo-dicom project without PayPal Account?

### ISSUE THREAD

**Issue by atifc** [fo-dicom/fo-dicom#972]
Hello,

Is there any way to make donations possible without requiring a PayPal account?

Perhaps accepting donations could be simplified with a product like https://stripe.com/partners/donorbox?

Thank you.

**Comment by amoerie** [comment]
Actually I think the best way to do this would be using the Github sponsor button. 

@gofal Where do the donations go to, do you know?

**Comment by gofal** [comment]
Anders Gustavson created these buttons. He's the one who built fo-dicom out of mdcm.

**Comment by amoerie** [comment]
Fair enough, then I suppose it is he who should configure other options.

**Comment by anders9ustafsson** [comment]
@gofal @atifc @amoerie Those Paypal links currently direct to my Paypal account, but I can assure you that no one has used them for a long time :-) I received a contribution something like a year ago which I forwarded to Reinhard, since he is currently the primary maintainer and developer of this project.
Please feel free to replace those buttons with any solution that better fits the community's needs, to ensure that any contributions are directly beneficial to the *fo-dicom* project and its maintainers.

**Comment by atifc** [comment]
I used to maintain a repo myself and I know that even $5 counts, as it tells the maintainers that someone is actually using the product and thankful for it. I do not have a paypal account and do not wish to open one, and my organization most definitely is not able to use paypal (administrative hell).
Anyways, thank you for fo-dicom and I'm looking forward to testing your new donation button ;)

**Comment by amoerie** [comment]
That's very graceful of you @anders9ustafsson , but fo-dicom is now popular mostly because of your initial efforts, so for me it's not so obvious that you should forward any money. :-)

But I can appreciate your sentiment that future funds should go towards future development of fo-dicom in some way, so whatever you ( @gofal  and @anders9ustafsson ) decide on is fine by me.

**Comment by anders9ustafsson** [comment]
Thanks, @amoerie , for those very kind words! I feel though that (due to changed career path) I have not contributed to *fo-dicom* for a very long time, so it would only be natural that any contributions is shared among those who are maintaining the project right now.

BTW, it is great to see the amazing progress the project is still doing. In particular, I am encouraged to see the efforts of bringing *fo-dicom* to .NET Standard 2. Many thanks to everyone involved!

**Comment by amoerie** [comment]
Thanks for the encouragement! We've still got a long way ahead of us, but I think we'll end up in a nicer place than we are now. We have a lot of improvements that we still dream about, but as you probably very well know, a lot of this has to be done in spare time..

**Comment by amoerie** [comment]
Closing this issue as I don't think there are any plans to change the donation button in the near future.
