### ISSUE TITLE
Dicom.Network.Client.DicomClient does not raise RequestTimedOut if timeout occurs during association establishment

### ISSUE THREAD

**Issue by jbergstr** [fo-dicom/fo-dicom#981]
### Expected behavior
There are no requests in the queue. `Send` is called and association is opened to a destination that is not responding. Eventually, the `RequestTimedOut` event is raised.

### Actual behavior
No timeout event is raised; however, `StateChanged` is raised and the transition is to `DicomClientCompletedState`.

### Steps to reproduce the behavior
In the code below, the `TimeoutException` with the `"Real timeout event."` message is never thrown. Instead, the `"Fake timeout event."` one is.
```
public async Task DemoAsync(CancellationToken cancellationToken = default)
{
    _dicomClient.NegotiateAsyncOps();

    var completionSource = new TaskCompletionSource<bool>();

    EventHandler<AssociationAcceptedEventArgs> associationAccepted = (sender, e) => 
        completionSource.SetResult(true);
    _dicomClient.AssociationAccepted += associationAccepted;
    
    EventHandler<RequestTimedOutEventArgs> requestTimedOut = (sender, e) => 
        completionSource.SetException(new TimeoutException("Real timeout event."));
    _dicomClient.RequestTimedOut += requestTimedOut;

    EventHandler<AssociationRejectedEventArgs> associationRejected = (sender, e) => 
        completionSource.SetException(new DicomAssociationRejectedException(e.Result, e.Source, e.Reason));
    _dicomClient.AssociationRejected += associationRejected;

    EventHandler<StateChangedEventArgs> stateChanged = (sender, e) =>
    {
        if ((e.OldState is DicomClientConnectState 
                || e.OldState is DicomClientRequestAssociationState) 
            && e.NewState is DicomClientCompletedState)
            completionSource.SetException(new TimeoutException("Fake timeout event."));
    };
    _dicomClient.StateChanged += stateChanged;

    _ = _dicomClient.SendAsync(cancellationToken, 
        DicomClientCancellationMode.ImmediatelyReleaseAssociation);

    try
    {
        var result = await completionSource.Task;
    }
    catch (DicomAssociationRejectedException darex)
    {
        /* ... */
        throw;
    }
    catch (TimeoutException toex)
    {
        /* ... */
        throw;
    }
    catch (Exception ex) when (!(ex is OperationCanceledException))
    {
        /* ... */
        throw;
    }
    finally
    {
        _dicomClient.AssociationAccepted -= associationAccepted;
        _dicomClient.RequestTimedOut -= requestTimedOut;
        _dicomClient.AssociationRejected -= associationRejected;
        _dicomClient.StateChanged -= stateChanged;
    }
}
```

### fo-dicom version and OS/platform
fo-dicom 4.0.4

**Comment by amoerie** [comment]
Well, I don't mean to be pedantic, but there isn't a request that timed out, is there. The request was never even sent. In the current implementation, these two scenarios will trigger a request timeout:

- The request takes too long to send (think C-STORE requests for very large files)
- The request is sent but the server is not responding.

Why exactly do you need to specifically association request timeouts? Do they occur often in your setup?

We could perhaps add a AssociationTimeout event to DicomClient.

**Comment by jbergstr** [comment]
You are quite correct in that that there is not a C-something-RQ timeout happening here. (Although the RQ in A-ASSOCIATE-RQ _does_ mean request...) All in all, considering e.g. large C-STOREs, it would indeed make sense to have a separate timeout value for the association since normally they should be quite quick to establish.

In my scenario, I prefer to catch all sorts of network-related issues as soon as possible; basically I try to be able to communicate to other subsystems that the destination is not reachable even before the first request has been sent. One part of my setup is that the destination is chosen dynamically, and in certain cases the data to send may even depend on the destination endpoint.

Of course, it is also useful for plain diagnostic purposes to know in which part of the operation the problem actually occurred.

And yes, association timeouts (or rather unreachable destination servers) do occur frequently enough that it makes sense for me to catch them.

**Comment by amoerie** [comment]
Hi @jbergstr, sorry for taking so long to answer your questions. This whole corona business had a large impact, and I also recently became a father. I'm afraid that non-essential things like open source work then get pushed back to the background. :-)

To answer your issue: 

At my workplace, we use the DICOM network layer extensively, and strangely we don't see this problem at all. Either the host is unreachable, in which case Socket exceptions occur, or the host does respond timely to association requests, because it's such a lightweight message to exchange. Usually it's the actual DICOM requests (FIND, MOVE, etc.) that can suffer from timeouts.

Furthermore, I won't deny that adding proper timeout detection to administrative requests (Association Request, Association Release, etc.) would require a non trivial amount of work to implement and test. Historically, testing the timeout behavior in unit tests has also been challenging and fickle in our CI environment. 

So, considering the facts that
- As far as I'm aware, you're the only person asking for this
- I have data from my company that this is not an issue in our pretty large scale use case
- It is not trivial to implement

I won't spend any time on this issue. However, I am willing review any pull requests, and give pointers if you wish to implement this yourself. I hope you can understand this decision.
