### ISSUE TITLE
DicomCFindRequest with Private Dicomtag

### ISSUE THREAD

**Issue by Nanisnb** [fo-dicom/fo-dicom#990]
I have 2 services 

In the first on in implente a Worklist SCU  has set an private DicomTag in the request

var cfind = Dicom.Network.DicomCFindRequest.CreateWorklistQuery();
cfind.Dataset.AddOrUpdate<string>(new Dicom.DicomTag(0x9991, 0x9992, "FIELD"), "customvalue");
...
await client.AddRequestAsync(cfind);
 await client.SendAsync();

In the seconds service (Worklist SCP)in try to read this value, but i the return result is empty.

I place this code when i'm processig OnCFindRequest Handler.

var v = request.GetSingleValueOrDefault(new DicomTag(0x9991, 0x9992, "FIELD"), string.Empty);
or
var dtag = request.GetPrivateTag(new DicomTag(0x9991, 0x9992, "FIELD"));
var r= request.GetSingleValueOrDefault(dtag, string.Empty);

seens like the Dicomtag ins't been submit in the request.

Tanks in advance

Nani

**Comment by gofal** [comment]
There are several traps:

- first of all you did not create the private Tag correctly. If the SCU only adds a single Tag with `AddOrUpdate(new DicomTag(...` then this is not complete. You also need to add a PrivateCreator tag. fo-dicom does this for you. But this requires that your element-value is below 0xFF. 
So you have to call:

        cfind.Dataset.AddOrUpdate(new Dicom.DicomTag(0x9991, 0x0092, "FIELD"), "customvalue");


- second. Now you can get the value with `request.GetSingleValueOrDefault(new DicomTag(0x9991, 0x0092, "FIELD"), string.Empty);` But this will still return string.empty. 
If you try `request.Dataset.GetValues<object>(new DicomTag(0x9991, 0x0092, "FIELD"))` then you will get an object-array `object[12] { 99, 117, 115, 116, 111, 109, ...}`. 
This is because each DicomTag has a binary content which has to be parsed. So the ValueRepresentation defines how to interpret the values. the 12 bytes may be an array of 3 integers, may be an string with 12 characters, may be signed or unsigned words, ...
While for Standard-Tags there is an internal dictionary how to parse these tags, this is not possible for private tags.
You can either access the byte-stream by calling `request.Dataset.GetDicomItem<DicomItem>(new DicomTag(0x9991, 0x0092, "FIELD")).ByteBuffer` and then handle the parsing yourself...
... or you extend the internal Dictionary.
So call somewhere on application start of your Worklist server the following code:

         DicomDictionary.Default.Add(new DicomDictionaryEntry(new DicomTag(0x9991, 0x0092, "FIELD"), "my private", "PrivField", DicomVM.VM_1, false, DicomVR.LT));

Then you later can call `request.Dataset.GetSingleValueOrDefault(new DicomTag(0x9991, 0x0092, "FIELD"), string.Empty)` and will retrieve your value "customvalue".

**Comment by gofal** [comment]
Close this due to inactivity. Please feel free to reopen this issue if you still face problems.
