### ISSUE TITLE
Guidelines for displaying images in WPF

### ISSUE THREAD

**Issue by Evangelink** [fo-dicom/fo-dicom#993]
Hi there,

As part of my evaluation of this framework I am trying to build a naive video-player for DICOM files. The clips will usually contain a couple thousands frames.

Having a quick look at the API and the code it seems better to use `FileReadOption.ReadLargeOnDemand` and to instantiate only once the `DicomImage`, is it correct?

I am also wondering whether the following call is good enough `dicomImage.RenderImage(frameNumber).As<ImageSource>()` or if I shall keep a reference to the `IImage` returned by `RenderImage(frameNumber)` and dispose it once I move to the next frame.

If you have any tips to share, please feel free to. By the way, if you think some tips are worth keeping I'd be happy to push a doc PR.

Cheers

PS: I am using fo-dicom.Desktop 4.0.4

**Comment by tboby** [comment]
This is possibly more of a discussion topic, but here are some notes on the bottlenecks from my experience with trying to render multi-frame dicoms in realtime.

- RenderImage is single-threaded per DicomImageFile
- The JPEG decoding done by RenderImage (through the Efferent native libraries) uses a temporary file on disk
- The JPEG decoding allocates a byte[] per frame
- The rendering step in fo-dicom allocates several byte[] per frame in the pipeline
- The final conversion from IImage to Bitmap/etc will generally result in allocating another byte[]

Basically, the bottleneck appears to be GC time due to immense memory pressure, and IO latency for the JPEG decoding. Significant speed-up can be found by creating multiple DicomImageFiles for the same dataset, and rendering frames in parallel. 

*However*, none of this is particularly significant compared to the time taken by *WPF* steps, such as converting a Bitmap into a BitmapSource. It's also not practical to store significant numbers of rendered frames in memory as Bitmaps can be huge for medical images.

fo-dicom 5.0 has some improvements on the memory allocation, and hopefully more coming soon looking at current PRs.
