### ISSUE TITLE
DicomDictionary.Default["invalid-keyword"] throws nullreference exception

### ISSUE THREAD

**Issue by smithago** [fo-dicom/fo-dicom#996]
### Expected behavior
null return

### Actual behavior
throws nullreference exception

### Steps to reproduce the behavior
.net core package reference
using Dicom;
var dicomTag = DicomDictionary.Default["invalid-keyword"];
//attributeId was a string with invalid keyword. so try

### fo-dicom version and OS/platform
4.0.4

Also what is the best way to get a pdb to debug into dicom from VS?. I an create a PR for bugs I find.

**Comment by smithago** [comment]
ping. Can someone take a look and fix this please

**Comment by gofal** [comment]
sure, I will do asap, unless someone else does meanwhile.

**Comment by jbl42** [comment]
I have the same issue and as far as I could track it down looking at the source it happens in the method `public DicomTag this[string keyword]` of `class DicomDictionary` when it tries to continue the search in private dictionaries in the `_private` member field. If the `DicomDictionary` was created through `public DicomDictionary this[DicomPrivateCreator creator]` the private ctor overload `DicomDictionary(DicomPrivateCreator creator)` is used resulting in the `_private` field being null.
`public DicomTag this[string keyword]` should do a null check before the `foreach` of `_private.Values`.

This mainly happens when `DicomDictionaryReader `is used to read private DICOM tags from XML on creation of subdicts for private creators.

Sorry for not providing a PR, I currently have no dev-env at hand.

**Comment by smithago** [comment]
@gofal will this be fixed soon?

**Comment by gofal** [comment]
Sure it will be fixed. I'm starting now. Thanks to @jbl42 for tracking this digging into this!

**Comment by gofal** [comment]
> Also what is the best way to get a pdb to debug into dicom from VS?. I an create a PR for bugs I find.

I assume the best would be, to checkout the lastest source, build the project you need and debug into latest version. development branch may already have some changes that are not updated on nuget. So I always recommend debugging with dev-branch.
